### ISSUE TITLE
"TypeError: e.keys is not a function" says cordova.js

### ISSUE THREAD

**Issue by rdrg** [EddyVerbruggen/cordova-plugin-googleplus#102]
<img width="767" alt="screen shot 2015-08-25 at 12 37 50 pm" src="https://cloud.githubusercontent.com/assets/1239954/9471516/210b88a6-4b27-11e5-8ebe-4c75ebd6b393.png">

Hi eddy, everybody,

thanks for the great work on this plugin! 

I'm getting the error shown above in the img, after starting the login process. I'm not sure where to start debugging. Did any of you get something similar? Any help greatly appreciated. My cordova version is 5.2 by the way.

best 

rodrigo

**Comment by EddyVerbruggen** [comment]
Woaah, nasty error - iOS or Android?

**Comment by rdrg** [comment]
This is android, although it didn't work in IOS either, but I couldn't get the logs to debug on IOS, yet. I'll try to get more info about IOS in the afternoon. Thanks for looking at this!

**Comment by EddyVerbruggen** [comment]
Can you share your code calling the plugin, especially the callback handlers you pass in?

**Comment by rdrg** [comment]
yes, of course:
```
window.plugins.googleplus.login({
	//'iOSApiKey': iOSApiKey, 
	scopes: "email https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/contacts.readonly"
	}, function (uData) {
        $localStorage.googleAuth = {
		    token   : uData.oauthToken,
		    expires : uData.expires
             };
	     uData.imgUrl = uData.imageUrl.replace('sz=50', 'sz=160');
         verifyAndBecomeUser(uData);
	}, function (msg) {
	      console.log('glogin error', msg);
	      $ionicLoading.hide();
});
```
I'm using ionic, as you can see. Android sdk target is 23. I'm looking at the IOS version now.

**Comment by rdrg** [comment]
Hey Eddy,

just tested again, with the same code, and it just worked. I don't know what the heck happened. I'm terribly sorry about taking up your time. I got something to point out about IOS, but I should open another issue about it. I guess you can close this one.

**Comment by EddyVerbruggen** [comment]
OK, thanks for reporting back. I sincerely had no clue what was going on :)
