### ISSUE TITLE
"login" and "trySilentLogin" not work in iOS (but Android is work perfect)

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-googleplus#104]
hi @EddyVerbruggen 
I am using PGB 5.1.1 + your latest 4.0.1 version from npm + all latest official core plugin +ipad mini 8.4.1 (12H321)

according to this
https://github.com/EddyVerbruggen/cordova-plugin-googleplus
and "get a configuration file here"
I am very sure that I got a correct "REVERSED_CLIENT_ID" in GoogleService-Info.plist and build with PGB Success

but...after this
when I use...
"login" and "trySilentLogin"，not work !!! no any response or alert message
"isAvailable" and "logout" and "disconnect"，work !!!

I tried many times

**Comment by EddyVerbruggen** [comment]
Perhaps try an older version of the plugin. Not sure how to assist you with this without posting your app code.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I will try the older version...

well...
my full code
```
window.plugins.googleplus.login(
    {

    },
    function (obj) {
      alert(JSON.stringify(obj)); // do something useful instead of alerting
    },
    function (msg) {
      alert('error: ' + msg);
    }
);

window.plugins.googleplus.trySilentLogin(
    {},
    function (obj) {
      alert(JSON.stringify(obj)); // do something useful instead of alerting
    },
    function (msg) {
      alert('error: ' + msg);
    }
);
```

**Comment by andrewb273** [comment]
I had issues likes this, thought my `REVERSED_CLIENT_ID` was correct, and it sort of was, but it was for a different build ID.

**Comment by bau720123** [comment]
hi @andrewb273 
so you mean is you have the same situation
"login" and "trySilentLogin" will all "no any response"
right ?

**Comment by andrewb273** [comment]
@bau720123 Not necessarily the same situation, I don't think I was getting the exact error message "no any response".

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I tried many times but still not work in iOS 8.4
I use Xcode to detect some wrong message when I use "login" and "trySilentLogin" method

```
Sep  9 10:46:49 kodzutsumiteki-iPad jQuerytestMobileforPhoneGapEdition[1155] <Warning>: *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> Your app must support the following URL schemes: com.littlebau.phonegap, com.googleusercontent.apps.909119150051-0g74v62g7ifqf1qflvejg1lvf62ih16j
```
kodzutsumiteki-iPad is my ipad name
jQuerytestMobileforPhoneGapEdition is my app's name
and I am very sure that "REVERSED_CLIENT_ID" => "com.littlebau.phonegap, com.googleusercontent.apps.909119150051-0g74v62g7ifqf1qflvejg1lvf62ih16j" is correct

could you give me some hint ?

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
it look like @ullasmohan have the same problem
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/82

**Comment by bau720123** [comment]
solved at
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/82
