### ISSUE TITLE
Armv7s support

### ISSUE THREAD

**Issue by briepace** [EddyVerbruggen/cordova-plugin-googleplus#110]
When trying to build a release version of a Cordova app for ios using "cordova build ios --release --device", the build fails with the error:

ld: file is universal (4 slices) but does not contain a(n) armv7s slice: PSHoursApp/Plugins/cordova-plugin-googleplus/GoogleSignIn.framework/GoogleSignIn file 'PSHoursApp/Plugins/cordova-plugin-googleplus/GoogleSignIn.framework/GoogleSignIn' for architecture armv7s

If I modify platforms/ios/cordova/lib/build.js and remove armv7s from line 157, the build happens with no problem; but that is not a correct solution.

Edit: To clarify in case line numbers are different. Change "'ARCHS=armv7 armv7s arm64'" to "'ARCHS=armv7 arm64'".

**Comment by poornerd** [comment]
I just got this error as well

**Comment by phw** [comment]
Got that as well. Disabling armv7s would be the way to go, unfortunately cordova doesn't allow you to change the architectures other as @briepace described above. It was fixed in cordova but not yet released, see https://issues.apache.org/jira/browse/CB-8788 (unfortunately this does still not allow you to configure ARCHS, but they removed armv7s from their standards).

Marking this as wontfix since there is nothing this plugin can do about it.

**Comment by louisdoe** [comment]
I get this error as well !

**Comment by louisdoe** [comment]
I had to remove google login from my ionic temporarily...ouch !

Do you think you can have a look in the next few days ?

**Comment by louisdoe** [comment]
Hi everybody, is the google login working now ? Can I put it back in my app ?

Thanks ;)

**Comment by Tommy10802** [comment]
Hellou, i want to ask you if it is some news in this issues, because i have same problem as above, when i try to build release version of app with this plugin on ios.
Thx

**Comment by briepace** [comment]
@louisdoe I actually work at PointSource and spoke with the developer who made the fork you linked to. He said that a pull request was done back into this project and was accepted. So any changes that were done in the fork should already be reflect in this repo.

**Comment by louisdoe** [comment]
Ok @briepace thanks !
