### ISSUE TITLE
No longer getting extended profile details on login

### ISSUE THREAD

**Issue by andrewb273** [EddyVerbruggen/cordova-plugin-googleplus#111]
Previously, we used to get the following fields:
* `givenName`
* `familyName`
* `gender`

amongst others in the login response. But now we only get `displayName` instead of them. Is there a way to still get the above fields, or does G+ no longer offer that?

**Comment by andrewb273** [comment]
Our QA team also pointed out that it's not asking for the same list of permissions, though unfortunately I don't know that list difference.

**Comment by sshadmand** [comment]
I am no longer receiving User Image.

**Comment by ashishsajwan** [comment]
:1 .. any workaround for this ???

**Comment by markusila** [comment]
Yeees)
use $http and oauthtoken to request users data
```$http.get('https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token='+obj.oauthToken).
                            then(function(response) {
                              console.log(response)
                              // this callback will be called asynchronously
                              // when the response is available'

                            }, function(response) {
                              console.log(response)
                              // called asynchronously if an error occurs
                              // or server returns response with an error status.
                            });```

**Comment by markusila** [comment]
Yeees)
use $http and oauthtoken to request users data
```
                         $http.get('https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token='+obj.oauthToken).
                            then(function(response) {
                              console.log(response)
                              // this callback will be called asynchronously
                              // when the response is available'

                            }, function(response) {
                              console.log(response)
                              // called asynchronously if an error occurs
                              // or server returns response with an error status.
                            });```

**Comment by EddyVerbruggen** [comment]
Cool, @markusila, I hope that help others!

**Comment by maries-15** [comment]
I couldn't solved the problem adding 'offline': true

$cordovaGooglePlus.login({'offline':true})
.then(function(data){
console.log("success")
}, function(error){
console.log("error")
});

**Comment by markusila** [comment]
@maries-15 show me some more code, i'll try to help you

**Comment by maries-15** [comment]
it is all my code.
what do you want to show exactly?

**Comment by maries-15** [comment]
@markusila it is all my code.
what do you want to see exactly?

**Comment by SidMehta** [comment]
@markusila I am using the workaround you mentioned. But I am "Failed to retrieve token: Unknown" error. I have set up the sha 1 on the developer console properly too.

**Comment by sebastialonso** [comment]
@SidMehta I change the scopes parameter to 'profile' and I only get the same response that you mention. Without any scope, I only get the email. It's really frustrating!

Can the maintainer @EddyVerbruggen shed some light about this critical issue?

**Comment by sammuggPS** [comment]
Hey @andrewb273, @SidMehta, @sebastialonso, and others,

I just merged a significant update yesterday that updated the Android side to use Google Sign-In and refactored plugin usage. The [current documentation](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/README.md) is up to date with those changes. You should check it out. Let me know if you have any questions!

Happy Coding,
~Sam
P.S. If your issue gets resolved, please close it!

**Comment by sebastialonso** [comment]
Awesome, I'll try it tonight and report back.
Thanks!

**Comment by andrewb273** [comment]
All good from my end, will close this issue

**Comment by vivekpd15** [comment]
Hi,

How did you guys manage to get the gender using the new flow?

**Comment by sammuggPS** [comment]
Hey @vivekpd15, refer to our documentation to learn about what is being returned from this plugin.

Also, if you have additional questions, please open a separate ticket as this one has been closed.
