### ISSUE TITLE
User can't cancel login after login is screen is called

### ISSUE THREAD

**Issue by sshadmand** [EddyVerbruggen/cordova-plugin-googleplus#112]
Thanks for the plugin, works great :) 

On iOS (In your demo) the Google login screen does not give the user any way to cancel the login to return to the app. Is there a way to enable this option?

**Comment by EddyVerbruggen** [comment]
That's actually one of my personal annoyances with most OAuth providers - you can't back out gracefully. It's Google's login/consent screen, not something this plugin has control over.

**Comment by sshadmand** [comment]
Thanks for the quick response :) Looks like it performs more smoothly on the device than on the simulator.

**Comment by Mojo90** [comment]
I discovered this recently and yes it is very annoying. Had a look at "dingur-App" (http://www.dingur.com). No beautiful App but they have a Google Sign in as well. For me it seems as they are showing it in ```SfSafariViewController``` --> "Done" is definetely Possible to cancel the screen. Had already a look at your code @EddyVerbruggen but no Idea where to kick in this controller. Maybe you can check out that app and it seems to be that it is possible (also not sure if it is an hack or not...)

**Comment by tomasbedrich** [comment]
If you download the latest [Google Sign In SDK](https://developers.google.com/identity/sign-in/ios/sdk/) and run a sample project, you can also see there a webview with a cancel button. So definetely it is possible.

I will try to create a PR soon.

**Comment by Mojo90** [comment]
Oh great didn't see that. I just replaced the ```GoogleSignIn.framework``` with the new one in my Project and it does work. Thank god for ```SfSafariViewController```😁

**Comment by tomasbedrich** [comment]
Yes, you are right. I was a bit exhausted yesterday. So in the meantime, if you [use this fork](https://github.com/phw/cordova-plugin-googleplus/tree/ios-updated-google-framework), it works.

**Comment by EddyVerbruggen** [comment]
Thanks to #153 v4.0.6 now has an option to cancel the OAuth flow.
