### ISSUE TITLE
"google-play-services.jar" already exists

### ISSUE THREAD

**Issue by ChristopheDaVinci** [EddyVerbruggen/cordova-plugin-googleplus#117]
I'm experiencing a problem when adding this googleplus plugin in conjunction with the azure NotificationHub plugin ( https://github.com/sgrebnov/cordova-plugin-azure-notificationhub ). The moment i add the plugin, it gives me this error:

>Failed to install 'cordova-plugin-googleplayservices':Error Uh oh! (TaskId:11)
>  "C:\Code\Javascript\CordovaProjects\PushNotificationSolution\Sample8\platforms\android\libs\google-play-services.jar" already exists! (TaskId:11)
1>      at Object.module.exports.common.copyNewFile (C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.js:67:19) (TaskId:11)
1>      at Object.module.exports.source-file.install (C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:78:20) (TaskId:11)
1>      at installWrapper (C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\cordova-lib\src\platforms\platforms.js:77:32) (TaskId:11)
1>      at Object.ActionStack.process (C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25) (TaskId:11)
1>      at handleInstall (C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:550:20) (TaskId:11)
1>      at C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:342:28 (TaskId:11)
1>      at _fulfilled (C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\q\q.js:787:54) (TaskId:11)
1>      at self.promiseDispatch.done (C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\q\q.js:816:30) (TaskId:11)
1>      at Promise.promise.promiseDispatch (C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\q\q.js:749:13) (TaskId:11)
1>      at C:\Users\christophe.DVIT\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\5.1.1\node_modules\cordova\node_modules\q\q.js:509:49 (TaskId:11)

The problem lies in the fact that there are two google-play-services.jar in my project. But i have no idea how to fix this problem. Has anyone experienced the same problem?

![Image of bug](http://i57.tinypic.com/o5rk93.jpg)

**Comment by EddyVerbruggen** [comment]
This plugin no longer includes the jar, so that's out of the equation.
