### ISSUE TITLE
Plugins/cordova-plugin-googleplus/GoogleOpenSource.framework/GoogleOpenSource(GTLDateTime.o)' does not contain bitcode.

### ISSUE THREAD

**Issue by jinuem** [EddyVerbruggen/cordova-plugin-googleplus#120]
Plugin works perfectly with Xcode 6... but when i upgraded to Xcode 7.. i get this error.

/Plugins/cordova-plugin-googleplus/GoogleOpenSource.framework/GoogleOpenSource(GTLDateTime.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Even i enabled BITCODE in the project. its not working properly

**Comment by EddyVerbruggen** [comment]
You need to disable bitcode in the build settings of the app target in XCode 7. That's because the GoogleSignIn library itself is not (yet) built with bitcode. So that message refers to the library, not your app.

**Comment by jinuem** [comment]
If i did that and build the app.. Google Login is not working :(

**Comment by Freundschaft** [comment]
with the release of ios9 stable and xcode 7 stable, has google released a bitcode built library already?

**Comment by Freundschaft** [comment]
https://developers.google.com/identity/sign-in/ios/sdk/google_signin_sdk_2_2_0.zip states that 

>2015-07-15 -- v2.2.0
>- Compatible with iOS 9 (beta).
>- Adds descriptive identifiers for GIDSignInButton's Auto Layout constraints.
>- |signInSilently| no longer requires setting |uiDelegate|.

does that fix the bitcode issue?

**Comment by jinuem** [comment]
@Freundschaft  Tried 2.2.0 Version. But still getting that bitcode error.. Even i tried latest one . 2.3.2. Same issue... 
@EddyVerbruggen do you have any idea to fix this on Xcode 7 apart from disabling bitcode?

**Comment by Freundschaft** [comment]
ah okay sorry, it even says on https://developers.google.com/identity/sign-in/ios/release?hl=en 

Compatible with iOS 9 (beta). Note that this version of the Sign-In SDK does not include bitcode, so you must set ENABLE_BITCODE to NO in your project if you use Xcode 7.

Probably we have to wait for a bitcode compatible release then?

**Comment by jinuem** [comment]
@Freundschaft  Only 2.2.0 mentioned about changing NO to BITCODE..  In other version they didnt mention anything about BITCODE...  Damn i can't go back to XCode 6 bcoz it doesnt support iOS9 ... We stuck here :(

**Comment by Freundschaft** [comment]
I think disabling bitcode shouldnt be a breaking issue
and as long as the changelogs dont mention anything about bitcode I would not assume that something changed, apparently the analytics sdks suffer from the same issue.

**Comment by socheat1994** [comment]
Anyone have any solution for me, currently I use the latest of Xcode 8.1 with swift 3.1 and I face this problem too. my target IOS8 up and I set the enable yes to project setting. I cannot set NO to project setting because it'll be error more than this if I said to No
