### ISSUE TITLE
Build failed : reason: dexDebug

### ISSUE THREAD

**Issue by remcova** [EddyVerbruggen/cordova-plugin-googleplus#125]
Hello,

I am making a app on the Android platform and I ran the command "phonegap build android" but sadly I received a error. I installed the plugin with this command: 
"cordova plugin add cordova-plugin-googleplus"

I also added the code in to the config.xml but I don't really know what reversed_client_id means. Is this just the Client ID which has this text on the end: "apps.googleusercontent.com" ?

Here is a screenshot of the error; https://gyazo.com/8b23ae1fd30c8b211642981b93f2406a

**Comment by balicekt** [comment]
Hey, I have figured it out by edit plugin.xml becuase plugin cordova-plugin-googleplayservices is deprecetad. 

install plugin like this: 
1) donwload this plugin from github to your computer
2) open plugin.xml and change this tree lines: 

    
    
    <dependency id="cordova-plugin-googleplayservices" /> 

TO:

    <framework src="com.google.android.gms:play-services-plus:+" />
    <framework src="com.google.android.gms:play-services-identity:+" />
    

3) install 
cordova plugin add ~/Downloads/cordova-plugin-googleplus/ --variable REVERSED_CLIENT_ID=yourCODEID

and it should work
