### ISSUE TITLE
Can we implement the new sign-in sdk released on sep 29,2015?

### ISSUE THREAD

**Issue by udhaya10** [EddyVerbruggen/cordova-plugin-googleplus#128]
Hope this will resolve the need of having the Google plus app for singing with Google account in iOS.

**Comment by Freundschaft** [comment]
I realized one of the issues using that one is that a specific ios verison is required, right?

**Comment by phw** [comment]
I tested the upgrade in this branch: https://github.com/phw/cordova-plugin-googleplus/tree/ios-updated-google-framework

Works so far and looks like it gets rid of the GooglePlus.framework dependency. I think we could also remove the dependency on GoogleOpenSource.framework, but this gets referenced directly in cordova-plugin-googleplus, not sure if this can be removed.

But it requires at least iOS 7, so if this gets added this plugin should probably take care of setting the target accordingly in the project settings.
