### ISSUE TITLE
app native?

### ISSUE THREAD

**Issue by missjewel** [EddyVerbruggen/cordova-plugin-googleplus#130]
This plugin works or for a native app also works for a hybrid?

**Comment by EddyVerbruggen** [comment]
This plugin is for Cordova / PhoneGap.

**Comment by missjewel** [comment]
sorry pero no sé en que parte colocar el ClientID de google plus en tu documentación no se explica. Estoy probando en un dispositivo Android.

**Comment by missjewel** [comment]
sorry but I do not know where in place the ClientID of google plus your documentation is not explained. I'm testing on an Android device.
