### ISSUE TITLE
window.plugins.googleplus not defined

### ISSUE THREAD

**Issue by KaptainKrayola** [EddyVerbruggen/cordova-plugin-googleplus#132]
I followed the directions but window.plugins only has one object called "insomnia".  So whenever i try to call a method on window.plugins.googleplus it's not defined and throws an error.

**Comment by Argetloum** [comment]
Same error for me.

**Comment by Argetloum** [comment]
Hi @KaptainKrayola ,
Maybe the device isn't ready.

Did you try to test after that:
```
document.addEventListener('deviceready', function()
{
    // your code with window.plugins.googleplus....
}, true);
```

**Comment by KaptainKrayola** [comment]
Yes, I added some checks in to several different spots.  I did a console.log of windows.plugins inside the handler for onDeviceReady and the only thing that it shows is "insomnia" so it's like googleplus isn't getting loaded into the window.plugins

**Comment by KaptainKrayola** [comment]
@Argetloum - are you able to get it to work?

**Comment by Argetloum** [comment]
@KaptainKrayola yup, it works fine for me.

**Comment by KaptainKrayola** [comment]
So I'm using the demo app and in my index.js i have 

 bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
onDeviceReady: function() {
        app.receivedEvent('deviceready');
        console.log("Device is ready...");
        window.plugins.googleplus.isAvailable(function(avail) {alert(avail)});
    },

In the console I see (as expected)
[phonegap] [console.log] Received Event: deviceready
[phonegap] [console.log] Device is ready...

then the error :
this throws the error "Cannot read property isAvailable of undefined" then lists the path and file.

@Argetloum  - would you mind pushing up some sample code that you have it working with so I can see how you have it done?

**Comment by Argetloum** [comment]
Your code is right I guess.. I did the same thing.
Maybe the plugin isn't well installed. Did you tried to remove and re-add the plugin ?

**Comment by KaptainKrayola** [comment]
Yep, removed and reinstalled.  I also created a whole new project.  I wonder if it's a version issue?

PhoneGap version 5.3.6
Cordova version 5.3.3
NodeJS version 0.12.2

Any ideas there?

**Comment by KaptainKrayola** [comment]
Update - this works perfectly fine if i build an apk and install it on the phone.  It seems that doing a "phonegap serve" to try and test/debug on the phone is the problem.

**Comment by KaptainKrayola** [comment]
Apparently Phonegap Serve just doesn't support 3rd party apps unless they are pure JS.  This was my whole problem and not actually a problem with this plugin.  Thanks for the help @Argetloum

**Comment by Gajendrasinh** [comment]
I use google pluse login its not workin in ionic

Function

$scope.googleSignIn = function() {
    $ionicLoading.show({
      template: 'Logging in...'
    });

    console.log(window.plugins);

    window.plugins.googleplus.login({
        'webClientId': 'kov839pq64s.apps.googleusercontent.com',
        'offline': true
      },
        function (user_data) {
          console.log(user_data);

          //for the purpose of this example I will store user data on local storage
          UserService.setUser({
            userID: user_data.userId,
            name: user_data.displayName,
            email: user_data.email,
            picture: user_data.imageUrl,
            accessToken: user_data.accessToken,
            idToken: user_data.idToken
          });

          $ionicLoading.hide();
          $state.go('app.home');
        },
        function (msg) {
          $ionicLoading.hide();
          console.log(msg);
        }
    );
  };

Error : TypeError: Cannot read property 'googleplus' of undefined
    at ChildScope.$scope.googleSignIn (controllers.js:13)

**Comment by tylerstephens814** [comment]
I have the same problem as @Gajendrasinh

**Comment by surajitdeveloper** [comment]
I have the same problem as @Gajendrasinh

**Comment by kunwar-shah** [comment]
Its too late to response but i will leave my comment so someone may find this useful.

Googleplus plugin only works when you run plugin from file system means file:///android_asset/www/index.html. Do not use any extra switch when you run from CLI. 
Simply use this command to  run : ionic cordova run android.

If  you use command like this: ionic cordova run android -l -c -s this will load plugin from url like : http://192.168.178.22:810 or something like that. So googleplus plugin will not work with url. I don't know why but thats what i find while debugging.I Hope this will fix googleplus undefined error.

**Comment by matunoa** [comment]
@KaptainKrayola @Gajendrasinh @surajitdeveloper @tylerstephens814 

I'm also getting Same Error : TypeError: Cannot read property 'googleplus' of undefined

This error is coming in real device, On Browser its working fine.

![WhatsApp Image 2020-01-20 at 7 37 02 PM](https://user-images.githubusercontent.com/60103763/72734830-6b66a180-3bbc-11ea-9ed9-0b3f4af44f06.jpeg)
