### ISSUE TITLE
Phonegap Build app : where to put google-services and google-services.json

### ISSUE THREAD

**Issue by louisdoe** [EddyVerbruggen/cordova-plugin-googleplus#134]
Hi Eddy,

I get this error on login : "service not available" (Android emulator, ionic app).

In the README you mention in "3.Google+ API setup" that we have to "follow Step 1 of this guide", but what should we do with the cloned google-services folder ?

And then if we need the configuration file: google-services.json, where should we put it if we phonegap build ?

I think this would be useful to explain in the README.

Thanks for your help

Louis

**Comment by Dineshrajaa** [comment]
+1

**Comment by rviteri** [comment]
+1

**Comment by antoninobajeli** [comment]
+1

**Comment by felipecaparelli** [comment]
1+

**Comment by bcabs** [comment]
+1

**Comment by Silvercast** [comment]
+1

**Comment by Silvercast** [comment]
the documentation says ``` There is no need to add the generated google-services.json file into your cordova project.``` . FYI

**Comment by SidMehta** [comment]
+1

**Comment by twicejr** [comment]
+1

**Comment by sammuggPS** [comment]
@twicejr, the point of the quote @Silvercast is that for this plugin in particular, the google-services.json and equivalent .plist for iOS they do not need to be included in the project.
