### ISSUE TITLE
How to use this plugin in Phonegap build?

### ISSUE THREAD

**Issue by Dineshrajaa** [EddyVerbruggen/cordova-plugin-googleplus#143]
Hello,
I am trying to use this plugin in an application which I am building using phonegap build service
I have included the necessary configurations in the config.xml after registering the application in Google developer console I could get the app working (i.e.,its generating the oauth token)when I build it using my local cordova cli(5.3.3)  , but when I try to run the app built with phonegap build service I am getting 
"Failed to Receive Acces token".

can someone please shed some light on how to fix this issue?

**Comment by bau720123** [comment]
hi @DanielOchoa 
what the syntax code in your config.xml (PGB)
have you ever use other 3rd plugin in your PGB ?

**Comment by Dineshrajaa** [comment]
<gap:plugin name="cordova-plugin-googleplus" source="npm">
            <param name="REVERSED_CLIENT_ID" value="602230551806-lusrd2is8ch01tud3l8i2ecnmhdq9gk0.apps.googleusercontent.com" />
            
        </gap:plugin>
This is the syntax which I am using,
Ya I have used different Third Party Plugins bau720123

**Comment by Silvercast** [comment]
the documentation says ``` There is no need to add the generated google-services.json file into your cordova project.```

**Comment by Dineshrajaa** [comment]
ya forgot to close this issue :)anyway Thanks for pointing it.
