### ISSUE TITLE
"phonegap-plugin-push" related problem

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-googleplus#147]
hi @EddyVerbruggen 
all detail at here
https://github.com/phonegap/phonegap-plugin-push/issues/273
hope can solve in the future

**Comment by EddyVerbruggen** [comment]
OK, publishes 4.0.4, hopep that helps!

**Comment by bau720123** [comment]
solved
thanks @EddyVerbruggen
