### ISSUE TITLE
PhoneGap Build Error (Android) #85 repeated 

### ISSUE THREAD

**Issue by algae514** [EddyVerbruggen/cordova-plugin-googleplus#148]
Hi Eddy,

This is an old issue so I have put the same subject.
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/85

I have seen this issue again when I used 
<gap:plugin name="cordova-plugin-googleplus" source="npm"  > 
about some 15-20 min ago.

I saw you have committed 2 hours ago, so I put version to 4.0.0 and it was working fine.
<gap:plugin name="cordova-plugin-googleplus" source="npm"  version="4.0.0">

Note : 
1. I have been using only phonegap build. 
2. logs are same as mentioned in earlier issue report.
3. I am using phonegap version 3.7 (pretty old, if this does not occur in new ones, probably nothing much to worry about)

Thanks again for your great plugin, makes life lot easier !!!

**Comment by EddyVerbruggen** [comment]
Yeah you need to use a Cordova version which uses Gradle to build the project, so please update your Cordova version on pgb. Hope that helps!
