### ISSUE TITLE
When authenticating google+ doesn't redirect back to app but stays in google+

### ISSUE THREAD

**Issue by tfmalt** [EddyVerbruggen/cordova-plugin-googleplus#15]
Use case is as follows:
1. login in triggered as expected from app.
2. Google+ opens and tells me to pick a google id.
3. The consent screen in shown correctly. I press OK
4. phone stays in google+, no callback is sent to app.

Is this a know issue? What can I do to help track down the cause?

**Comment by tallcoder** [comment]
This was happening to me after updating cordova-ios to 5.0. Once I realized that's what changed and downgraded it back to 4.5.4, google login started working again.

Hopefully, this issue gets fixed because now I cannot move to cordova-ios 5.0 yet.

**Comment by sofienbenab** [comment]
Dear all, I'm facing the same issue with ionic 3 (ios cordova version 4.5.5).

Mister @calvingferrando, can you please precise how to add the bundle id to the URL types scheme in the *-info.plist ?
what are the values of these fields please if my bundle id is com.app

<img width="815" alt="Capture d’écran 2019-05-08 à 21 20 59" src="https://user-images.githubusercontent.com/50423399/57402317-56d1ad00-71d7-11e9-832e-cdbb9ea78051.png">

and if add a CFBundleURLTypes tag to my *-info.plist it looks like this but I still don't get how to put the information : 

<img width="624" alt="Capture d’écran 2019-05-08 à 21 24 05" src="https://user-images.githubusercontent.com/50423399/57402436-a2845680-71d7-11e9-9a61-6346f7fb6ee8.png">

Many thanks in advance for your help :)
