### ISSUE TITLE
IOS Build fails with compilation errors

### ISSUE THREAD

**Issue by SeaEagleEye** [EddyVerbruggen/cordova-plugin-googleplus#150]
I'm getting the following error when the build fails in IOS

Users/eswari/Desktop/Google_auth/blank/platforms/ios/blank/Plugins/cordova-plugin-googleplus/GooglePlus.m:1:9: fatal error: 'GoogleOpenSource/GoogleOpenSource.h' file not found
"#import  GoogleOpenSource/GoogleOpenSource.h"

Error code 65 for command: xcodebuild with args: -xcconfig,/Users/winbold/Desktop/Google_auth/blank/platforms/ios/cordova/build-debug.xcconfig,-project,blank.xcodeproj,ARCHS=i386,-target,blank,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/winbold/Desktop/Google_auth/blank/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/winbold/Desktop/Google_auth/blank/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/winbold/Desktop/Google_auth/blank/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/winbold/Desktop/Google_auth/blank/platforms/ios/cordova/build: Command failed with exit code 2

**Comment by balajivinnakota** [comment]
I'm getting the same problem with the IOS build...

**Comment by Mojo90** [comment]
Same for me.

Went to: https://developers.google.com/+/mobile/ios/getting-started
Downloaded Google+ iOS SDK and added ```GoogleOpenSource.framework```manually. Now I was able to build. Not sure if this has to be done or if in GooglePlus.m has to be fixed something

**Comment by taylorlc70** [comment]
+1 for this issue. Our cordova iOS build has been working fine for a long time, but now this. Everything I've searched suggests manual changes in xcode. Is there a better way?

**Comment by EddyVerbruggen** [comment]
Hmm, that import should no longer be there in the first place, can you please try version 4.0.5?

**Comment by taylorlc70** [comment]
Fixed! Thank you, sir.

**Comment by Mojo90** [comment]
Perfect does work for me, thx. Didn't see that there was sth commented out thus workaround with old Framework...

**Comment by YaroslavG** [comment]
Hi guys,
I use version": "4.0.8" but I have the same problem with the IOS build...
Can you help me?

**Comment by sammuggPS** [comment]
@YaroslavG,

*This is a closed issue, so if the problem persists after trying my suggestion below, please open a* ***new*** *issue and respond there.*

I just merged a significant PR the other day that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out.

Could you please try removing and readding the plugin to your project? When you re-add the plugin, please install from github, not from the plugin registry. I.e.,

```bash
$> cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=<your reversed client id>
$> cordova prepare
```

Happy Coding,
~Sam

**Comment by marimuthudm** [comment]
Hi,
I have faced the same issue while building for IOS and Ionic 1.

```
In file included from /ionic/platforms/ios/Kitescafe/Plugins/cordova-plugin-googleplus/GooglePlus.m:3:
/ionic/platforms/ios/Kitescafe/Plugins/cordova-plugin-googleplus/GooglePlus.h:2:9: fatal error: 'GoogleSignIn/GoogleSignIn.h' file not found
#import <GoogleSignIn/GoogleSignIn.h>
```
Any solutions ?

**Comment by marimuthudm** [comment]
Try 

`cordova plugin add cordova-plugin-googleplus@4.0.5 --save --variable REVERSED_CLIENT_ID=<Your Id>`

Version 4.0.5 working fine
