### ISSUE TITLE
README out of date for Google+ API setup (Android)

### ISSUE THREAD

**Issue by jacqueskang** [EddyVerbruggen/cordova-plugin-googleplus#151]
Currently it says "To configure Android, follow Step 1 of <a href="https://developers.google.com/+/quickstart/android">this guide</a>"
But apprenante Google has updated that guide and "step 1" is no longer relevant.
I don't know what exactly to be done ex: Do we need to copy google-services.json somewhere and do we need to modify strings.xml file?

Please consider updating the README.md

**Comment by azotos** [comment]
I had the same problem and used this page https://web.archive.org/web/20150317133043/https://developers.google.com/+/quickstart/android

It is an older snapshot of the page (from March) and the one they refer to in the README. I think it will help you until they fix it.

**Comment by jacqueskang** [comment]
@azotos I made it work already but thank you anyway! It could have saved me a lot of time if I knew that archive link!

**Comment by jacqueskang** [comment]
README updated.
