### ISSUE TITLE
Error on Phonegap Build cli-5.2.0 

### ISSUE THREAD

**Issue by zphingphong** [EddyVerbruggen/cordova-plugin-googleplus#156]
Version 4.0.6 doesn't seem to be working with Phonegap Build cli-5.2.0. Error out on Android compilation.

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexRelease'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/android-sdk/build-tools/23.0.1/dx --dex --output /project/build/intermediates/dex/release --input-list=/project/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)

Any idea?

**Comment by zphingphong** [comment]
@EddyVerbruggen Hey Eddy, is it possible to upgrade the plugin to support Phonegap Build cli-5.2.0 ?

**Comment by EddyVerbruggen** [comment]
@zphingphong Hey, it should work as I just built an app with [this line in config.xml](https://github.com/EddyVerbruggen/X-Services-PhoneGap-Build-Plugins-Demo/blob/master/config.xml#L30). Do you build with gradle as well? Perhaps there is another plugin in your `config.xml` interfering with this one.

**Comment by zphingphong** [comment]
@EddyVerbruggen  Would something like this work? Or it's wrong because I point to npm?

<gap:plugin name="cordova-plugin-googleplus" source="npm">
        <param name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.47378534221-qv6dsrsg3dqus6i9alrqcn4bqu02349k" />
    </gap:plugin>

**Comment by EddyVerbruggen** [comment]
@zphingphong [check here](https://github.com/EddyVerbruggen/X-Services-PhoneGap-Build-Plugins-Demo/blob/master/config.xml#L30-L32), build fine on build.phonegap.com.

**Comment by VitaliiBlagodir** [comment]
Hi @EddyVerbruggen !

When I build from your repo https://github.com/EddyVerbruggen/X-Services-PhoneGap-Build-Plugins-Demo.git
Phonegap Build throws error for iOS:
Error - One of your plugins requires a parameter: REVERSED_CLIENT_ID - You can fix this here

**Comment by EddyVerbruggen** [comment]
Hey @VitaliiBlagodir,

I didn't test iOS myself, but that's strange because the param [is part of the config.xml](https://github.com/EddyVerbruggen/X-Services-PhoneGap-Build-Plugins-Demo/blob/master/config.xml#L31).. perhaps that's an issue with phonegap build. Maybe it works ok when we use `<gap:plugin` instead of `<plugin` for this one..

**Comment by VitaliiBlagodir** [comment]
@EddyVerbruggen , you are right. On Phonegap Build build for iOS going well if old format used:

``````````
<gap:plugin name="cordova-plugin-googleplus" source="npm">
  <param name="REVERSED_CLIENT_ID" value="myreversedclientid" />
</gap:plugin>
``````````````````
Also grandle need to be used. @zphingphong try to add following line
``````````
<preference name="android-build-tool" value="gradle" />

**Comment by EddyVerbruggen** [comment]
That's correct, you need gradle. They had that as the default but rolled that change back because of a few issues, so you need to set it explicitly.

**Comment by zphingphong** [comment]
@EddyVerbruggen it built now, but it doesn't let me login in iOS. Is there anything else I should change? Works on Android though.

**Comment by hoojianliang** [comment]
HI, I already added <preference name="android-build-tool" value="gradle" /> and 
<gap:plugin name="cordova-plugin-googleplus" source="npm">
  <param name="REVERSED_CLIENT_ID" value="979226798515-avj13e8frdgdn9ooh7m26dbcpvb3t991.apps.googleusercontent.com" />
</gap:plugin>
to my config.xml. Why it still failed to build. Please help me :)

**Comment by hoojianliang** [comment]
Hi, I already added ```<preference name="android-build-tool" value="gradle" />``` and 
```<gap:plugin name="cordova-plugin-googleplus" source="npm">
  <param name="REVERSED_CLIENT_ID" value="979226798515-avj13e8frdgdn9ooh7m26dbcpvb3t991.apps.googleusercontent.com" />
</gap:plugin>``` to my config.xml file. But it is still failed. Please help me :)

**Comment by zphingphong** [comment]
@hoojianliang It might be something else in your config file. Here is mine, it built, check it out. http://pastebin.com/kNwrQcky

**Comment by hoojianliang** [comment]
@zphingphong hi, how you build the file? through build.phonegap.com?

**Comment by zphingphong** [comment]
@hoojianliang yea

**Comment by hoojianliang** [comment]
@zphingphong hmm, I tried to change my config.xml to your's, but I am still failed. Anyway, thanks for your replies and helps.

**Comment by bilalhassan235** [comment]
@hoojianliang you haven't reversed the client id . try reversing that string if it works

**Comment by hoojianliang** [comment]
i found what my problem already, is the com.phonegap.plugins.facebookconnect plugin crash with cordova-plugin-googleplus. Thanks to you guys, by the way, what the plugin for facebook connect you guys using?

**Comment by ashishsajwan** [comment]
@EddyVerbruggen @VitaliiBlagodir @zphingphong 
any clear fix for this issue ??
How do i get things going ??

**Comment by teknologist** [comment]
Any solution to this ?
