### ISSUE TITLE
What userinfo do you get on successful android login?

### ISSUE THREAD

**Issue by zigzag-way** [EddyVerbruggen/cordova-plugin-googleplus#159]
As for me I got this:
 {"imageUrl":"profile image url",
"email":"email@gmail.com",
"userId":"103473911172360433971",
"familyName":"LastName",
"gender":"male",
"givenName":"FirstName",
"displayName":"First Last Name",
"ageRangeMin":21} 

But where are the tokens?!

**Comment by nermolov** [comment]
Bumping, trying to use obj.idToken and obj.oauth.Token returns and "undefined"

**Comment by zigzag-way** [comment]
I use this code
                                    $cordovaGooglePlus.login(
                                        {},
                                        function (obj) {
                                            console.info('Login: ' + JSON.stringify(obj));
                                            window.localStorage.setItem('gp_email', obj.email);
                                            window.localStorage.setItem('gp_uid', obj.userId);
                                        },
                                        function (msg) {
                                            console.error("g+ login error");
                                        }
                                    );

It doesnt return anything except the array that I `ve posted

**Comment by EddyVerbruggen** [comment]
@zigzag-way Does my comment in #162 help?

**Comment by zigzag-way** [comment]
Oh, it helped, but why should I use this option?

**Comment by EddyVerbruggen** [comment]
Because it's an extra server roundtrip which is a total waste (performance wise mostly) if you don't need it.
