### ISSUE TITLE
Unable to get obj.idToken

### ISSUE THREAD

**Issue by nermolov** [EddyVerbruggen/cordova-plugin-googleplus#162]
As stated, I am unable to get obj.idToken and obj.oauthToken. Instead of actually getting the tokens, I get an "undefined" 

I am successfully able to get all user info, except for the tokens, which are crucial in my implementation.

**Comment by EddyVerbruggen** [comment]
Is this on iOS, Android, or both?

**Comment by EddyVerbruggen** [comment]
For Android, did you pass in `offline: true` (see the readme) to get the `oauthToken` param in the response?

```js
        window.plugins.googleplus.login(
            {
              offline: true
            }, ..
        )
```

**Comment by pranaydutta89** [comment]
same here :+1:  are we missing some configuration

**Comment by pranaydutta89** [comment]
on doing offline:true i am getting "Failed to retrieve token Unknown" error

**Comment by nermolov** [comment]
OK so when setting offline: true I now get the oauthToken. But I am still not able to get the obj.idToken are there any other settings that I have to set?

**Comment by pranaydutta89** [comment]
i am getting  "Failed to retrieve token Unknown" error, even when testing in different devices

**Comment by nermolov** [comment]
Are you using android or iOS?

**Comment by nermolov** [comment]
Just as a clarification, I am still unable to get obj.idToken, I just get an undefined. (android)

**Comment by pranaydutta89** [comment]
well i had fixed issue,
here is few mistakes i was doing

1) wrong SHA1 footprint in console.google (debug,keystore should also be present there)
2) in scopes i was writing wrong scopes

**Comment by nermolov** [comment]
Are you able to get obj.idToken? If so, what scopes/settings are you using?

**Comment by pranaydutta89** [comment]
scopes:'email profile' and i needed the oauth token so i got that one

**Comment by nermolov** [comment]
Still unable to get obj.idToken, getting an undefined, am I doing something wrong?

**Comment by nermolov** [comment]
@EddyVerbruggen Am I missing any scopes to get obj.idToken? It is just returning undefined.

**Comment by nermolov** [comment]
I have solved the problem myself, in order to receive obj.idToken, you need to specify webApiKey (even on android!) and it is also not an api key, it is instead the client id of your web application. After specifying that, you can get obj.idToken
