### ISSUE TITLE
Reverse Client ID

### ISSUE THREAD

**Issue by alien3d** [EddyVerbruggen/cordova-plugin-googleplus#170]
Are reverse client ID is the Google Api Key ? 
something like this from google developer console 
Android key for com.sumaxia.alien3d (auto created by Google Service) ?

**Comment by sammuggPS** [comment]
Hey @alien3d,

I just merged a significant PR the other day that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out.

In regard to your question, the Reversed Client Id is an item needed for using the plugin with iOS. It is what Google uses to identify an application to the project on the Developers Console.

Let me know if you have any questions!

Happy Coding,
~Sam
P.S. If your issue gets resolved, please close it!

**Comment by alien3d** [comment]
thanks for update.. sorry kinda late a bit respond..  :) ..

**Comment by SelfnessAid** [comment]
Hi, everyone
I am not sure what should I use as reverse client id in my app
when I tried to implement this command, 

> `$ ionic plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid`

here, what does it mean - myreversedclientid ?

![screen shot 2016-11-13 at 2 44 31 am](https://cloud.githubusercontent.com/assets/20356023/20240113/2ec0705a-a94b-11e6-991a-d907d4dda948.png)

thanks for any assistance

**Comment by epicfaace** [comment]
@SelfnessAid , Looks like you should try that command with sudo.
