### ISSUE TITLE
The OAuth token does not give access to email for some users in the server side

### ISSUE THREAD

**Issue by bsautel** [EddyVerbruggen/cordova-plugin-googleplus#173]
Hi.

I use the OAuth token to retrieve user profiles from the server side. For about half of users, the `https://www.googleapis.com/oauth2/v2/userinfo` endpoint does not provide me the email address. I get exactly the same behavior with the `https://www.googleapis.com/plus/v1/people/me` endpoint. And yet these two endpoints give me many other attributes such as name, id, gender, locale...

I do not know Google + very well, but I assume users can choose whether they want their email address to be part of their Google + profile or not. If this assumption is right, it could explain why I do not get the email address for some users.

I tried to change the scopes in the login method parameter to add the `plus.profile.emails.read` one described [here](https://developers.google.com/+/web/api/rest/oauth) but it did not change anything. I also tried many other scope names related to email but none of them could get the profile endpoint to return users email address.

I took a look at the [Google Sign-In for Android library documentation](https://developers.google.com/identity/sign-in/android/people). They explain that some additional configuration has to be done to retrieve users' email addresses. In [this page](https://developers.google.com/identity/sign-in/android/sign-in), they talk about using the Google Sign-In API.
In the [GooglePlus.java](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/src/android/GooglePlus.java#L168) file, I could see that only the Google Plus API Client is added in the Google API Client.

I assume all the scopes defined in the login method that are not related to the Google Plus API are simply ignored.

Do you think it would make sense to add the Google Sign-In API client? Or at least a configuration entry to choose whether to use Google Plus or Google Sign-In?

Thanks!

**Comment by jorgejeferson** [comment]
Had the same problem, my solution was:
`Google API` >> `G+ API` >> `Enable`

**Comment by bsautel** [comment]
@jorgejeferson  thanks for your reply.

Are you talking about the Google Developer Console configuration?

**Comment by jorgejeferson** [comment]
Yes.

**Comment by bsautel** [comment]
It sounds like it is already the case for me.

**Comment by sebastialonso** [comment]
Same here, @jorgejeferson solution is not really related with the issue. I'm having the same issues, and the API has been enabled from the start.

**Comment by sammuggPS** [comment]
Hey @bsautel and @sebastialonso,

I merged a significant PR the other day that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out. To install it, use the second (GitHub URL) method found in the [README](https://github.com/EddyVerbruggen/cordova-plugin-googleplus#4-installation-phonegap-cli--cordova-cli).

In the updated documentation, you'll notice that the `oAuthToken` is now called the `serverAuthCode` because that's what Google calls it. Profile and Email are getting requested no matter what, so I hope you don't run into this issue again. Do make sure that your project is set up properly on the Dev Console.

Let me know if you have any questions!

Happy Coding,
~Sam
P.S. If your issue gets resolved, please close it!

**Comment by bsautel** [comment]
Hi @sammuggPS.

I just come to test this fix with a Google account for which I could not retrieve the email field with the former version. I confirm that **it works**!

It remains me to change the server-side token validation mechanism since it is currently working with access tokens and with this new version I have to call an API to convert this authentication code to an access token.

Will this fix be integrated in the next release?

Thanks a lot for your work!

**Comment by sammuggPS** [comment]
@bsautel, That's great to hear!

It should be in the next release, yes. We wanted to make sure that things were relatively smooth before pushing this up to npm.

Thanks for giving it a go!

**Comment by bsautel** [comment]
OK for the next release.

I forgot to mention that I tested this fix only on Android.

Thanks.
