### ISSUE TITLE
Work marvelous pretty odd ?

### ISSUE THREAD

**Issue by alien3d** [EddyVerbruggen/cordova-plugin-googleplus#174]
I follow the instruction at the main page.
The only instruction i don't follow and error on part to set reverse id. I try to put in config. xml  but it said error.. 
Try my luck on compile with Visual Studio Apache Cordova Tools and test on phone huawei y5c.
1. It WORK... ? 
2. Second time click at the link  it will output no error just refresh.. but still okay to me..third time. Error.. no warry i will add some error handling if login no need for clickin same thing.
3. Nice small popup add account.. ..  
4. Conclusion, i try few cordova  plugin and it make page redirect / browser..  Quite annoy dou.. 
5. tq..

**Comment by EddyVerbruggen** [comment]
I'm sorry but I don't get it.. perhaps someone else?

**Comment by alien3d** [comment]
The main question was ?

Are reverse client id mandatory in android ? 
From the first page , you said it required . But when i tested it work without the reverse client ID

Are second time click login will error ?

Yes, it error but it can avoid if you set some localstorage saying you have registered.

Why this plugin compare to other OAUTH2 cordova

The reason other plugin using  loadstart on window.open but it only work on same domain. If other domain like facebook or google it will open new browser and after complete it wouldn't close as loadstop event.

Anyway Thank you .. save my time testing code. :)
