### ISSUE TITLE
not building with cordova-ios 4.0.1

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-googleplus#175]
all detail right here
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/27
this is why "cordova-plugin-googleplus" also have this error too

developer should be follow this in iOS@4.0.1
http://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
just want to ask...
any update progress ?

**Comment by EddyVerbruggen** [comment]
Hey, which issue do you mean? That [error of the diagnostic plugin](https://github.com/dpa99c/cordova-diagnostic-plugin/issues/27) is about `stringByEvaluatingJavaScriptFromString` which this plugin doesn't use.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
please forgive me
this is another problem when using "phonegap-plugin-push" + "cordova-plugin-googleplus"
all detail under here
https://github.com/phonegap/phonegap-plugin-push/issues/449

if you have time
you can see @dragermrb and my conversation
very thankful
