### ISSUE TITLE
Unable to build for Android in Adobe's build service

### ISSUE THREAD

**Issue by Dineshrajaa** [EddyVerbruggen/cordova-plugin-googleplus#176]
Hi all I just created a sample app and included this plugin but I couldn't get a successful build for android
I am getting this Error

Error - One of your plugins required the gradle android build tool to build - You can fix this here

Here is the log of the failed build

Build Date: 2016-01-19 17:02:51 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
Fetching plugin "cordova-plugin-googleplus@~4.0.6" via npm
Installing "cordova-plugin-googleplus" for android
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^

Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle.
    at /project/cordova/lib/build.js:183:27
    at _fulfilled (/project/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:760:13)
    at /project/cordova/node_modules/q/q.js:574:44
    at flush (/project/cordova/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by EddyVerbruggen** [comment]
So did you try switching to gradle? You can set this in config.xml, look it up.

**Comment by Dineshrajaa** [comment]
Thanks it worked :)
