### ISSUE TITLE
Inconsistent API / Documentation needs clarifications.

### ISSUE THREAD

**Issue by pmwisdom** [EddyVerbruggen/cordova-plugin-googleplus#178]
So this is for people that need the ability to refresh oAuthTokens for any google apis. If you want to retrieve a token to get a correct accessToken / refreshToken combination you need to supply a client Id.

For this plugin on android that is added via the androidApiKey, but for iOS its the webApiKey. So first question, why are these different in the first place? They are the same exact key, which is your browser oAuth client Id (which also needs to be clarified). 

So next : lets say you do not add either of these keys (androidApiKey or webApiKey) . The plugin will hand you back an accessToken and refreshToken. You won't be able actually do any token refreshing because the client Id that the plugin uses without the webApiKey / androidApiKey is the platform specific (android / ios) key. It will error out when refreshing a token saying that you have provided an unauthorized client. This is more of a documentation issue, I had to actually look at the source code to understand what was going on.

This is very, very confusing for someone trying to use both android and ios. Its only further complicated by the fact that the api's are not consistent. It isn't made any better by the fact that google makes you supply 3 different keys, so maybe a little documentation on all the different keys and what they do would be really, really helpful.

**Comment by tomikapc** [comment]
**# Indeed!**

**Comment by sammuggPS** [comment]
@pmwisdom and @tomikapc,

I just merged some changes today, including some updated documentation. Let me know if there's anything you think needs additional clarification.
