### ISSUE TITLE
No keytool execution instructions

### ISSUE THREAD

**Issue by virtser** [EddyVerbruggen/cordova-plugin-googleplus#184]
You write in README: "Make sure you execute the keytool steps as well or authentication will fail."

But there is no instructions in the link on how to execute it.

**Comment by EddyVerbruggen** [comment]
So that page changed, awesome. Can you send a PR for the readme?

**Comment by virtser** [comment]
If I knew what need to be done, I would. :)
Now I'm stuck on how to install it...

**Comment by corinzio** [comment]
Hi @virtser 
It's a phase inside the "Get a configuration file" step.
It is requested that you define the sha1 key your app is signed by.
if you like me are using the debug key you cand follow this [guide](https://developers.google.com/drive/android/auth) written for the drive api to obtain the sha1 key from the debug keystore.

hope it helps

**Comment by virtser** [comment]
Thanks @corinzio !
