### ISSUE TITLE
Android version 6.0 now asking for 'Contacts permission'

### ISSUE THREAD

**Issue by schaukoski** [EddyVerbruggen/cordova-plugin-googleplus#190]
Hi!

Im using this plugin for connect to g+ and login into my app. Everything was working like expected.

Today i updated my cellphone to android 6.0 marshmallow and when i try to connect like i did before, it asks for "Contacts permission" but i just need the basic profile info.; this is my code with the scopes i tried so far:
```javascript
window.plugins.googleplus.login(
    {
        'scopes': 'https://www.googleapis.com/auth/plus.login',
        //'scopes': 'https://www.googleapis.com/auth/plus.profile.emails.read',
        //'scopes': 'https://www.googleapis.com/auth/userinfo.email',
        'offline': true, // optional, used for Android only - if set to true the plugin will also return the OAuth access token ('oauthToken' param), that can be used to sign in to some third party services that don't accept a Cross-client identity token (ex. Firebase)
        'webApiKey': appConfig.googleWebApiKey,
        // there is no API key for Android; you app is wired to the Google+ API by listing your package name 
        // in the google dev console and signing your apk (which you have done in chapter 4)
    },
    function (user_data) {
        $scope.externalLogin(user_data.oauthToken, 2);
    },
    function (msg) {
        $ionicLoading.hide();
        $scope.showAlert('Não foi possível conectar com o gmail');
    }
);
```

Thank you, sorry for bad english!

** How do i post CODE with correct indenting? Thanks!

**Comment by Nadejde** [comment]
I get the same problem. But only when I actually send a first parameter to the login method. If I live that empty no contacts access is requested.

**Comment by sammuggPS** [comment]
Hey @schaukoski and @Nadejde,

Thanks for bringing this up.

I just merged a significant update yesterday that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out.

On the note of scopes, different scopes will request different types of account access. The Plus.Login scope happens to request access to the users google contacts.

With the updates I pushed yesterday, the default scopes are `profile` and `email`. These will return the user's display name, email address, and profile picture, the items Google considers to be "basic profile info." If you need any more information than that, you would need to pass in `"scopes": "<list of scopes>"`.

However, be aware that if you pass in a list of scopes the plugin will **only** request the scopes in that space separated list. For example, to get the basic profile *and* plus.login data scopes should be formatted as follows:

```
"scopes": "profile email https://www.googleapis.com/auth/plus.login"
```

To get the latest version of the plugin, use:

```bash
$> cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=<reversed-client-id>
$> cordova prepare
```

Let me know if you have any questions!

Happy Coding!
~Sam

P.S. @schaukoski, I edited your comment so you could see how to write code with proper indenting and highlighting in markdown.

**Comment by Beirdo** [comment]
Very very good.  I will try your new support tonight on my project as well.  I've been fighting for days trying to get this working right, so I'm super-pleased to see that you're switching to Google Sign-In :)

**Comment by schaukoski** [comment]
Thank you so much, i will update and try it!

Thanks!

**Comment by Nadejde** [comment]
Hey @sammuggPS,

Thank you for the comment! Just tried it out and works great. See exact code below.

A couple of things to mention:
- googleClientId needs to be of type "Web appliaction" now. I was using one of type Android and that is failing with the new model with error 12501. Just switching to the web client id fixed this. See here: http://stackoverflow.com/questions/33583326/new-google-sign-in-android
- You no longer get an access token directly as it was before. You now get the server authentication code. You then need to make a separate call to get an access token (if you need one) using your client id, secret, authorization token and more. See here: https://developers.google.com/identity/sign-in/android/offline-access

I hope this makes sense and I'm not totally off as I'm new to this.

```
window.plugins.googleplus.login( 
        {
          scopes: 'profile email',
          webClientId: keys.googleClientId,
          offline: true
        },
        function (userData) {

          _googleAuth.serverAuthCode = userData.serverAuthCode;
          _googleAuth.name = userData.displayName;
          _googleAuth.email = userData.email;

        },
        function (error) {

      });
```

**Comment by sammuggPS** [comment]
Hey @Nadejde,

Thanks for trying out the update! I’m glad you got it working.

You should know that i pushed a minor update this morning that cleaned up GooglePlus.java a bit, but nothing that would really affect your development.

- Google Client ID: You are correct! I made note of this in the Usage -> Login section of the README. Our documentation had an overhaul with this shift to Google Sign-In, so be sure to read up and note any other caveats.
- Access Token: Correct again! 10 pts to Gryffindor. The reason for this is because Google Sign-In is a relationship between the **native** side of the app and **Google**. Google *really* wants developers to use the Native SDKs to access APIs from the client side of a mobile app. This poses a problem for hybrid development because the hybrid application does not manage the user’s connection to Google. **Therefore**, best practice for using the REST APIs from a hybrid application would be to use the access and refresh tokens received through this `serverAuthCode`.

Hope that all makes sense! Thanks again for trying out the update.

Happy Coding!
~Sam

**Comment by schaukoski** [comment]
@Nadejde Hi!

I tried just like you did, with scopes: 'profile email' but it still asks for Contacts Permission.

Any ideas what i could be doing wrong?

Thanks!

**Comment by Nadejde** [comment]
@schaukoski Hi,

Have you installed the plugin from the git repository like this?
```
$> cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=<reversed-client-id>
```
It is important. If you install using cordova plugin add cordova-plugin-googleplus you get the latest release and that's actually behind the git repo. Just remove the existing plugin and add it again.

Hope this helps.

**Comment by sammuggPS** [comment]
@Nadejde,
So, the latest PR worked for you?

**Comment by Nadejde** [comment]
@sammuggPS seems so yes.

**Comment by schaukoski** [comment]
Hello @Nadejde , i think last time i executed the command cordova plugin add without remove it first. Im now looking for get the oauthtoken, as you said, the token doesnt come anymore in the first call.

In my process, i used to get the token from gmail, send it to my API, and my API verify the token and get the information i need server-to-server.

Thank you!

**Comment by sammuggPS** [comment]
@schaukoski,

As I said earlier in this thread, the usage of this plugin has changed significantly from the last version. Please read our documentation and understand what changed and what is now being returned.

~Sam

**Comment by schaukoski** [comment]
Hello @sammuggPS ,

I think im passing the wrong webClientId. Because im passing the webClientId and Offline:true, but i get in respose just, email, userid, displayName. In the google developers console, im using the "Web client (auto generated by google)" is that the one?

Thanks!

**Comment by sammuggPS** [comment]
@schaukoski,

The one you want will be under the OAuth 2.0 Client Ids section and of type Web Application. If that's what you're using, then that should be correct. Make sure it's the client id and not the client secret. Those are different.

**Comment by schaukoski** [comment]
Yes, its exactly this one im using. 

Maybe something wrong with my Reversed_client_Id ? I will try to reinstall the plugin, and verify my Android Signing Certificate SHA-1.

**Comment by sammuggPS** [comment]
Reversed_client_id is only needed for iOS. It will not affect your android build.

**Comment by Nadejde** [comment]
@schaukoski 
Hi, I was using the same model you described. I've had to make the following changes:
- Make sure to save ```serverAuthCode``` and that you use the web client id not the android one:
```
window.plugins.googleplus.login( 
        {
          scopes: 'profile email',
          webClientId: keys.googleClientId,
          offline: true
        },
        function (userData) {

          _googleAuth.serverAuthCode = userData.serverAuthCode;
          _googleAuth.name = userData.displayName;
          _googleAuth.email = userData.email;
  
          deferred.resolve(_googleAuth);
        },
```

- after this you need to make another call to google to get the oauth token:
https://developers.google.com/identity/sign-in/android/offline-access
You will need to pas in api key secret etc on this call. Short story is do a POST request to this url: https://www.googleapis.com/oauth2/v4/token. Pass in serverAuthCode , client_id, client_secret, grant_type, redirect_url(just one of your allowed urls for your app in the google dev console)

- I implemented the step above on the server myself. Passed serverAuthCode to the backend. After that I get the oauth token direct in the backend (no need to check it's authenticity again, but you can anyway).

Let me know if you need more guidance with this. I'm glad to help.

**Comment by schaukoski** [comment]
@Nadejde  Thanks for the help!

Im using this exactly code, using the web client id just like sammuggPS said. The response "userData" i dont have this property "serverAuthCode". My object just have email, userId and displayName.

**Comment by Nadejde** [comment]
@schaukoski Can you paste your code in here please for us to have a look at? Thank you

**Comment by schaukoski** [comment]
```
	    $scope.googlePlusSignIn = function () {
	        try {
	            $ionicLoading.show({
	                template: '<div><ion-spinner icon="android"></ion-spinner></div><div>Aguarde um momento...</div>',
	                noBackdrop: false
	            });

	            window.plugins.googleplus.login(
                {
                    'scopes': 'profile email',
                    //'scopes': 'https://www.googleapis.com/auth/plus.login',
                    //'scopes': 'https://www.googleapis.com/auth/plus.profile.emails.read',
                    //'scopes': 'https://www.googleapis.com/auth/userinfo.email',
                    'offline': true, // optional, used for Android only - if set to true the plugin will also return the OAuth access token ('oauthToken' param), that can be used to sign in to some third party services that don't accept a Cross-client identity token (ex. Firebase)
                    'webClientId': appConfig.googleWebApiKey,
                    // there is no API key for Android; you app is wired to the Google+ API by listing your package name in the google dev console and signing your apk (which you have done in chapter 4)
                },
                  function (user_data) {
                      alert(JSON.stringify(user_data));
                      alert(user_data.serverAuthCode);
                      $scope.externalLogin(user_data.serverAuthCode, 2);
                  },
                  function (msg) {
                      $ionicLoading.hide();
                      $scope.showAlert(msg);
                      $scope.showAlert('Não foi possível conectar com o gmail');
                  }
                );
	        } catch (e) {
	            $scope.showAlert(e);
	        }

	    }
```

**Comment by sammuggPS** [comment]
@schaukoski,

`appConfig.googleWebApiKey` --> this needs to be your Web Client Id. NOT an Api Key.

Everything else looks fine.

**Comment by schaukoski** [comment]
@sammuggPS  thanks for the tip, its just an old variable, but it is the webclientid that im using.

**Comment by Nadejde** [comment]
@schaukoski  Last think I can think of for you to try is to remove the plugin. Remove android platform from ionic. add the plug-in back from git repository and then add the android platform black. 

What version of cordova and Ionic are you on? (don't think this would make any difference but nothing else I can think of)

**Comment by shash5** [comment]
even i'am not able to get serverAuthCode in android...everything else including oauthToken, idToken etc get from googleplus plugin...since from last 2 days working on the same...plz help...

**Comment by shash5** [comment]
@schaukoski even i'am not able to get serverAuthCode in android...everything else including oauthToken, idToken etc get from googleplus plugin...since from last 2 days working on the same..

**Comment by shash5** [comment]
I'am using ionic 1.7.14 and cordova 6.0.0

**Comment by sammuggPS** [comment]
@shash5,

I merged a significant PR last week that updated the Android side to use Google Sign-In. You should install the latest plugin from GitHub, _read the updated documentation_, then give it another go.

P.S. You will likely need to remove the plugin first and then reinstall. Otherwise, you may run into issues in the build process.

~Sam

**Comment by shash5** [comment]
@schaukoski thanks for the reply..can you plz put the latest git plugins url....

**Comment by sammuggPS** [comment]
@schaukoski, it's in the documentation!

Please, please, please read our documentation. Things have changed from the last version.

**Comment by shash5** [comment]
Though I'am the beginner to this..I'am very very sorry for silly questions....to get latest cordova googleplus plugin in android, i usually do this...cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid...for reverseclientid i usually put my android client id....I think it is not the proper way...i guess it is for ios...

**Comment by sammuggPS** [comment]
@shash5,

Your REVERSED_CLIENT_ID is a property that can be found in the iOS client id configuration on the developer's console. It is also called the "iOS Url Scheme".

That is the correct way to get the latest plugin, however, I recommend removing the plugin before reinstalling. That way you don't run into any potential issues of the plugin not updating in the platform directories.

P.S. They're not silly questions, it's just already answered in the documentation!

**Comment by shash5** [comment]
@schaukoski thank you so much...I'am able to get serverAuthCode...

**Comment by schaukoski** [comment]
I think you guys are confusing the nicknames, heheheh!

**Comment by shash5** [comment]
hai sorry man..@sammuggPS thank you very much...

**Comment by sammuggPS** [comment]
@schaukoski, did you try @Nadejde's suggestion of removing the plugin then reinstalling?

If you are using the correct clientId and setting offline to true, you should be getting back the serverAuthCode and an idToken.

**Comment by schaukoski** [comment]
@Nadejde  @sammuggPS ,

I did what u said @Nadejde , removed the android platform, removed the plugin and installed again. It worked, now im able to get the idToken and serverAuthCode!

Now im having trouble to use the https://www.googleapis.com/plus/v1/people/me?access_token=<<serverAuthCode>>&key=<<apiKey>> but this is another problem!

Thanks guys!

**Comment by sammuggPS** [comment]
@schaukoski, That's awesome! Thanks for letting us know. Good luck with the rest!

**Comment by Nadejde** [comment]
@schaukoski  Great news! Good luck!

**Comment by schaukoski** [comment]
@Nadejde  could you make a test for me please?

Could you try to get the user information using your serverAuthCode? like this: https://www.googleapis.com/plus/v1/people/me?access_token=serverAuthCode

i tried so many times, trying with all scopes, but i always get
 "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."

I Tried passing the api key too, but didnt work.

Thank you, sorry for bothering!

**Comment by sammuggPS** [comment]
@schaukoski, I don't think that's the URL you want to use to exchange the auth code.

Please reference [this Google guide](https://developers.google.com/identity/protocols/OAuth2WebServer#handlingresponse) to get an example of the exchange.

"To exchange an authorization code for an access token, use the https://www.googleapis.com/oauth2/v4/token endpoint..."

**Comment by schaukoski** [comment]
@sammuggPS  i was able to use like this before the updateof the plugin. Google has changed the serverAuthCode we receive in the plugin ?

**Comment by sammuggPS** [comment]
@schaukoski,

Despite the name of this plugin, we're no longer using the Google+. So plus-based APIs shouldn't be used in conjunction with these APIs unless the proper scopes are supplied and you have the proper APIs enabled. See [this Google+ Article](https://developers.google.com/+/web/signin/#set_up_google_sign-in_for_google) to learn more.

In general, whenever you are developing an application that relies on some third-party tool, such as Google, you should reference the documentation that applies to the details of your project.

In our case, the details of the plugin are that we use the Google Sign-In framework. Therefore, any documentation we reference should start with Google Sign-In. Any URLs we use to exchange codes or tokens should be sourced from and verified through Google Sign-In.

**Comment by schaukoski** [comment]
Ohh! Allright! I will read the documentation, Thanks!!!

**Comment by Nadejde** [comment]
@schaukoski  Hi. Have you used postman before? This is an example of how you use the endpoint @sammuggPS  mentioned:

![image](https://cloud.githubusercontent.com/assets/11600081/14355460/e3db83fa-fcd8-11e5-9c86-219caa1ea861.png)

The response you will get will look like this:
```
{
  "access_token": "oauth token here"
}
```
Not sure what you use on the backend. I use .net and this is how the code looks like, perhaps it helps:

```
string accessTokenEndPoint = string.Format("https://www.googleapis.com/oauth2/v4/token");

var tokenDetails = new List<KeyValuePair<string, string>>()
{
    new KeyValuePair<string, string>("code", authorizationCode),
    new KeyValuePair<string, string>("client_id", Startup.googleAuthOptions.ClientId),
    new KeyValuePair<string, string>("client_secret", Startup.googleAuthOptions.ClientSecret),
    new KeyValuePair<string, string>("redirect_uri", "https://localhost"), //vaid google redirect url. 
    new KeyValuePair<string, string>("grant_type", "authorization_code")
};

var tokenPostData = new FormUrlEncodedContent(tokenDetails);

var client = new HttpClient();
var response = await client.PostAsync(accessTokenEndPoint, tokenPostData);
if (response.IsSuccessStatusCode)
{
    var content = await response.Content.ReadAsStringAsync();
    dynamic jObj = (JObject)Newtonsoft.Json.JsonConvert.DeserializeObject(content);

    accessToken = jObj["access_token"];
}
```

**Comment by schaukoski** [comment]
Hello @Nadejde  thank you so much!

Yes, i use it often. I left the redirect_uri blank.

At the first attempt i get a bad request like this:
´´´
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
´´´

In the second try, i get the code was already redeemed
´´´
{
  "error": "invalid_grant",
  "error_description": "Code was already redeemed."
}
´´´

the field grant_type is "authorization_code"

**Comment by Nadejde** [comment]
@schaukoski  you need to put redirect_url in there. And it needs to match one of the valid urls you've set for that client_id in the google app console. Like here:

**Comment by schaukoski** [comment]
It worked!

@Nadejde  I would like to thank you so much for your patience and kindness to help somebody that barely speak english, posting codes, examples and images.

We need more people like you in my country, Brazil.

@Nadejde , @sammuggPS  Thanks guys!!!!  You rock!

**Comment by Nadejde** [comment]
@schaukoski 
Haha. No worries mate. Any time. Glad to hear you've got it working.

**Comment by sammuggPS** [comment]
@schaukoski, glad you got it working!
@Nadejde, thanks for all your great input. You were a huge help!

**Comment by schaukoski** [comment]
@Nadejde since you are a really nice guy, I will abuse you ;) 

Im trying to debug this line of code, but when i press F10, i get no answer. The postman gets stucked waiting for a callback.

I have used on try catch block to see if jumps to catch, but nothing. Im sorry, but i have no experience with await and async methods.

```
var response = await client.PostAsync(accessTokenEndPoint, tokenPostData);
```

Thanks!

**Comment by Nadejde** [comment]
@schaukoski You need to make sure that the method calling the code using await is declared as async, otherwise the program execution does not wait for the PostAsync to finish. Like this:
```
private async Task<string> RequestExternalAccessToken(string provider, string authorizationCode)
{}
```
However if you do this you will have to use await on the method that calls this one, and so on (which is not necessarily a bad thing). If your method is an action in the controller you can just do this and it will work fine:
```
public async Task<IHttpActionResult> GetExternalAccessToken(string provider, string authorizationCode)
{}
```
Alternatively if you want to avoid the whole async business altogether you can do:
```
var response = client.PostAsync(accessTokenEndPoint, tokenPostData).Result;
```

Choose whatever method works best for you.

**Comment by schaukoski** [comment]
@Nadejde  Thanks again!

I will study about async and await in .NET!

Thanks man, have a great day.

**Comment by Nadejde** [comment]
@schaukoski  you're welcome. have a great day yourself.
