### ISSUE TITLE
Redirects back to google.com

### ISSUE THREAD

**Issue by shinyMetilda** [EddyVerbruggen/cordova-plugin-googleplus#191]
The page redirects back to google.com on successful login.

The following method needs to be implemented inside AppDelegate of GooglePlus.m to redirect back to app

-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options{
    return [[GIDSignIn sharedInstance] handleURL:url
                               sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                      annotation:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}

Kindly fix.

**Comment by arrunn** [comment]
This is conflicting with cordova-plugin-facebook4. Fb login fails to return from Safari if this code added.

**Comment by shinyMetilda** [comment]
Can you do something like this?



    - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url
options:(NSDictionary<NSString*, id> *)options

I had to implement both methods in order for my app to work properly.
I have facebook authentication too, so my methods ended up looking
like the following.

    - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url
options:(NSDictionary<NSString*, id> *)options {
        return [[FBSDKApplicationDelegate sharedInstance] application:app
                                                              openURL:url

sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]

annotation:options[UIApplicationOpenURLOptionsAnnotationKey]]
                || [[GIDSignIn sharedInstance] handleURL:url

sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]

annotation:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
    }
    - (BOOL)application:(UIApplication *)application openURL:(NSURL
*)url sourceApplication:(NSString *)sourceApplication
annotation:(id)annotation
    {

            return [[FBSDKApplicationDelegate sharedInstance]
application:application
                                                              openURL:url

sourceApplication:sourceApplication
                                                           annotation:annotation
                     ] ||
                    [[GIDSignIn sharedInstance] handleURL:url

sourceApplication:sourceApplication
                                                     annotation:annotation];
       }



As mentioned in the thread of this link
https://code.google.com/p/google-plus-platform/issues/detail?id=900  ,
as this is a serious issue, since it is not redirecting back to app.

**Comment by shinyMetilda** [comment]
I had created a pull request with the google redirection fix. The repo can be found at https://github.com/shinyMetilda/cordova-plugin-googleplus/blob/master/src/ios/GooglePlus.m . This would work for login without FB SDK. Try the above code if you are using FB authentication too.

**Comment by sammuggPS** [comment]
Hey @shinyMetilda, can you close this if all is good now? (Thanks for your PR, by the way. Keep it up!)

**Comment by shinyMetilda** [comment]
Done.

**Comment by propertynoticed** [comment]
@shinyMetilda I am using Cordova-Facebook and Google -Facebook. After using following. Facebook stopped working. Can you help me with this ?
`-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary *)options{
return [[GIDSignIn sharedInstance] handleURL:url
sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
annotation:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}`

Thanks
Kunal

**Comment by shinyMetilda** [comment]
Hi ,

If you are using it with Facebook. Try something like this
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/191.
Make sure to import the necessary Facebook .h file

**Comment by propertynoticed** [comment]
@shinyMetilda  Superb!! Thanks

**Comment by amitbindal09** [comment]
@shinyMetilda Thanks!! Its working for me.
