### ISSUE TITLE
Unwanted scope required if using "offline"

### ISSUE THREAD

**Issue by oskarnrk** [EddyVerbruggen/cordova-plugin-googleplus#196]
If you set 'offline' to true to have the token automatically the plus.login scope is required but this behavior is too strong and it's actually not needed.

**Comment by sammuggPS** [comment]
Hey @oskarnrk, thanks for pointing this out.

I just merged a significant update yesterday that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out. Let me know if you have any questions!

- Sam

**Comment by sammuggPS** [comment]
Hey @oskarnrk,

Not sure if you saw the update, but if your issue got resolved please close it!

Happy Coding,
~Sam

**Comment by oskarnrk** [comment]
Hi @sammuggPS, thanks for the update. I'm using a fork of the previous version that I fixed for my usage and now I cannot test the new version. I can do it in some days. But I trust you so I close the issue.
Thank you again!
