### ISSUE TITLE
How to secure web google api key ?

### ISSUE THREAD

**Issue by fr4ngus** [EddyVerbruggen/cordova-plugin-googleplus#197]
Hello, I use the plugin for my Ionic app but I read on the Google Developper page that you should not embedded in your source code the api key. So there is a solution to secure the api google key ?

**Comment by sammuggPS** [comment]
Hey @fr4ngus,

I just merged a significant update to the code last night that I think you'd be interested in checking out.

You are correct, though, that the api key is not what you would want embedded in the source code. There seemed to be some confusion of terms between the Google docs and this plug in, so allow me to clarify:

For this plugin, the only thing you should need in your hybrid code (javascript) is the web ClientId (which you can find on the developer's console). Android uses your SHA1 fingerprint + bundle id to recognize the application and iOS the reversed client id.

You can find this and more information reflected in the docs. Let me know if you have further questions.

Happy coding!

**Comment by fr4ngus** [comment]
Ok it's clear right now.
Thanks !
