### ISSUE TITLE
Google showing that this  Method is deprecated and wont function as intended so should we not use it

### ISSUE THREAD

**Issue by ezazwar1** [EddyVerbruggen/cordova-plugin-googleplus#198]

**Comment by EddyVerbruggen** [comment]
Which method exactly, and at what point do you see it?

**Comment by ezazwar1** [comment]
https://developers.google.com/+/mobile/ios/getting-started 

If You go to the Link You provided The google says that this is deprecated 

so that's why i am concerned whether to use it or not and can we go ahead and change the google Login with new Method

**Comment by sammuggPS** [comment]
Hey @ezazwar1, I just merged a significant update today that you should check out. The main change was for the Android side to use Google SignIn instead of Google+.

FYI, @EddyVerbruggen had already updated the iOS side to use the Google SignIn SDK before the changes today, so the deprecated methods you refer to were not being used any more.

**Comment by ezazwar1** [comment]
Hey @EddyVerbruggen  Please Update The docs Link So that no one gets confused 

Thanks @sammuggPS  

and Special Thanks To @EddyVerbruggen  For Such a cool Plugins.

**Comment by sammuggPS** [comment]
@ezazwar1, I updated the link last night. Happy coding!

**Comment by ezazwar1** [comment]
I Have A suggestion as i saw the return values returned from google api  have lots of fields but currently we have only few options in this plugin so i suggest to add more Like the Cover picture 

@sammuggPS  
@EddyVerbruggen 


Thanks

**Comment by sammuggPS** [comment]
@ezazwar1,

I'm glad you pointed this out.

I intentionally did not include anything past the basic information returned. The purpose of this plugin is authentication, not to cover every use case of the Google APIs. The data returned covers all that would be necessary to meet that goal.

Anything beyond basic authentication you will need to implement yourself. Feel free to edit the plugin locally if you want to get that data back at sign in, but for the purposes of this plugin, the data returned will only be in regards to authentication, authorization, and identity.

I'll be sure to make that more clear in the documentation. Let me know if you have any more questions.

**Comment by ezazwar1** [comment]
Hey @sammuggPS  Can you Please at least Tell me which method to call in java file to get the coverpic url

or just point me to the code where its shown 


Thanks

**Comment by sammuggPS** [comment]
@ezazwar1,

I don't know off the top of my head what would need to be called. Your best bet would be to dive into the APIs provided by Google to figure it out! If anyone knows, it'll be Google. This is their show, after all.

To help you along, here are the links to the [iOS](https://developers.google.com/identity/sign-in/ios/api/) and [Android](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/package-summary) Google Sign-In references.

Happy Coding!
~Sam
