### ISSUE TITLE
Intel XDK build failing - dex error

### ISSUE THREAD

**Issue by Moghul** [EddyVerbruggen/cordova-plugin-googleplus#200]
I am using Cordova 5.1.1 and building on the Intel XDK building tool.
I got the dex error and attempted to fix it as per #114 which gave me another error

Not recognizing known sRGB profile that has been edited

:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJava.../AppAnalyzer/platforms/android/src/nl/xservices/plugins/GooglePlus.java:7: error: package com.google.android.gms.auth.api does not exist
import com.google.android.gms.auth.api.Auth;
                                      ^
.../AppAnalyzer/platforms/android/src/nl/xservices/plugins/GooglePlus.java:160: error: cannot find symbol
            .addApi(Auth.GOOGLE_SIGN_IN_API, gso.build());
                    ^
  symbol:   variable Auth
  location: class GooglePlus
.../AppAnalyzer/platforms/android/src/nl/xservices/plugins/GooglePlus.java:174: error: package Auth does not exist
        Intent signInIntent = Auth.GoogleSignInApi.getSignInIntent(this.mGoogleApiClient);
                                  ^
.../AppAnalyzer/platforms/android/src/nl/xservices/plugins/GooglePlus.java:185: error: package Auth does not exist
            handleSignInResult(Auth.GoogleSignInApi.silentSignIn(this.mGoogleApiClient).await());
                                   ^
.../AppAnalyzer/platforms/android/src/nl/xservices/plugins/GooglePlus.java:196: error: package Auth does not exist
            Auth.GoogleSignInApi.signOut(this.mGoogleApiClient).setResultCallback(new ResultCallback<Status>() {
                ^
.../AppAnalyzer/platforms/android/src/nl/xservices/plugins/GooglePlus.java:217: error: package Auth does not exist
            Auth.GoogleSignInApi.revokeAccess(this.mGoogleApiClient).setResultCallback(new ResultCallback<Status>() {
                ^
.../AppAnalyzer/platforms/android/src/nl/xservices/plugins/GooglePlus.java:258: error: package Auth does not exist
            handleSignInResult(Auth.GoogleSignInApi.getSignInResultFromIntent(intent));
                                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 40.731 secs

.../AppAnalyzer/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: .../AppAnalyzer/platforms/android/gradlew with args: cdvBuildDebug,-b,.../AppAnalyzer/platforms/android/build.gradle,--no-daemon
Command finished with error code 1: .../AppAnalyzer/platforms/android/cordova/build --debug,--buildConfig=.../AppAnalyzer/build.json
ERROR building one of the platforms: Error: .../AppAnalyzer/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: .../AppAnalyzer/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (.../cordova/cordova-cli/5.1.1/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

I'm not sure at all how to fix it and this is the only google plugin that doesn't request a client secret. Please, help.

**Comment by sammuggPS** [comment]
Hey @Moghul,

I just merged a significant update the other day that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out.

Because your issue lies with getting the `auth.api`, I think you need to make sure that you have your environment properly set up. Make sure that you have the following installed and up to date in addition to your Android platform:
- Android SDK Build-Tools,
- Android Support Library, and
- Google APIs *for your platform*

In the cordova plugin.xml, you should have the following frameworks in the android platform section:
```
<framework src="com.google.android.gms:play-services-auth:+" />
<framework src="com.google.android.gms:play-services-identity:+" />
```

However, you *should not* need to manually change plugin.xml. It will be correct and up to date if you added the plugin using the `plugin add https...` option.

Let me know if you have any questions!

Happy Coding,
~Sam
P.S. If your issue gets resolved, please close it!

**Comment by Moghul** [comment]
I just pulled today (I think it's version 4.0.8). The build I pulled gave me the dex error. I took the whole step 3 bit from #114 and replaced it in the code and did the whole local import thing. I do have the Android SDK Build-Tools, support library and api but I'm going to assume they are outdated. Since I'm no longer at work right now, I'll take a look at them tomorrow morning and see what I can do. I'll update you then. Thanks for your help so far!

Extra info: my Facebook Plugin is currently using android-platform-v13, same as my Push Plugin. Could there be an issue there?

**Comment by sammuggPS** [comment]
@Moghul, to be sure we're working from the same code base, could you please remove the plugin and then re-add it with the following commands? When you're back at work, of course.

```
$ cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid
$ cordova prepare
```

Our current version, 4.0.9, is in pre-release, so if you add the plugin via the npm registry it will not be up to date with the documentation found on this repository. Solutions in issue #114 are no longer relevant for the latest version.

**Comment by Moghul** [comment]
@sammuggPS I just removed the plugin and added it with the following variables:
http://i.imgur.com/zXpKdyd.png

After installation, this is the message I received:
http://i.imgur.com/0ZRGqMp.png

Still no 4.0.9 but I am currently updating my Android sdk libraries which might fix the issue. I will keep you updated.

**Comment by Moghul** [comment]
@sammuggPS Alright, I cloned the repository to my computer and I can see your merges; do you think it would be a good idea to attempt to import from there? My current version version still says 4.0.8 and still gives me this:


UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	.../android-sdk/build-tools/21.1.2/dx --dex --no-optimize --output .../AppAnalyzer/platforms/android/build/intermediates/dex/debug --input-list=.../AppAnalyzer/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 33.197 secs

.../AppAnalyzer/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: .../AppAnalyzer/platforms/android/gradlew with args: cdvBuildDebug,-b,.../AppAnalyzer/platforms/android/build.gradle,--no-daemon
Command finished with error code 1: .../AppAnalyzer/platforms/android/cordova/build --debug,--buildConfig=.../AppAnalyzer/build.json
ERROR building one of the platforms: Error: .../AppAnalyzer/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: .../AppAnalyzer/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (.../cordova/cordova-cli/5.1.1/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by Moghul** [comment]
@sammuggPS Not sure if related but I just noticed that this line

"PACKAGE_NAME": "io.cordova.hellocordova"

is added to each plugin reference in each json file (like android.json) in the plugins folder.
Removing it didn't seem to have any effect and neither did replacing it with my app's package name.

**Comment by sammuggPS** [comment]
Plugin Version: I just realized that I forgot to change the version in plugin.xml from 4.0.8 to 4.0.9, so that part's on me, haha. You were right!

play-services-auth:
This is the package that you need for Google Sign-In. Without it, you'll get a whole mess of other errors.

Dex:
After looking into this dex error a bit, I am 90% confident that this is not an issue directly regarding the plugin. Other people have been able to get the plugin installed and running no problem.

Sometimes, in situations like this, it might be best to completely delete your android platform and recreate it. Doing so would give you the confidence that you are starting with a clean platform directory, not muddled down by various tweaks and changes.

Also, I strongly recommend that you update your version of cordova and make sure your cordova android platform is up to date as well.

android-support:
On the note of the android support libraries, I did not have to add a support.jar to my project anywhere. You should be using the android sdk manager to get all your android dependencies and then cordova build android should pull all the things you need in on its own.

Sorry I can't be of more help, but as I said, I'm very confident that this is not an issue directly with the plugin but with the version of cordova, android-support, and other sdk-related packages.

Happy coding and godspeed, @Moghul,

~Sam

**Comment by Moghul** [comment]
@sammuggPS 
Thanks for the help and I hope this might assist others in the future:
I decided to go with what is more or less my own implementation with oauth2. It was quick and easy and it gives me everything I need (no client secret required, has to be a web application clientID, not android).

I used these following links to pull me along:
https://developers.google.com/oauthplayground/
https://github.com/krisrak/jquery-cordova-oauth2/blob/master/cordova.oauth2.js
I also used postman.

Further notes: android-support libraries are present in at least 2 plugins in my project (baked right into them). I am confident that the fact that that is happening might be the reason behind this. Would be a good thing to note that this might not be compatible with phonegap-plugin-facebook.

When using intel-xdk you don't really have the option to remove a platform and re-add it. Best case scenario you have to redo the app.

I am also confident that this isn't caused by this plugin but more by a conflict between plugins. Shame, knowing this would have saved me a few hours.

Let me know if I should close this or maybe you can do it if you want to.

**Comment by sammuggPS** [comment]
@Moghul,
It's curious to me that the error doesn't show up without the google plugin but does with it.

It's also curious to me that XDK doesn't let you make modifications like that. I don't know what your experience with cordova or phonegap is, but have you tried removing/updating/re-adding platforms from the command line? Personally, I do all my cordova actions using the CLI.

I'll go ahead and close this issue. I'm also going to highlight the part in your previous comment that this is a **_conflict between plugins_**, not an issue with this plugin imparticular. It's always good to be aware of all the components you're adding to your project! Stuff like this can pop up when you least expect it.

All the best,
~Sam

**Comment by Moghul** [comment]
@sammuggPS 
There used to be a conflict there as well, between v4 and v13 but I replaced v4 with v13 and it was fine.

I'm not sure if you can do it from command line but I've looked into it and Intel XDK has a little row of blue buttons in the settings that you can press and that does more or less the same thing. Regardless, it's a shame this happens since I now had to code my own flow.

Thank you for your time!
