### ISSUE TITLE
Build error if use together with cordova-plugin-facebook

### ISSUE THREAD

**Issue by Silvercast** [EddyVerbruggen/cordova-plugin-googleplus#202]
Hi,
My project requires both [Facebook plugin](https://github.com/jeduan/cordova-plugin-facebook4) and your wonderful Google Plus login plugin. Unfortunately, I have build error related to multidex because both link to GooglePlay service.

Do you have any idea how I can have both? thanks

**Comment by YaroslavG** [comment]
Hi, 
I have the same problem
[82](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/82)

**Comment by shinyMetilda** [comment]
Hi, if you are having trouble with ios build  while using Facebook login,
this thread might be of help
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/191

**Comment by Silvercast** [comment]
@YaroslavG so can you use this plugin latest commit with Facebook plugin on Android or not? because I saw your contradict comment on https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/141

**Comment by YaroslavG** [comment]
Silvercast,
yes, I use this plugin with Facebook on Android and IOS

**Comment by ezazwar1** [comment]
try using Telerik facebook plugin

**Comment by leonardobazico** [comment]
For me google signin works fine, but facebook not. Browser doesn't close after authorization.

**Comment by YaroslavG** [comment]
leonardobazico,
Hi, I have the same problem, facebook not working on IOS 9

**Comment by erinsasha** [comment]
Hello, All!

Also faced the same problem. I have latest cordova version, latest plugins **EddyVerbruggen/cordova-plugin-googleplus** and **EddyVerbruggen/phonegap-facebook-plugin**.

```
:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)


 FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_92\bin\java.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 29.115 secs
Error: Error code 1 for command: cmd with args: /s,/c,"C:\B2CMApp\b2cmessenger-cordova\platforms\android\gradlew cdvBuildDebug -b C:\B2CMApp\b2cmessenger-cordova\platforms\android\build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
``` 

```
jdk1.8.0_92
<preference name="android-minSdkVersion" value="19"/>
Android Support Repositoy : 32
Android Support Library : 23.2.1
```

Both plugins works fine without each other.

**Comment by sykaeh** [comment]
I have the same problem as well. If I do not have `cordova-plugin-googleplus 4.0.8 "Google+"` installed, the Android build works fine, but once I add the googleplus plugin (either from git or npm). The Android build fails with the same message as above.

These are the plugins I am using:
```
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.1 "Network Information"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.2.2 "Whitelist"
ionic-plugin-deploy 0.5.6 "IonicDeploy"
ionic-plugin-keyboard 2.2.0 "Keyboard"
phonegap-facebook-plugin 0.12.0 "Facebook Connect"
```
