### ISSUE TITLE
Not working on IOS 8.4

### ISSUE THREAD

**Issue by YaroslavG** [EddyVerbruggen/cordova-plugin-googleplus#206]
Hi, I use this  plugin on Android and IOS>9 and it is works peferctly on , but seems it not work on IOS 8.4
I attached my screenshot
![0-neu-d1-bbcc47223e4165cdb2a91888a35366c2](https://cloud.githubusercontent.com/assets/5793103/14252330/744691c4-fa8f-11e5-9718-8c817e80118b.jpg)

**Comment by sammuggPS** [comment]
@YaroslavG,

Hey! There's a simple explanation for this: iOS 9 and above use what is called the [SafariViewController](https://developer.apple.com/videos/play/wwdc2015/504/), an in app version of safari that has (mostly) replaced iOS's older [WKWebView](https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/).

So on 8.4 and back, this is how the plugin is supposed to work! If you continue to sign in, it should work, no problem.

And yes, I understand that this does not provide the option for the user to cancel. If you need that, you can configure the WKWebView settings as needed.

Happy coding!
~Sam

**Comment by YaroslavG** [comment]
sammuggPS,
Thank you for quick answer, can you help me how to configure  the option for the user to cancel?

**Comment by sammuggPS** [comment]
@YaroslavG, I've never done it before. You'll have to dive in to the documentation and figure out yourself! There's a link to the WebView documentation in my original comment.

However, here's something to consider: https://david-smith.org/iosversionstats/

According to Mr. David Smith's statistics on iOS versions, iOS 8 is falling off the maps. Therefore, the necessity of customizing the WebView is something you should consider. Will it be worth it down the road? How much utility will people actually get out of it?

Either way, it's up to you to figure it out. Good luck!
