### ISSUE TITLE
REVERSED_CLIENT_ID for Android?

### ISSUE THREAD

**Issue by masai2k** [EddyVerbruggen/cordova-plugin-googleplus#209]
Hi,
when I add this plugin inserting REVERSED_CLIENT_ID var, I don't find the same var in android.json file under plugins folder. Is it necessary to use REVERSED_CLIENT_ID for android app??

Massimo

**Comment by sammuggPS** [comment]
Hey @masai2k, the REVERSED_CLIENT_ID is only for the iOS side of this application. It does not apply to Android.

Please read through the documentation provided in the README!
