### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by shash5** [EddyVerbruggen/cordova-plugin-googleplus#211]
cordova googleplus plugin in ionic weather oauthToken is same as serverAuthCode...???

**Comment by sammuggPS** [comment]
Ehhhh not quite. There was a naming mismatch somewhere along the way, probably associated with Google changing up their auth process.

You should dive into Google's Sign-In documentation and read up on the different parts so you know how and why everything is fitting together the way it is.

Happy coding,
~Sam
