### ISSUE TITLE
Unable to exchange authcode for access token on my flask based web app

### ISSUE THREAD

**Issue by vivekpd15** [EddyVerbruggen/cordova-plugin-googleplus#214]
I have clearly given the webClientId taken from the client id for web application from the google developer console for the same project. I am able to get the authcode successfully on my android app but when I send this code to the python code on the server so that it can exchange it for the access token. I receive a "redirect_uri_mismatch" error. I have set the redirect_uri properly in the console matching spelling, case, scheme, port & trailing slash and the generated JSON file is used as the client_secret file on the server. 

I am using the following piece of code for token exchange: "client.credentials_from_clientsecrets_and_code(CLIENT_SECRET_FILE, ['profile', 'email', 'https://www.googleapis.com/auth/userinfo.profile'], authcode)"

I am using the latest version 4.0.9 pulled from Github. Please help me find what I am doing wrong.

**Comment by sammuggPS** [comment]
@vivekpd15,

First off, you need to pass in the the client secret itself, not the file it is in.

Second, is there documentation somewhere for this code snippet? I've never seen that function before. Normally, I exchange the authcode using Google's REST API.

**Comment by vivekpd15** [comment]
Hi sammuggPS, Thanks for replying. 

The code snippets documentation is right [here](http://oauth2client.readthedocs.org/en/latest/source/oauth2client.client.html#oauth2client.client.flow_from_clientsecrets). 

But never-mind. I got it working, figured out that I needed to pass the redirect_uri as a parameter to this function. Keeping it in the CLIENT_SECRET file only wouldn't work.

**Comment by sammuggPS** [comment]
@vivekpd15,

Gotcha. Glad you got it working!
