### ISSUE TITLE
Getting idToken in Android

### ISSUE THREAD

**Issue by kartikagarwal1993** [EddyVerbruggen/cordova-plugin-googleplus#219]
The documentation mentions to pass `webClientId` for retrieving back the idToken in android. But after going through the GooglePlus.Java I found that using `webApiKey` solves the issue.

**Comment by sammuggPS** [comment]
@kartikagarwal1993,
Do you mean to say that you are calling login like this?
```javascript
window.plugins.googleplus.login(
    {
        webApiKey: "<your api key>"
    }
);
```

If so, I think you might be using the npm version of the app. That version mostly works, but it does use some deprecated login methods.

I recommend that you use the version of the plugin that is installed when you install using the GitHub URL.

**Comment by kartikagarwal1993** [comment]
I see, anyways solved the problem with the npm version itself by calling like this
`window.plugins.googleplus.login(
    {
        webApiKey: "<your api key>"
    }
);`

Will I face other issues while using the npm version?

**Comment by sammuggPS** [comment]
Potentially. The largest issue with previous versions (from my POV) is that they do not conform to all of Google's practices and terminology. Second, the android and ios sides are using different authentication practices (Google+ and Google Sign-in, respectively). In the most recent code on Git, both sides use Google Sign-In.

All I can say is tread lightly. The android code on npm is using some deprecated libraries. iOS should be mostly good to go.
