### ISSUE TITLE
Able to get everything except idToken

### ISSUE THREAD

**Issue by hcw12889** [EddyVerbruggen/cordova-plugin-googleplus#228]
I've followed the guideline from the README and from the internet.
Everything is ok except that I cannot get the idToken.
I can get the email and the full profile of the user, even if I set 'offline' parameter to true, I can also get the oauthToken.
But whatever I do, I still can't get the idToken

What I've done to try to solve it:
- Set the SHA1 in Android Client Id in Google developer console
- Use Web Client Id instead of Android Client Id (I've tried both of them)

How can I retrieve the idToken?
I've also tried to follow the documentation of Google using oauthToken to get access token to get the user info, but it doesn't work and give me warning of 'Error fetching OAuth2 access token, message: 'invalid_grant'.

Can anyone help me..?

Attached with screenshot:
![screenshot_2016-05-07-03-37-16-1](https://cloud.githubusercontent.com/assets/1859928/15084588/015365f2-1407-11e6-8390-d57153875fa1.png)

**Comment by hcw12889** [comment]
![screenshot_2016-05-07-03-52-47-1](https://cloud.githubusercontent.com/assets/1859928/15084665/8bead8f8-1407-11e6-91bf-e86a439e881e.png)

Screenshot with the alert of getting oauthToken

**Comment by hcw12889** [comment]
After checking the code in GooglePlus.java, I've found the solution to get idToken.
Which is changing the parameter name 'webClientId' to 'webApiKey'.

window.plugins.googleplus.login(
{'webClientId': 'client id of the web app/server side'}
..
//rest of the code

@sammuggPS 
Could you please modify the README document? Thank you.

**Comment by sammuggPS** [comment]
Hey!
The documentation on GitHub right now reflects the most recent code (v4.0.9), NOT the version returned from NPM (v4.0.8).
I put a note at the top of the readme stating this.
The latest code uses Google SignIn on both IOS and Android. The older code uses Google Plus on the Android side.
Please read the documentation for more info. If you want to continue using the legacy version, you can use GitHubs file history to view an older version of the Readme.
Cheers!
.........
Sam





On Fri, May 6, 2016 at 1:31 PM -0700, "hcw12889" <notifications@github.com> wrote:












Closed #228.
