### ISSUE TITLE
Google plus sign in API Depricated.

### ISSUE THREAD

**Issue by Abdul-Moiz** [EddyVerbruggen/cordova-plugin-googleplus#229]
I was integrating this plugin but unfortunately it was giving invalid_uri error. 
On inspection figure out the API is deprecated by google and no longer working.
https://developers.google.com/+/mobile/ios/sign-in

It would be nice if someone can migrate this to Google sign in API :)

Thanks.

**Comment by sammuggPS** [comment]
Hey there! IOS has already been migrated to Google Sign in.

The NPM version is using Google+ for Android, but the GitHub version is using Google Sign In. Cheers!

**Comment by angeloocana** [comment]
How do I install from Github instead of npm?
I'm with npm version already installed. 

Thanks

**Comment by sammuggPS** [comment]
There are instructions in the README documentation.

P.S. The Readme as it is now reflects usage for the GitHub codebase. Previous versions of the README will apply to the NPM codebase.

Cheers!

**Comment by angeloocana** [comment]
Thanks, it works like a charm!
But I get the token in .oauthToken instead of .serverAuthCode as described in documentation.

**Comment by sammuggPS** [comment]
What platform are you testing on?
Sometimes when upgrading a plugin you need to remove from the platform first.
Sometimes you need to completely remove the platform then make it again.
Other times it works as you'd expect, haha.

**Comment by sammuggPS** [comment]
@angeloocana I just got back to reviewing this ticket:

Did you get the GitHub version properly installed?

**Comment by EddyVerbruggen** [comment]
Version 5.0.0 on npm supports Google Sign-In on both iOS and Android. Thanks @sammuggPS for all your help!
