### ISSUE TITLE
Not working with Android version 4.4.4

### ISSUE THREAD

**Issue by vishalwayachal** [EddyVerbruggen/cordova-plugin-googleplus#233]
Hi,
First I would like to congratulate you for making this awesome package. 
I am using this for one of my project, it work great with  Google Nexus 5 (Android Version 5.1.1)

But when I try to integrate it with Google Nexus 4 (Android version 4.4.4), I can't receive any response from respective plugin (google).

Will you please correct me if I am missing something or I need to implement any other framework for this.
Looking forward from your end.

Thanks in Advance.

**Comment by ravshan4yk** [comment]
Do you have any results?
