### ISSUE TITLE
undefined variables.

### ISSUE THREAD

**Issue by yerko18** [EddyVerbruggen/cordova-plugin-googleplus#238]
Hello, I have a problem signing, I can only rescue the mail but others appear as undefined variables.

Last version of cordoba
Latest version of this plugin

this is the function:

function login() {
   window.plugins.googleplus.login(
        { 'scopes': 'profile email'
    	},
        function (obj) {
          document.querySelector("#image").src = obj.imageUrl;
          document.querySelector("#image").style.visibility = 'visible';
          document.querySelector("#feedback").innerHTML = "Hi, " + obj.displayName + ", " + obj.email;
		  alert("displayName :" + obj.displayName + "\n" +
		  			"email :" + obj.email + "\n" +
 					"userId : " + obj.userId + "\n" +
 					"displayName : " +  obj.displayName + "\n" +
 					"imageUrl : " +  obj.imageUrl + "\n" +
 					"idToken : " +  obj.idToken + "\n" +
 					"oauthToken : " +  obj.oauthToken + "\n" +
 					"gender : " +  obj.gender + "\n" +
 					"givenName : " +  obj.givenName + "\n" +
 					"middleName : " +  obj.middleName + "\n" +
 					"familyName : " +  obj.familyName  + "\n" +
 					"birthday : " +  obj.birthday + "\n" +
 					"imageUrl : " +  obj.imageUrl + "\n");
        },
        function (msg) {
          document.querySelector("#feedback").innerHTML = "error: " + msg;
        }
    );
  }

I tested with different gmail accounts and nothing changes

![screenshot_2016-05-27-10-22-39](https://cloud.githubusercontent.com/assets/1042883/15610856/753ed458-23f5-11e6-9ff8-166a8c2a831b.png)
![screenshot_2016-05-27-10-25-16](https://cloud.githubusercontent.com/assets/1042883/15610857/75431432-23f5-11e6-8b23-349d6c03a768.png)

**Comment by vikas0vanvi** [comment]
hello , i have same issue , have you found any solution ?

**Comment by yerko18** [comment]
@vikas0vanvi  

no, no yet

**Comment by matheo** [comment]
Gotta try the latest git, because there are changes on the Google API

**Comment by sammuggPS** [comment]
As @matheo said, please try the latest git.

Also, please note that you'll only get an idToken back on Android if you pass in the webClientId. You'll only get a serverAuthCode on both platforms if you pass in the webClientID && offline: true.

**Comment by sammuggPS** [comment]
@yerko18, Out of curiosity, are you using Ionic to create and build your app?

**Comment by vikas0vanvi** [comment]
hello , i am getting error code 10 if i use latest git , at least old was giving only email Id , i am using normal cordova project btw. thanks...

**Comment by yerko18** [comment]
@sammuggPS,  i use cordova without ionic

**Comment by yerko18** [comment]
@matheo: 
the last version only with "git"? because, i use:

plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID="myId"

And, the problem is not solved.

**Comment by vikas0vanvi** [comment]
this one is new
cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus

**Comment by yerko18** [comment]
@vikas0vanvi 
the latest solve this problem?

**Comment by vikas0vanvi** [comment]
nope , now i don't even getting response , its giving in error function

**Comment by yerko18** [comment]
@sammuggPS @matheo 

somebody can help us?

**Comment by sammuggPS** [comment]
Hey all, I've been talking to @lemondesigns about the error 10 bit. Check out issue thread #240 to see what we've been talking about.

**Comment by vikas0vanvi** [comment]
its been long i am stuck in this problem so i have used this solution for temporary purpose 

http://stackoverflow.com/questions/23930744/how-to-use-google-login-api-with-cordova-phonegap

**Comment by yerko18** [comment]
@sammuggPS I did not serve that information, I use the most up to date from Github but did not let me build or run , i tested with "cordova plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid"  and add the version "**4.0.8**" and still does not work, undefined variables still appears

@vikas0vanvi , I tested your solution but at the time of calling the function  callGoogle(), i get an error with  "**var deferred = $.Deferred();**", you can help me while I find a solution with this plugin

**Comment by sammuggPS** [comment]
@yerko18 if you are using the version from GitHub, please refer to our README.

v4.0.9 changes the names and removes some of the items originally found in the response object. The purpose being to narrow the scope of this plugin to have a barebones focus on identity and authentication.

**Comment by yerko18** [comment]
@sammuggPS  I use from Github, but i get an error in build for android 
CMD>**cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid**

i copied index.html from directory "**demo**"

CMD>**cordova build android**

![captura](https://cloud.githubusercontent.com/assets/1042883/15900590/057be746-2d6e-11e6-86cc-cfc502b946fc.PNG)

**Comment by sammuggPS** [comment]
Have you tried opening the android directory in Android Studio and seeing what errors it brings up?

**Comment by yerko18** [comment]
how i do that?
i have Android Studio 1.2.2 but I never use

**Comment by sammuggPS** [comment]
1) Open Android Studio
2) Open an existing project
3) In the dialog, navigate to your platforms directory
4) Select and open the android directory

**Comment by sammuggPS** [comment]
Did you run `cordova prepare` after you installed and added `index.html`?

**Comment by sammuggPS** [comment]
This forum is talking about ionic, but you could still try deleting `.gradle` and rebuilding.

http://stackoverflow.com/questions/35227860/ionic-cordova-error-code-1-error-building-one-of-platforms

**Comment by yerko18** [comment]
@sammuggPS 
yes, i run **cordova prepare** after

**Comment by yerko18** [comment]
@sammuggPS 
I delete the folder but when you build the entire folder is downloaded and I get the same error

**Comment by sammuggPS** [comment]
Hmm I dunno what to say. Whatever it is, it sounds like it's something with your project set up. Can you try the following?
1. create a completely new project
2. Drop in the `index.html`
3. Add the plugin
4. create _only_ an android platform
5. `cordova prepare`
6. Build/run/test?

**Comment by yerko18** [comment]
this is how I've tried, from the beginning I create an empty project and have added only plug Google+, just the android platform.
Right now I'm updating the android SDK to rule that

More information
Java >> jdk v1.8.0_45 - jre v1.8.0_91
android_ant >> v1.9.5
cordova >> v6.1.1
cordova-plugin-googleplus >> v4.0.9

Windows 7, x64

**Comment by sammuggPS** [comment]
Ohhhhh you're using Ant to build the project? If that's the case, why are you getting a gradle error?

**Comment by sammuggPS** [comment]
http://gradle.org/getting-started-android/

**Comment by yerko18** [comment]
Works, but the version 4.0.9 from Github
I update all of android SDK, and create a completely new project. Now I include in my project the plugin and try it, thanks for the help and advice

This information I can recover:
email         
userId      
displayName 
imageUrl

![screenshot_2016-06-08-16-12-11](https://cloud.githubusercontent.com/assets/1042883/15909400/41408086-2d94-11e6-8ab2-534b87831c26.png)

**Comment by sammuggPS** [comment]
@yerko18 Excellent!

Make sure you go through our documentation to understand what is and is not being returned in version 4.0.9!
