### ISSUE TITLE
Phonegap Build Server Error on Plugin Include

### ISSUE THREAD

**Issue by mrmaiko** [EddyVerbruggen/cordova-plugin-googleplus#24]
Hello,

When <gap:plugin name="nl.x-services.plugins.googleplus" version="1.0.7" /> is added to the project with or without the version attribute Phonegap Build fails with the attached screen shot.

http://i.imgur.com/KylmTw8.jpg

Works fine when I remove it, and the other plugins are working fine as well.

Is this not compatible with Phonegap Build?

**Comment by mikegetlottoapp** [comment]
Thank you, Nicholas!

**Comment by RustyGumbo** [comment]
Still not working after changing to that :(

**Comment by nicholasareed** [comment]
@RustyGumbo works fine for me, I just built it seconds ago on PGB using that line. Both Android and iOS are OK.

**Comment by RustyGumbo** [comment]
Maybe it's a conflict with another plugin.. could you share the plugin list for the project you built? So I can compare it to mine :)

**Comment by nicholasareed** [comment]
No problem: https://github.com/FamousMobileApps/waiting_app/blob/master/config.xml

It might also help to look at the error log for whichever platform you're building for; I previously had issues with the android-support-vX libraries.

**Comment by RustyGumbo** [comment]
Apparently is has a conflict with the com.phonegap.plugins.facebookconnect plugin!

**Comment by nicholasareed** [comment]
Yup, in case you're only using it for login, I've already solved that problem. See the commented out facbook portion of that config.xml I posted two above: https://github.com/FamousMobileApps/waiting_app/blob/master/config.xml#L84

I didn't need any features beyond login, so that is the only thing I made sure was compatible :)

**Comment by RustyGumbo** [comment]
That seems to be working! Although the app doesn't build on Windows Phone anymore (which doesn't really affect me atm).

Thanks a bunch!

**Comment by nicholasareed** [comment]
Yeah, I haven't ever built on WP...someday! Glad to hear it worked, and I
hope some of the non-login functions work for you if you need them.
Eventually I expect the "official" facebook plugin to work better with g+
so I don't have to host the weird "nickreed.blah.blah.blah" plugin
