### ISSUE TITLE
User Cancelled error when adding "Youtube" scope

### ISSUE THREAD

**Issue by akirayuki129** [EddyVerbruggen/cordova-plugin-googleplus#241]
When I call this.....

```
window.plugins.googleplus.login({
         'scopes': 'profile email youtube',
         'offline': true,  
         'webClientId': '0000.apps.googleusercontent.com'
},
```

It shows the logged in accounts.  Then, after you tap one it immediately throws an error that says "user cancelled".  If I remove the "youtube" scope I get a token back but when I try to use it to call the youtube api I get this:

```
{
	"error": {
		"errors": [{
			"domain": "global",
			"reason": "insufficientPermissions",
			"message": "Insufficient Permission"
		}],
		"code": 403,
		"message": "Insufficient Permission"
	}
}

```
I'm only testing on Android right now.  I'm using build.phonegap.com to build it.  This is in my config.xml:

```
<gap:plugin name="cordova-plugin-googleplus" source="npm">
    <param name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.-0000" />
  </gap:plugin>
```

So, I think that means it is loading the latest version from npm, right?

Any help would be appreciated.

Thanks!

Eric

**Comment by sammuggPS** [comment]
Hey @akirayuki129,

First, thanks for checking out the plugin!

Second, please refer to this [list of Google Identity scopes](https://developers.google.com/identity/protocols/googlescopes). I believe for your case you'd want the scopes passed in to be `'scopes': 'https://www.googleapis.com/auth/youtube'`.

Third, note that profile and email are included by default, so you shouldn't need to add them to the list of scopes.

Fourth, you are correct that phonegap is pulling the latest code from NPM. If you want to use the github version, try this:
```
<gap:plugin spec="https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git" source="git">
    <param name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.-0000" />
</gap:plugin>
```

I realize not all this info was documented. I'll update the README today!

Cheers!
~Sam

**Comment by akirayuki129** [comment]
Thanks for the reply.  I'm getting closer!  Now I get this message:

Failed to retrieve token: Unknown

I'm looking through other messages to try to figure out why.

**Comment by akirayuki129** [comment]
I tried using latest in git and I never get called back after tapping my email.

**Comment by akirayuki129** [comment]
It's working!  The last thing I was missing was to build with the correct cert.

**Comment by sammuggPS** [comment]
Excellent! So glad you figured it out. Was that with the Git version?
.........
Sam Muggleworth
Software Engineer
m 703.881.2521
twitter @PointSource @sammugg
Sam.Muggleworth@PointSource.com
www.PointSource.com




On Thu, Jun 2, 2016 at 2:02 PM -0700, "akirayuki129" <notifications@github.com> wrote:












It's working!  The last thing I was missing was to build with the correct cert.

**Comment by akirayuki129** [comment]
No, that was with the npm version.  The git version isn't working for me right now.
