### ISSUE TITLE
Older plugin version available for PhoneGap Build?

### ISSUE THREAD

**Issue by asgathea** [EddyVerbruggen/cordova-plugin-googleplus#25]
Hi,

I'm trying to create a PhoneGap app that uses this plugin and the Facebook Connect plugin. Unfortunately I get a "jar mismatch" error on PhoneGap Build when both plugins are included. Apparently the Google Plus plugin uses version 21 of android-support-v4.jar while the other plugin uses version 20. Is it possible to make version 1.0.5 of the Google Plus plugin available for PhoneGap Build again?

**Comment by celwell** [comment]
`
Also, if you can recommend any direction on getting the server-side to have access to the email scope after receiving the authToken from this plugin, that would be great! I can get access to the entire G+ profile, but no email addresses (but I get one from the G+ plugin).
`

@nicholasareed Hey Nicholas, did you ever find a solution to getting the Email addresses on the scope? I, too, need to retrieve it server side but the scope is not including email address.

**Comment by nicholasareed** [comment]
@celwell I wish! I had to rip GPlus out because I couldn't get it working correctly. If you come across a newer solution, I'd love to hear about it

**Comment by celwell** [comment]
@nicholasareed I ended up just taking the email address from the JS object in the response, and sending that alongside the auth token. So, now my email are able to be spoofed, since I'm not checking server side, oh well.
