### ISSUE TITLE
Still getting 12501 error code.

### ISSUE THREAD

**Issue by sanjosedennis7593** [EddyVerbruggen/cordova-plugin-googleplus#255]
I tried all of the following solution i found out on this plugin but nothing works. They said that there's mismatch on client_id or either the package name but i always checked it and it is same. I already use webClientId but none of it works. Installing the latest plugin not also works. Is there anyone out here solve issue like what i've been experience? Thanks :)

**Comment by J-who** [comment]
Yeah I've been battling this issue for awhile now too. Nothing seems to work.

**Comment by sammuggPS** [comment]
12501 while developing usually means your SHA1 when you were setting up your client ID was incorrect. It could also mean that you are using the Android Client Id instead of the Web Application Client Id.

For Google Sign In you _have to_ use the Web Application Client Id (counter-intuitive, I know, but it is what it is).

**Comment by sammuggPS** [comment]
Also, make sure that you have the following items installed and up-to-date in your SDK manager:

1. SDK Tools (latest)
2. Platform-tools (latest)
3. Build-tools (latest)
4. API 23 or less (Cordova 6.x and Cordova-android 5.x only support up to 23) with the following:
    1. SDK Platform (keep up to date)
    2. An emulator image that includes Google APIs (i.e. Google APIs Intel x86 Atom System Image)
    3. Google APIs (the standalone install)
5. Android Support Repo (latest)
6. Google Play Services (latest)
7. Google Repository (latest)

**Comment by sanjosedennis7593** [comment]
I already fixed it, i fixed by using the android-debug keystore instead of my own generated keystore. By the way thanks.

**Comment by sammuggPS** [comment]
Hey @sanjosedennis7593, if you're good to go, please close the issue!

**Comment by uzumakinaruto123** [comment]
Same issue here. I am getting error code 12501. I have checked my SHA-1 , its correct. used the one from android-debug keystore. I am passing webClientId as parameter.

**Comment by limaneto** [comment]
@sammuggPS where is the Web cliente ID is suppose to go ?

**Comment by Riyaz0001** [comment]
thanks all, I'm solved this problem. error 12501

**Comment by Riyaz0001** [comment]
can anyone tell me, how to get a user birthday in this plugin? how do use scope?
