### ISSUE TITLE
Showing `Have offline access` Dialog, even when offline is set to false

### ISSUE THREAD

**Issue by saiy2k** [EddyVerbruggen/cordova-plugin-googleplus#258]
I dont require `offline` access and I even set it explicitly as follows:

		window.plugins.googleplus.login(
			{
                'offline': false
			},
			function (obj) {
				console.log('User found', obj);
			},
			function (msg) {
			  	console.log('Error: ', msg);
			}
		);

But still I am getting this dialog:
![screenshot_2016-08-08-10-12-55](https://cloud.githubusercontent.com/assets/701985/17469493/2f7f6d52-5d51-11e6-9a43-d4bde6d87583.png)

**Comment by sammuggPS** [comment]
What version of the plugin are you using?

**Comment by saiy2k** [comment]
Version: "~4.0.8"

**Comment by sammuggPS** [comment]
Can you try using version 4.0.9 and tell me if run into that issue (or any other issues)? Version 4.0.8 on Android is using deprecated APIs.

Despite not being on NPM yet, 4.0.9 is in pretty good shape. Any issues people have run in to have been surrounding set up and dev environment differences (i.e., some people have been using the incorrect Client ID and running into issues).

**Comment by sammuggPS** [comment]
To install v4.0.9:
```bash
$> cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --save --variable REVERSED_CLIENT_ID=yourReversedClientId
$> cordova prepare
```

**Comment by saiy2k** [comment]
@sammuggPS  Thanks for the Input. With version 4.0.9, its working right, as expected 👍
