### ISSUE TITLE
[iOS] Build Fail - "Undefined symbols for architecture arm64"

### ISSUE THREAD

**Issue by roblav96** [EddyVerbruggen/cordova-plugin-googleplus#259]
I'm trying to build and deploy to the store and this build error occurs:
![Build Error](https://s10.postimg.org/uxsyzncih/Screen_Shot_2016_08_08_at_8_22_18_PM.png)

What's weird is when I build to test on a device, it builds and deploys to device no problem.

Thoughts?

**Comment by roblav96** [comment]
# SOLVED
Turns out enabling `In-App Purchases` through capabilities resolves this issue.

**Comment by EddyVerbruggen** [comment]
With plugin version 5.0.0 this should no longer be necessary as Google has removed the dependency on StoreKit, see "Removes the dependency on StoreKit." [here](https://developers.google.com/identity/sign-in/ios/release). At least, I assume that's where the error originates from.
