### ISSUE TITLE
iOS invalid_client - OAuth Client Not Found

### ISSUE THREAD

**Issue by berzley** [EddyVerbruggen/cordova-plugin-googleplus#261]
I have the login working on Android but not iOS. Using the demo I get the following error:
<img width="373" alt="screenshot 2016-08-10 11 38 48" src="https://cloud.githubusercontent.com/assets/3287266/17561277/4e343716-5ef3-11e6-9c71-15c8bc634e6f.png">

I have the webClientId set in my JS (I think that's just for Android though). My generated GoogleServices-Info.plist was added to the project. I've tried adjusting it's values around with no luck.
Beyond that I'm stumped. I feel like it is either the 'audience' or the 'client_id' as seen in the screenshot that might be the issues.

**Comment by sammuggPS** [comment]
What version of the plugin are you using? Did you install with a Reversed Client Id? That can be found in your GoogleServices-Info.plist (which you don't actually need to include in the project).

If you're passing in a webClientId, make sure it is the one of type Web Application (**not** of type Android, iOS, or other).

**Comment by sammuggPS** [comment]
Also, we are aware of the issue with iOS on v4.0.9 right now where the window isn't closing after signing in.

**Comment by sammuggPS** [comment]
Don't use a Reversed WEB client id. It needs to be the reversed iOS Client ID (So the original value in Info.plist).

When you install the plugin, you need to include `--variable REVERSED_CLIENT_ID=<the value from Info.plist>`. This sets a URL Type REVERSE_CLIENT_ID which you can see under the Target>Info tab in XCode. It should be something like `com.googleusercontent.apps.<string of numbers/letters>`.

The client id of type Web Application is only the one that you are passing in when calling the plugin. Like so:

```javascript
window.plugins.googleplus.login(
    {
        webClientId: "<Client Id of type Web Application>"
    },
    function () {},
    function () {}
);
```

**Comment by berzley** [comment]
@sammuggPS Thank you very much, this resolved all of my issues.

**Comment by Aydogdy** [comment]
berzley, how did you solve the issue? Could you help me plz, i am getting the same error

**Comment by berzley** [comment]
It all had to do with the REVERSE_CLIENT_ID - Unfortunately, it's been so long I no longer remember what the exact issue was beyond what I can gather from the above thread.
I know when installing the plugin setting `REVERSE_CLIENT_ID` correctly was the key. @sammuggPS comment above popped everything into place for me.

I'm actually about to get back into this project in the coming week and should I come across the issue (or at least the structure behind it) I'll message again with an update.
