### ISSUE TITLE
Calling login() throws an error in Xcode

### ISSUE THREAD

**Issue by mhartington** [EddyVerbruggen/cordova-plugin-googleplus#267]
Calling `login()` will throw in exception in xcode

```
[NSNull objectForKey:]: unrecognized selector sent to instance 0x1b0ebbef8
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull objectForKey:]: unrecognized selector sent to instance 0x1b0ebbef8
```

Setting break points on all exceptions points to line 84 of GooglePlus.m

```
 NSString* scopesString = [options objectForKey:@"scopes"];
```

**Comment by mhartington** [comment]
My mistake, it seems that even if you dont need to pass any scope, it still must be passed as an empty object.

**Comment by sammuggPS** [comment]
@mhartington, for clarification: Can you post a snippet of what didn't work compared to what did?

**Comment by mhartington** [comment]
What worked,

```
window.plugins.googleplus.login({}, successFunction, errorFunction)
```
What didn't work

```
window.plugins.googleplus.login(successFunction, errorFunction)
```

Simple mistake 😄 

though now I'm not getting redirected back to my main app view, but thats a new issue

**Comment by sammuggPS** [comment]
Ah, yeah. Glad you figured that one out!

Yes, other devs have been running into that issue as well. There are a couple pull requests open right now that I and other collaborators have not gotten around to testing yet. If you're interested, they're #263 and #264. Give those a go! If one works better than the other, please let us know :)

**Comment by mhartington** [comment]
Gave #264 a shot, worked quite well! 

_while you're here..._ 😁  

Any idea on error 10 on android?

**Comment by sammuggPS** [comment]
Awesome! Thanks for testing that out.

Yes! Error 10 and error 12501 are _most commonly_ associated with one of two issues:
1) The SHA1 used to set up your Android project on the dev console is not the same as the one being used to build your project
2) The webClientId being passed into the login or silentLogin methods should be of type Web Application, not Android or iOS (however, I know that you said you were not passing anything in right now).

As always, make sure that your Android SDK is up to date with the following items:
1. SDK Tools (latest)
2. Platform-tools (latest)
3. Build-tools (latest)
4. API 23 or less (Cordova 6.x and Cordova-android 5.x only support up to 23) with the following:
    1. SDK Platform (keep up to date)
    2. An emulator image that includes Google APIs (i.e. Google APIs Intel x86 Atom System Image)
    3. Google APIs (the standalone install)
5. Android Support Repo (latest)
6. Google Play Services (latest)
7. Google Repository (latest)
