### ISSUE TITLE
problem in google login

### ISSUE THREAD

**Issue by ezazwar1** [EddyVerbruggen/cordova-plugin-googleplus#269]
Hey my app is in production and i noticed that for some google users the app does call the success block but returns empty object , that should not be the case . i tried it made a new email id and tried to login with google. The login was successful but it never returned anything and i dont know why is it that for some it returns and for others it doesnt

**Comment by sammuggPS** [comment]
What version of Android is your phone?

**Comment by ezazwar1** [comment]
4.3

**Comment by ezazwar1** [comment]
something was wrong with my code ,
seeing the scope parameter in the plugin login method how can i get the cover pic of user what needs to be written in scope 


Thanks
@sammuggPS

**Comment by sammuggPS** [comment]
I don't know off the top of my head. You'll have to dig in to the developer references over at http://developers.google.com/
