### ISSUE TITLE
[Android] Error thrown on disconnect

### ISSUE THREAD

**Issue by Fatal-Errol** [EddyVerbruggen/cordova-plugin-googleplus#274]
An error similar to https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/199

is thrown when I do a disconnect.

> Uncaught exception from plugin java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.optString(java.lang.String, java.lang.String)' on a null object

The args.optJSONObject(0) is returning null so calling optString in a null object throws the error.

I'm in marshmallow with the up to date files and libraries.

**Comment by Fatal-Errol** [comment]
This seems to happen if I haven't previously authenticated via google and then call the disconnect function. It will be good if this wil be handled more gracefully rather than making my script stop.

**Comment by EddyVerbruggen** [comment]
Fair point. The next version will gracefully invoke the error callback for `logout` and `disconnect` on Android in case `login` or `trySilentLogin` were not invoked in the same app lifetime.
