### ISSUE TITLE
Cordova throws error on build

### ISSUE THREAD

**Issue by litunny** [EddyVerbruggen/cordova-plugin-googleplus#277]
I saw this awesome plugin, and i loved it based on the cool functionalities, but after doing all the requirements and all, while building it threw error. At first i thought it was my cordova itch, remove the plugin and build again and everything went fine, i thought maybe it was my android-sdk, I used my other windows machine with sdk version 5.1.1 add the plugin again and build but still threw the same error, thereafter i remove the plugin in the same project rebuild and every went fine. Please see below error message in my cordova console:

**Error code 1 for command: cmd with args: /s /c "C:\wamp\www\wiicr8\Atarah\platforms\android\gradlew cdvBuildDebug -b C:\wamp\www\wiicr8\Atarah\platforms\android\build.gradle -Dorg.gradle.daemon=true"

ERROR building one of the platforms: Error: cmd : Command failed with exit code 1

You may may not have the required environment or OS to build this project

Error: cmd: Command failed with exit code 1

Caught exception:
undefined**

**Comment by EddyVerbruggen** [comment]
That's a _very_ generic build error.. can't you find something related to this plugin?

I'm only testing on a Mac btw, so I can't help you with this. Mac/Windows shouldn't make a difference though.

**Comment by litunny** [comment]
Okay, thank you. I think i need to consider some other means.

Thank you for replying.
