### ISSUE TITLE
Android build (error: cannot find symbol result.put("familyName", acct.getFamilyName());)

### ISSUE THREAD

**Issue by fernandosimoes** [EddyVerbruggen/cordova-plugin-googleplus#278]
Someone can help me??

When I build my android app using ionic 2 I'm got an error on the picture.

![error-ionic2](https://cloud.githubusercontent.com/assets/3368885/18530510/34fa8432-7aa8-11e6-8f67-a99304ede0c4.PNG)

I tried to uninstall and install again, but nothing happens I aways got same error, follow my plugin list installed on app and my ionic and Cordova version
![plugin list](https://cloud.githubusercontent.com/assets/3368885/18530594/981c96f4-7aa8-11e6-85de-329d8f4eb240.PNG)
![ionic and Cordova v](https://cloud.githubusercontent.com/assets/3368885/18530595/981e3d38-7aa8-11e6-81e8-f18663aa84d4.PNG)

**Comment by EddyVerbruggen** [comment]
Please update your Android SDK, especially the Play Services repository. I'm not entirely sure which version you need though.

**Comment by fernandosimoes** [comment]
Thank's for your help, problem really was solved with update thank you again

**Comment by EddyVerbruggen** [comment]
👍

**Comment by Ram-SR** [comment]
How to update Play Services repository? Please provide me a screenshot of android studio.

**Comment by EddyVerbruggen** [comment]
@Ram-SR please Google it.

You may find results like: "type `android` in the console/Terminal"

**Comment by Ram-SR** [comment]
Hell with this. Installed Android support library, Play Services repository. Still the problem is continuing. @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
What does "Hell with this" mean? Does it help solving the issue? I don't have your machine on my desk so it's impossible for me to figure it out, right?

**Comment by Ram-SR** [comment]
What is the link between result.put("familyName", acct.getFamilyName()); and android studio?

**Comment by EddyVerbruggen** [comment]
There is no link between those two; `acct.getFamilyName()` was a function not available in the OP's version of Google Play Services. Updating that fixed the issue.

**Comment by Ram-SR** [comment]
Even with my updates, problem is continuing. What might be the reasons?

**Comment by JPodz** [comment]
Ran into this issue as well, but updating everything solved it. Thanks @EddyVerbruggen! 👍

**Comment by Ram-SR** [comment]
Solved but when I using `window.plugins.googleplus.login()`, it throwing this error `property 'plugins' does not exist on type 'Window'`. Please help me

**Comment by Ram-SR** [comment]
Thank you so much for your valuable response @EddyVerbruggen. Done everything. I have a doubt regarding `trySilentLogin()` method. If I already logged into 3 accounts in my device(Android Gmail app), which account will be logged into my app(created by me)? The response in both `login()` and `trySilentLogin()` cases is a number. Is that OAuth2 token? Can we get details of the logged user? How? Please help me.
