### ISSUE TITLE
Not Working on IOS 10

### ISSUE THREAD

**Issue by ezazwar1** [EddyVerbruggen/cordova-plugin-googleplus#280]
Please Help the login was working fine but i tried it on ios 10 but its not working 

Regards 
Ezaz

**Comment by magicfa** [comment]
workshop perfekt

Frank Rittershofer

**Comment by ShonChuang** [comment]
Me too !! IOS 10 not working!

**Comment by ShonChuang** [comment]
I'm find the solution. 
[http://stackoverflow.com/questions/38689631/how-to-use-facebook-ios-sdk-on-ios-10/38799196#38799196](http://stackoverflow.com/questions/38689631/how-to-use-facebook-ios-sdk-on-ios-10/38799196#38799196)

**Comment by ezazwar1** [comment]
Hey @ShonChuang  Are you able to login with google now cause when i call the google login the browser that used to open 0n IOS 9.x is now not opening and there is hell lot of logs that are being written in simulator



Regards
Ezaz

**Comment by ShonChuang** [comment]
Hi @ezazwar1 , 
You need use xcode edit and to turn on "enable keychain sharing ". (like up URL article)
After run project on simulator!  you can try it !

**Comment by EddyVerbruggen** [comment]
@ShonChuang is right - since iOS 10 you need to enable that switch. Looking to automate it for you..

**Comment by EddyVerbruggen** [comment]
Would be nice if some of you wants to give the current master repo on GitHub a spin. It should auto-add the entitlements file after plugin install, so you can forget about Xcode.

**Comment by shlomiassaf** [comment]
@EddyVerbruggen I can confirm working on my emulator (iOS 10, iPhone 7)
Disabled "enable keychain sharing"
rebased repo.
💯

**Comment by EddyVerbruggen** [comment]
@shlomiassaf great, thanks! I'll publish a new npm version shortly.

**Comment by EddyVerbruggen** [comment]
Available now from npm: version 5.1.0

**Comment by valgen** [comment]
Hi everyone,

I'm testing this plugin via a Visual Studio 2015 Cordova project connected to a Mac iOS 10 and iPhone 6 Simulator (remotebuild).

I keep getting the following Javascript error: keychain error

I'm using this version:
<plugin name="cordova-plugin-googleplus" version="5.1.1">

Could you please tell me what should I do to make this working?

**Comment by sammuggPS** [comment]
@valgen please open a new ticket instead of using this closed one.
