### ISSUE TITLE
"trySilentLogin" still not work after use "window.plugins.googleplus.login" (only in Android)

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-googleplus#29]
I am using Android 4.4.2
when I am not already use "window.plugins.googleplus.login"，if I use "trySilentLogin"，it will show the err callback，"no value token"
but..
when I am already use "window.plugins.googleplus.login" and got many information about JSON.stringify(obj)
this time if I use "trySilentLogin" again，it will show nothing (no any response)，still not trigger the success callback

my code just as same as yours and use your 1.0.7 version on PGB，1.0.8 version not try yet on "plugins.cordova.io"

PS
so that will cause only the first time login can got the full JSON.stringify(obj)，after it，it will no way to trigger it again，otherwise disconnect and login again

**Comment by bau720123** [comment]
hi @EddyVerbruggen and @nicholasareed 
I install 1.0.8 version with PGB 3.6.3
but still have the same situation

**Comment by bengtweisse** [comment]
+1

**Comment by bau720123** [comment]
anything update or ... ?

**Comment by bengtweisse** [comment]
I built a workaround. Call logout before

**Comment by bau720123** [comment]
hi @bengtweisse 
I can't understand what you mean ?
you found a solution ?
how ?
any step ?

**Comment by bengtweisse** [comment]
The Plugin provides a logout Method. The Plugin does nothing if you are
already loggedin. So i am triggering logout before relogin.
Am 07.02.2015 13:13 schrieb "包四維" <notifications@github.com>:

**Comment by bau720123** [comment]
hi @bengtweisse 
in Android 4.4.2
well...
of course when you are in "already login success" situation that you can use "logout" again before "relogin" or "reSilentLogin"
but it is not the correct logical

because in the real situation
if users want to check his(her) information about GooglePlus "again"..
but you can't tell your users...(hi users...you must logout again that can use "relogin" or "reSilentLogin")

PS
in iOS，the logical is totally perfect

**Comment by bau720123** [comment]
hi @bengtweisse 
I made a detail explain right here
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/45

**Comment by EddyVerbruggen** [comment]
Fixed in #45, thanks for your patience!
