### ISSUE TITLE
error 12501 REVERSED_CLIENT_ID and webClientId

### ISSUE THREAD

**Issue by trangnt58** [EddyVerbruggen/cordova-plugin-googleplus#296]
I am using Ionic 2 RC0. 
Following tutorial, after step 3: Google API setup, I received 2 OAuth 2.0 client IDs (web client and android client). 
https://drive.google.com/file/d/0B6E5FToRUMKrZmM2OFZyOEx3V1E/view?usp=sharing
I add plugin with android client id.
`cordova plugin add cordova-plugin-googleplus --save --variable REVERSED_CLIENT_ID='androidclientid'`

and call login method with option webClientId is webclientid that I received
```
window.plugins.googleplus.login(
    {
      'scopes': '... ', // optional, space-separated list of scopes, If not included or empty, defaults to `profile` and `email`.
      'webClientId': 'client id of the web app/server side', // optional clientId of your Web application from Credentials settings of your project - On Android, this MUST be included to get an idToken. On iOS, it is not required.
      'offline': true, // optional, but requires the webClientId - if set to true the plugin will also return a serverAuthCode, which can be used to grant offline access to a non-Google server
    },
    function (obj) {
      alert(JSON.stringify(obj)); // do something useful instead of alerting
    },
    function (msg) {
      alert('error: ' + msg);
    }
);
```
But I got 12501 error. What is wrong?

**Comment by EddyVerbruggen** [comment]
Did you set the SHA-1 as well? You really have to triple check everything as it's something in your setup..

**Comment by trangnt58** [comment]
Yes, I done with SHA-1. I want to ask about REVERSED_CLIENT_ID. Is it web client id or android client id?

**Comment by sammuggPS** [comment]
The Reversed ClientId is only for the iOS part of the plugin. On the Google Developers Console, it will be listed as the iOS URL Scheme.

**Comment by trangnt58** [comment]
@EddyVerbruggen @sammuggPS  Thanks for supporting. Now it works. My problem is difference between Debug and Release.
Debug is from %USERPROFILE%\.android\debug.keystore 
Release is from my-release-key.keystore

**Comment by limaneto** [comment]
for developing on Ionic are we suppose to install the plugin using the Reverse Cliente Id generated by the ourself created OAuth 2 with the Release fingerprint ?
