### ISSUE TITLE
redirect url not handled when redirected from Google+ app on iOS

### ISSUE THREAD

**Issue by visionscaper** [EddyVerbruggen/cordova-plugin-googleplus#3]
Hi,

In the AppDelegate entry point (IdentityUrlHandling):

```
(BOOL)identity_application: (UIApplication *)application
                 openURL: (NSURL *)url
       sourceApplication: (NSString *)sourceApplication
              annotation: (id)annotation
```

the url does not contain "oauth2callback" when redirected from the Google+ app. It only contains this string when redirected from Safari. Locally I fixed this as follows inside the AppDelegate entry point:

```
GooglePlus* gp = (GooglePlus*)[[self.viewController pluginObjects] objectForKey:@"GooglePlus"];

if ([gp isSigningIn]) {
    return [GPPURLHandler handleURL:url sourceApplication:sourceApplication annotation:annotation];
} else {
    // call super
    return [self identity_application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}
```

In the GooglePlus class I maintain a isSigningIn state.

Kind regards,

-- Freddy

**Comment by kritikaperiwal12** [comment]
Can anyone help me? I am using Google Plus framework for Gmail sign in. But while submitting App on app store the app is rejected and the reason behind this is it navigates to safari, to resolve this issue i have to use Safari View Controller API. So How can i use this in my project. Should i change the whole approach for Google Plus Framework that i already implemented in y project?
