### ISSUE TITLE
Enable server-side API access for app

### ISSUE THREAD

**Issue by sagarinnova** [EddyVerbruggen/cordova-plugin-googleplus#30]
Hi,
Can you please suggest if I can use the same plugin to request a one-time authorization code.
Basically I need one-time authorization code , as I want server to be able to make Google API calls on behalf of users or while they are offline.

Current plugin is working successfully as client side implementation. It would be great if you could expose that API in GooglePlus.js

Thanks,
Sagar

**Comment by AbhilashThomas** [comment]
Any updates?

**Comment by phw** [comment]
This is absolutely possible. See my answers to #80 and #100
