### ISSUE TITLE
Domain Specific

### ISSUE THREAD

**Issue by iliDaedalus** [EddyVerbruggen/cordova-plugin-googleplus#302]
Could you please add "gso.setHostedDomain(domain);" ?
That will only allow accounts on specific domain to login.

Personally, I've created a preference in the config.xml that I can set comma-seperated domains, then passed them in the signIn method as argument (together with webClientId), and then in java if the argument is not null or empty, I add the gso.setHostedDomain(< for each domain in the comma-seperated string>);
Similar in GooglePlus.m

**Comment by sammuggPS** [comment]
Hey @iliDaedalus,
The goal of this plugin is to provide the bare minimum required to authenticate users using Google Sign In. Therefore, additional functionality -- such as restricting the domain or retrieving additional information -- is on the developers using the plugin to implement and maintain.

**Comment by iliDaedalus** [comment]
OK I understand.
I only thought that's a very small but good to have additive.
Thank you for the nice plugin anyways!

**Comment by sammuggPS** [comment]
If you think that other devs/projects would find it useful, you're more than welcome to implement it then make a pull request to add it in! This is an open source project :)

**Comment by iliDaedalus** [comment]
I'll do that thanks!

**Comment by iliDaedalus** [comment]
Pull request created:
[https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/303](url)
