### ISSUE TITLE
Google Auth error 400 : Invalid redirect URI

### ISSUE THREAD

**Issue by ducmaxime** [EddyVerbruggen/cordova-plugin-googleplus#309]
<img width="826" alt="screen shot 2016-11-28 at 08 44 33" src="https://cloud.githubusercontent.com/assets/6499846/20659915/e87e2bd4-b546-11e6-8b23-433bd502e18e.png">

Hi, I try to use it with google OAuth:

1. I have activated Google+ API on https://console.developers.google.com/apis/credentials
2. I have created an ID client OAuth
<img width="746" alt="screen shot 2016-11-24 at 20 15 57" src="https://cloud.githubusercontent.com/assets/6499846/20659680/62f2af40-b545-11e6-9f2b-b63b6643c8d6.png">
3. My code 

![screen shot 2016-11-28 at 08 36 02](https://cloud.githubusercontent.com/assets/6499846/20659896/ce4ea18a-b546-11e6-8722-220e167cfcdf.png)

4. I have started my app -> ionic emulate ios

5. I have this error
<img width="325" alt="screen shot 2016-11-25 at 18 08 53" src="https://cloud.githubusercontent.com/assets/6499846/20659883/b8ff1922-b546-11e6-9e3b-03f08c5e324d.png">

Can you help me ?

thx

**Comment by Arlem** [comment]
Same here

**Comment by husmen73** [comment]
same here. android works, ios NOT works.

**Comment by ducmaxime** [comment]
For me it's not woking on Android :(. 

But for IOS I have a solution.

Just import the generated google-service.plist file on root of your project.

good luck

**Comment by krunalpanchal** [comment]
Awesome solution ducmaxime. It worked very well !!. Thanks a tonne.

**Comment by Dranix** [comment]
@ducmaxime Thank you very much for wonderful solution. You save my poor desk from being head banged repeatedly

**Comment by FlashGordon95** [comment]
Where to put tabs info ? 
Still having this issue :/

**Comment by Arlem** [comment]
@FlashGordon95 From target tab click on info, there should be URL Type at the bottom of the view. See attached images.
![screen shot 2017-03-23 at 09 51 32](https://cloud.githubusercontent.com/assets/6169446/24239482/6ccfcbd8-0fae-11e7-99eb-dd6276974404.png)
![screen shot 2017-03-23 at 09 51 44](https://cloud.githubusercontent.com/assets/6169446/24239487/6f89afd8-0fae-11e7-8b97-ca3d6b64e417.png)

**Comment by FlashGordon95** [comment]
Thank you for the reply. 
+1 for screenshots, I'm sure others will come here for same problem too.
Thank you!

**Comment by hoangnguyen291** [comment]
@ducmaxime thanks a lot, i've been stuck for 2 days on this, you've saved my life 👍

**Comment by Klerith** [comment]
@ducmaxime You are my hero, thank you

**Comment by sant-ngeneo** [comment]
Cli in Main Project, Cli in the Tag -> info > URL TYPES, add the REVERSED_CLIENT_ID <google.service.plist>

**Comment by hassanalizealteks** [comment]
> Cli in Main Project, Cli in the Tag -> info > URL TYPES, add the REVERSED_CLIENT_ID <google.service.plist>

kindly show me with detail in ionic 4 project for ios
