### ISSUE TITLE
How to get id_token?

### ISSUE THREAD

**Issue by RobinJain15** [EddyVerbruggen/cordova-plugin-googleplus#310]
Hi @EddyVerbruggen / @sammuggPS 

I'm using this plugin in my app. I need id_token to pass onto server so that I can verify the integrity of the user.

I'm using following in the scopes, though only getting the email id
{
                            'scopes':'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me',
                            'webClientId': 'xxxxxxxx-xxxxxxxx.apps.googleusercontent.com'
                          }

Is there something I'm missing in scopes?
Can you please suggest what else I can do to get the id_token?

**Comment by modularwill** [comment]
Hi @EddyVerbruggen / @sammuggPS

I am having the same issue @RobinJain15 describes above. 

Any ideas on a solution?

**Comment by RobinJain15** [comment]
Hi @sammuggPS

Can you guys please suggest something?

FYI : It is an hybrid app in phonegap.

I checked the previously raised issues and found a similar one there, #245 it is. You mentioned that it could be an issue with NPM version. I'm using the NPM version. Though when I switched to github version app stopped responding.

Thanks,
Robin.

**Comment by sammuggPS** [comment]
Hi @RobinJain15,

First things first: in your scopes, you do not need to request userinfo.profile. We are requesting that and email by default.

Second, is login successful and you just aren't getting an idToken? Or are you getting an error?

Third, can you provide us some more platform/environment information? What version of phonegap? Cordova? What version of Android are you building for? Are you running this in an emulator? Or on a device?

Fourth, for Android, make sure you have the following installed and up-to-date in your SDK manager:
1. SDK Tools (latest)
2. Platform-tools (latest)
3. Build-tools (latest)
4. API 23 or less (Cordova 6.x and Cordova-android 5.x only support up to 23) with the following:
   1. SDK Platform (keep up to date)
   2. An emulator image that includes Google APIs (i.e. Google APIs Intel x86 Atom System Image)
   3. Google APIs (the standalone install)
5. Android Support Repo (latest)
6. Google Play Services (latest)
7. Google Repository (latest)

**Comment by RobinJain15** [comment]
Hi @sammuggPS 

With NPM version I'm able to login succesfully, though only getting email id. With github version I'm stuck on the login screen, getting no error. It is not going in the error callback.

1. Phonegap version - cli-5.2.0
2. Android version - 4.0 and up
3. Running on - Device

**Comment by RobinJain15** [comment]
Isn't there a way we get the id_token with NPM version? I mean by adding something in scope or anything else.

**Comment by RobinJain15** [comment]
With GitHub version it is giving error "10".

**Comment by sammuggPS** [comment]
To my recollection Error 10 means that the wrong Web Client Id is being applied.

You're supposed to be able to get the ID Token if you supply the web client id field, for both the GitHub and NPM versions. The only difference between GitHub and NPM right now is the "hosted domain" option.

**Comment by RobinJain15** [comment]
Thanks @sammuggPS.

We at least have a reason now why it is not working. I'll cross check the web client id and try.

**Comment by RobinJain15** [comment]
Hi @sammuggPS 

I checked the web client id and it is correct. 

config.xml has
```
<plugin name="cordova-plugin-googleplus" spec="https://github.com/EddyVerbruggen/cordova-plugin-googleplus" source="git">
        <variable name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.948037425713-3cc0aka9u5bl90eungc02hvpat7k6pnk" />
    </plugin>
```

And code from js file is
```
window.plugins.googleplus.login(
    {
      'scopes': 'email profile',
      'webClientId':'com.googleusercontent.apps.948037425713-3cc0aka9u5bl90eungc02hvpat7k6pnk',
    },
    function (obj) {
      alert(obj);
    },
    function (msg) {
      alert(msg);
    }
);
```

When I have the webclientid mentioned then getting error "12501" and when it is not there the error coming is "10".

Can you please check what I'm missing in above code snippets?

Thanks,
Robin.

**Comment by sammuggPS** [comment]
@RobinJain15,

If you're getting an error 12501, that is likely an issue with your SHA1 configuration. Please make sure that the SHA1 used to build and run your application is that same one used in the your app configuration in the developer's console.

**Comment by RobinJain15** [comment]
Hi @sammuggPS 

I was not using SHA1 to build the application. 

Now with below command
**`keytool -exportcert -alias xxxxx_xxxx -keystore xxxxxx_xxxx_xxxxxx.keystore -list -v`**

I'm getting following Certificate fingerprints.

```
Certificate fingerprints:
         MD5:  B4:7F:92:C6:63:81:10:5F:B6:24:2C:CF:E5:10:F8:E2
         SHA1: 21:46:0F:D8:9C:E4:F6:F8:3C:3A:B6:BF:26:02:2E:A3:EB:58:C7:FD
         SHA256: 91:75:6B:89:03:2F:76:96:15:C7:4E:16:CB:CA:9D:85:35:BC:57:94:AD:53:C4:CC:E9:33:62:53:F5:91:49:FD
         Signature algorithm name: SHA256withRSA
         Version: 3
```

When I used SHA1 key from here in the developer's console a new web client id is generated. On using this web client id, I'm again getting error 12501.

Is it something to do with "Signature algorithm name: **SHA256withRSA**"?

Thanks,
Robin.

**Comment by sammuggPS** [comment]
Hi @RobinJain15,

The SHA1 is essentially a hash that identifies the machine/environment/user by which your android application was built. So if you are building an Android application, your SHA1 is coming into play.

What I think is happening is that the SHA1 you see above is not the one being applied when the application is built. So, you have two options:
1) Figure out which SHA1 is getting used and set up your Android credentials with that fingerprint,
2) Figure out how to build the app with whatever credentials are already in the Google dev console.
