### ISSUE TITLE
Success callback not fired, when multiple google accounts are associated with Accounts manager.

### ISSUE THREAD

**Issue by amalantony** [EddyVerbruggen/cordova-plugin-googleplus#33]
When there are multiple Google accounts in the Android accounts manager, calling `window.plugins.googleplus.login` shows the pop up window with the option to choose one of the accounts. However, once the account is chosen, the pop is dismissed and the success callback is not fired. When login is called again, the success callback is fired for the account selected earlier.

**Comment by EddyVerbruggen** [comment]
I can imagine my latest commit (for #45) solves this as well.

**Comment by handmadeadv** [comment]
I'm using 4.0.9 and getting the same error
