### ISSUE TITLE
get gender

### ISSUE THREAD

**Issue by neelancherivishnu** [EddyVerbruggen/cordova-plugin-googleplus#334]
how to get gender, date of birth from this plugin. I am using Ionic 2 . Thank you

**Comment by sammuggPS** [comment]
https://developers.google.com/android/reference/com/google/android/gms/common/Scopes.html#PLUS_LOGIN

Including the scope discussed in the above link is what you would want. However, keep in mind that the only information available is going to be what that user has made public.

Therefore, I recommend that you do not rely on Google SignIn to supply gender, date of birth, etc. It would be better to ask for that information separately as part of a "sign up" flow for your application.

**Comment by Jai-Krish** [comment]
I'm trying to fetch these info using the OAuth2 API for which I'll need the `access_token` but the unlike in the Facebook plugin the response doesn't contain the access token but it gives the `idToken` and `serverAuthCode`. How do I resolve these into access toke for use in `https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token=ACCESS_TOKEN` ???
