### ISSUE TITLE
Question about documentation - reversedclientid

### ISSUE THREAD

**Issue by JTronLabs** [EddyVerbruggen/cordova-plugin-googleplus#336]
In step 4 it states:

> If you are building a hybrid application (iOS and Android), or an Android application, you have to replace myreversedclientid with the reverse value of Client ID in your Release credential generated on step 3, on Google Developer's Console, this will be: "com.googleusercontent.apps.uniqueId", without quotes.

Are we literally supposed to reverse our client ID for this? So given a client id `1234-123abc123.apps.googleusercontent.com`, we should use `com.googleusercontent.apps.321cba321-4321` ? Or do we just reverse the order: `com.googleusercontent.apps.123abc123-1234`? Do we include the `com.google.apps.`? Thanks much!

Also, in my config.json I have 
```
oauth_client: { 
client_id: ...
...
},
{
client_id: ...
...
}
```
that follows this pattern, which one am I supposed to use? It looks like the id that is not in the oauth_client object matches the client id that is in console.developers.google.com. So I assume this is the id I want, correct?

**Comment by JTronLabs** [comment]
You just reverse order: `com.googleusercontent.apps.123abc123-1234`. I used the client_id found in `console.developers.google.com`.

**Comment by sammuggPS** [comment]
However, make sure that if you are manually reversing the client id that it is the clientId for an iOS application!
