### ISSUE TITLE
Throws alert:service not available

### ISSUE THREAD

**Issue by udhaya10** [EddyVerbruggen/cordova-plugin-googleplus#35]
When trying to loging throws service not available

**Comment by bau720123** [comment]
hi @udhaya10 
you should open the google + service from your console page
please read from this
https://github.com/EddyVerbruggen/cordova-plugin-googleplus#4-google-api-setup
thanks

**Comment by udhaya10** [comment]
Tried with emulator(`cordova emulate android`) and phone it works but not with browser (`cordova emulate browser`)
