### ISSUE TITLE
(bug) Invalid parameter for redirect uri: Invalid Scheme

### ISSUE THREAD

**Issue by theromis** [EddyVerbruggen/cordova-plugin-googleplus#354]
Experiencing issues with this great plugin on ios 10.2.

Found similar question at ionic forum.
Just copying text from this thread:
https://forum.ionicframework.com/t/ionic-native-googleplus-login-invalid-parameter-for-redirect-uri-invalid-scheme/82096

I am using Ionic2/Cordova to log into an app using `Google`.

I try the following, based on[ ionic-native GooglePlus](https://ionicframework.com/docs/v2/native/google-plus/) and [this demo](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/tree/master/demo/ionic2):

      loginGoogleCordova(): void {
        GooglePlus.login({
          'webClientId': 'mywebclientid.apps.googleusercontent.com',
          'offline': true
        }).then(googleData => {
          if (!firebase.auth().currentUser) {
            firebase.auth().signInWithCredential(firebase.auth.GoogleAuthProvider.credential(googleData.idToken))
              .then((success: FirebaseAuthState) => {
                this.doAlert("signInWithCredential successful " + JSON.stringify(success));
                this.signIn(success, AuthProviders.Google);
              })
              .catch((gplusErr) => {
                console.error('GooglePlus failed ' + gplusErr);
                this.doAlert("GooglePlus failed " + JSON.stringify(gplusErr))
              });
          }
        }, error => {
          this.loading.dismiss();
          console.error('loginGoogle: ' + error);
          this.doAlert('loginGoogle: ' + error.message);
        });
      }

Which looks like it makes progress, because it now accesses the Google api. But I get the following:

> Invalid parameter for redirect uri: Invalid Scheme:
> mywebclientid.apps.googleusercontent.com

[![enter image description here][1]][1]

But when I check my `Web client ID` in the Firebase `Authentication` -> `Sign-in Method`, this is the `Web client ID`. 

[![enter image description here][2]][1]

Also, when I installed the plugin, I ran:

    $ ionic plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=mywebclientid.apps.googleusercontent.com

As you can see, it is also in the Xcode's `plist` file:

[![enter image description here][3]][3]

**UPDATE**

I did notice that when looking at my Google APIs, that the `CLIENT ID` is created for `Web client`:

[![enter image description here][4]][4]

I that the problem? Should I create one `CLIENT ID` for `iOS` and another for `Android`? Then have `if statements`:

    if iOS
      use iOS client id
    if Android
      use Android Client id

      use Android Client id

But as you can see from [here][5], it uses: `'webClientId': 'USE-YOURS-HERE!!!!!.apps.googleusercontent.com'`

As a result, I am a little confused, and any advise would be appreciated.

**Comment by FlashGordon95** [comment]
Looking for answer to this too

**Comment by theromis** [comment]
ok in my case everythin was easy, I've used as a REVERSED_CLIENT_ID forward one
!NB: use *iOS URL scheme* not the client ID
it starts from: *com.googleusercontent.apps.123123123.....*

**Comment by geeksilva97** [comment]
> ok in my case everythin was easy, I've used as a REVERSED_CLIENT_ID forward one
> !NB: use **iOS URL scheme** not the ~client ID~
> it starts from: **com.googleusercontent.apps.123123123.....**

How to do this? I added the information to the login method. But it did not work.

```typescript
this.googlePlus.login({
      webClientId: 'com.googleusercontent.apps.3752-and-so-on,
      offline: 'true'
    })
      .then(result => this.userData = result)
      .catch(err => this.userData = `Error ${JSON.stringify(err)}`);
```

**Comment by alisonmb** [comment]
I changed the URL Scheme in info.plist, to something like this: com.googleusercontent.apps.MYAPPIDD. And it's works.
