### ISSUE TITLE
SignIn error in cordova

### ISSUE THREAD

**Issue by lawlessnut** [EddyVerbruggen/cordova-plugin-googleplus#359]
@EddyVerbruggen 

Do you know why i'm getting this error ? is it something to do with my configuration.

> Error in Success callbackId: GooglePlus1939957523 : TypeError: googleUser.getBasicProfile is not a function
cordova.js:314 Uncaught TypeError: googleUser.getBasicProfile is not a function
    at Login.responseGoogle (main.js:156704)
    at Login.<anonymous> (main.js:156766)
    at Object.callbackFromNative (cordova.js:293)
    at <anonymous>:1:9

**Comment by ChrisEelmaa** [comment]
Check out the source code, there is no mention of getBasicProfile() anywhere. What are you trying to do and do you have any code examples?

**Comment by lawlessnut** [comment]
You are right. Let's close the issue
