### ISSUE TITLE
404 error whe installing

### ISSUE THREAD

**Issue by Likon84** [EddyVerbruggen/cordova-plugin-googleplus#36]
cordova plugin add nl.x-services.plugins.googleplus

gives me 404 error. how I can install it?

**Comment by mrmaiko** [comment]
Hi Likon,

Use: 

$ cordova plugin add nl.x-services.plugins.googleplus@1.0.8

For some reason version 1.0.9 is not available.

**Comment by Likon84** [comment]
thx it worked

**Comment by EddyVerbruggen** [comment]
Hi, I tried to unpublish 1.0.9 recently but due to a bug it failed.

I just updated plugman and have now successfully revoked 1.0.9, so installation of 1.0.8 is default again and should work.

@Likon84 thanks for reporting this issue and thanks @mrmaiko for providing a temporary workaround!
