### ISSUE TITLE
Builds fine, but failed to load Info.plist in GoogleAppUtilities.framework

### ISSUE THREAD

**Issue by suspiration** [EddyVerbruggen/cordova-plugin-googleplus#362]
Builds went fine, but when trying to run in simulator getting error "Failed to load Info.plist from bundle at path /<path here>/<app name>.app/Frameworks/GoogleAppUtilities.framework

Tried searching everywhere but couldn't find any solution.  Any input would be greatly appreciated!

**Comment by jans-y** [comment]
Hi, Have you found the solution?

Thank you very much.

**Comment by suspiration** [comment]
I followed Google's instructions and re-added all the framework and it worked after that.

**Comment by jans-y** [comment]
Could you please post a link to that instructions? I removed and re-added frameworks but still the same problem. Thank you.

**Comment by jans-y** [comment]
Thank you for any response, because I am still getting the same error.

**Comment by suspiration** [comment]
This is the link with instructions I followed: https://developers.google.com/identity/sign-in/ios/sdk/
