### ISSUE TITLE
Error: disallowed_useragent

### ISSUE THREAD

**Issue by cthemudo** [EddyVerbruggen/cordova-plugin-googleplus#372]
Hi!

When I exec the sample code in iOS, open a page and tell me:

> 403. That’s an error.
> 
> Error: disallowed_useragent
> 
> This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.
> 

I try this in Phonegap 6.4.6 and Xcode 8.3 with the same error.

Is there any solution?

Thanks!

**Comment by cthemudo** [comment]
Sorry, It's my fault.
I had obsolete code.
Plugin works perfectly.
Thanks!

**Comment by rbiq** [comment]
@cthemudo can you please elaborate on what you mean obsolete code? And what did you exactly do to get this to work? I am facing the exact same issue

**Comment by EuropeanUniversityFoundation** [comment]
I also get the same error, also only for iOS... What did you exactly do?

**Comment by cthemudo** [comment]
I forgot to delete an obsolete code from another library. The other library opens a webview and is not allowed by Google.
My error has nothing to do with EddyVerbruggen's library (cordova-plugin-googleplus)

**Comment by carmen-tang** [comment]
@cthemudo What was the obsolete code that you had? I'm having this exact same issue.

**Comment by charlesbodman** [comment]
Same issue

**Comment by kirantpatil** [comment]
We are also having same issue, please suggest how to resolve the issue .
