### ISSUE TITLE
Getting 12501, when trying to Implement Using Mac

### ISSUE THREAD

**Issue by prashant-93** [EddyVerbruggen/cordova-plugin-googleplus#374]
Hi,
I am trying to Implement this plugin since 2 Days, but when I Implement using Windows Operating System it works fine but when i did the same process using Mac Operating System i get the 12501.

Kindly Check the Process I followed,
1. Create the Ionic Project using command
`ionic start socialLogin Blank`
2. Logged into Google Developer Console and Created a new Project there.
3. Enable the Google SignIn using debug SHA-1 certificate, for Debug keystore i used the command 
 `sudo keytool -exportcert -list -v -alias androiddebugkey -keystore ~/.android/debug.keystore`
as per the Documentation
**It automatically creates a Android client for the project**
4. Generated the release keystore for the Project using keystore Command
`sudo keytool -genkey -v -keystore <key-store-name>.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000`
5. Then Again, I selected the project in Google Developer Console, and select the project Credentials and select the "Create Credentials" for OAuth Client ID and where I pasted the Relese SHA-1
6. Using the Release Reverse Client ID i installed the plugin using npm. **It automatically add my plugin Reference in Config.xml**
7. in the Device Ready function 
`window.plugins.googleplus.login(
    {
      'scopes': ''"
    },function (obj) {
      alert(JSON.stringify(obj));
    },function (msg) {
      alert('error: ' + msg);
    }
);`

Finally i run the Project the using  `sudo ionic run android` and it shows me the Alert for 12501

Kindly, help me where i went wrong.

**Comment by ianlintner-wf** [comment]
I am seeing the 12501 as well on the emulators. I am going to try on physical device tomorrow.

I created the client ids in the console. I see google the device perform the login, but the failed/error callback I get the message 12501.

I am going to walk through the setup again to make sure I didn't screw it up, but I have tried multiple times. It is either that or google made a change that may have broke the library.

I am hope I just messed up the something in the google console.

**Comment by saoron** [comment]
+1

**Comment by ianlintner-wf** [comment]
I resolved my issue. 

1. I was using a business account without the correct permissions for the web api keys on google console. 12501 is an ambiguous error. 

Troubleshooting steps:
* How I figured the error out is I created a fresh google personal account.
* I went to the console: https://console.developers.google.com/apis/credentials
* I went to the credentials screen.
* I created the android & ios credentials in the google api console. For the emulator versions I used the debug key as that was Ionic uses for the emulate versions.  ~/.android/debug.keystore
* Make sure to specify the key & the package based on what is in the manifest.xml

* I then created the web client (oAuth Client Id) API console. I set the urls to 
Authorized Origin: http://localhost
Authorized Redirect: http://localhost/callback

* I also setup the consent screen with the url http://localhost

* I went to the libraries tab.
* I added the APIs 

 Google Cloud Messaging
 Google People API
 Google+ API
 Identity Toolkit API
 Mobile Crash and Performance Reporting API
Token Service
