### ISSUE TITLE
New OAUTH rules

### ISSUE THREAD

**Issue by mike-nelson** [EddyVerbruggen/cordova-plugin-googleplus#377]
Does this plugin use a webview? If so it would not meet the new rules would it?

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by EddyVerbruggen** [comment]
No it uses the webbrowser, not an embedded webview.

**Comment by mike-nelson** [comment]
Cool, thanks, that is great :)

**Comment by mike-nelson** [comment]
Got it working!
