### ISSUE TITLE
PGB 3.6.3 with plugin 1.0.9 will cause all platform build fail

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-googleplus#38]
according to this
http://plugins.cordova.io/#/package/nl.x-services.plugins.googleplus
PGB 3.6.3 with plugin 1.0.9 will cause all platform build fail

but...
PGB 3.6.3 with plugin 1.0.8 is OK ~

**Comment by EddyVerbruggen** [comment]
Hi, I tried to unpublish 1.0.9 recently but due to a bug it failed.

I just updated plugman and have now successfully revoked 1.0.9, so installation of 1.0.8 is default again and should work.

Thanks for reporting this issue!

**Comment by bau720123** [comment]
thanks @EddyVerbruggen
