### ISSUE TITLE
invalid_client for g+ signin

### ISSUE THREAD

**Issue by vcanintranet** [EddyVerbruggen/cordova-plugin-googleplus#380]
I have installed plugin on IOS and try to login with given example, & found that "Invalid Client" and OAuth Client not found. Please help to resolve the issue.

I have tried all the possible ways to get it work but no luck.

**Comment by mike-nelson** [comment]
I saw this and got past it. This means the client ID is not right.

**Comment by vcanintranet** [comment]
i had checked later on and found that my client id was wrong..

thanks for prompt response... :)
