### ISSUE TITLE
Not getting refresh token on the server side using serverAuthCode

### ISSUE THREAD

**Issue by CarsonChen1129** [EddyVerbruggen/cordova-plugin-googleplus#381]
Hi, I tried to use this plugin to do Google authentication with Ionic 2 framework. I can get user info, idToken, and serverAuthCode using this plugin (with offline:true). I sent the serverAuthCode back to my server to perform step2_exchangeCode, but I cannot get a credential with refresh token. The refresh_token that I got is null. 

- Does anyone know how to solve this issue? or otherwise I cannot use the serverAuthCode. 

- If this method is not working, does anyone know how to get access_token with this plugin on Android? I cannot use the JavaScript Google API client without access_token. (gapi does provide a authentication method but that needs the user to input password again and again)

Thank you very much in advance.

**Comment by remster** [comment]
Are you after an accessToken for authorisation? If so, check the new master, you should get it now.

**Comment by sergicurtu** [comment]
CarsonChen1129,

The same happens to me. Despite add different Scopes and webclientId obtained from the Google API Console can not get a refresh_token when I send obj.serverAuthCode to my server (php).

 (I have no problem with the access_token) 

Sergi

**Comment by fquirogam** [comment]
Same here, I want to get the refresToken but I'm only getting the idToken that I assume that corresponds with the accessToken

**Comment by metractive** [comment]
+1

**Comment by CarsonChen1129** [comment]
@EddyVerbruggen Thank you very much for developing this wonderful plugin. Do you have any suggestions regarding the refresh_token issue that I encountered with? I tried the latest master but it is still not getting refresh_token. Thank you.

**Comment by aashkafirst** [comment]
getting same issue

**Comment by sachiv-logiciel** [comment]
Hii everyone,

I tried to use this plugin to do Google authentication with ionic and ionic native. I can get refresh token with serverAuthCode. is there any way to get refresh token with serverAuthCode. Please help i need this very badly.

Thanks

**Comment by kaustubhnj** [comment]
The refresh_token is served only the 1st time the user logs in with Google OAuth. i.e. this first API call that makes use of serverAuthCode to generate the refresh_token and access_token. There after every token refresh request is done using the initially received refresh_token. The response to this call will only return the id_token and access_token. If you loose the initially generated refresh_token, then you will have to re-authorize the user.

**Comment by sachiv-logiciel** [comment]
Hii everyone,

I solve that issue with 2 small changes in  cordova-plugin-googleplus/src/android/GooglePlus.java.
This code change return you refresh_token every time in android.

Goto line no 164. Changes you have to done as follow:-

 if (clientOptions.optBoolean(ARGUMENT_OFFLINE_KEY, false)) {
         gso.requestServerAuthCode(webClientId, false);
 }

To:-

if (clientOptions.optBoolean(ARGUMENT_OFFLINE_KEY, true)) {
         gso.requestServerAuthCode(webClientId, true);
 }

Thanks

**Comment by enzonotario** [comment]
@sachiv-logiciel I'm using this library from ionic. Do you know how can I implement your changes? I modified the code as you say in ```node_modules/cordova-plugin-googleplus/src/android/GooglePlus.java``` but doesn't have any effect. 

Sorry but I don't know if I have to "compile" anything or something else.

Sorry for my english too.

Thanks!

**Comment by sachiv-logiciel** [comment]
Hie @enzonotario 

Please remove your plugin with remove command and again install plugin from my git repository. please change myreversedclientid with your client id in installing command.

Removing command:-

cordova plugin rm cordova-plugin-googleplus --save

Installing command:-
cordova plugin add https://github.com/sachiv-logiciel/cordova-plugin-googleplus.git --save --variable REVERSED_CLIENT_ID=myreversedclientid

Thanks

**Comment by enzonotario** [comment]
Thanks!!

**Comment by shawns582** [comment]
After signing in and getting a refresh token, has anyone been able to use the refresh token to obtain a new access token?  I have some code that I previously used successfully that is no longer working since I moved from using Oauth.io to using this native plugin.  I am getting 'unauthorized client.' If you have any tips it would be greatly appreciated.  Thanks much.

**Comment by velickym** [comment]
I'm facing the same issue. I think the solution is setting forceCodeForRefreshToken to **true** when calling requestServerAuthCode() on GoogleSignInOptions.Builder (as mentioned by @sachiv-logiciel)

Pull request #419 was created which does the exact thing.

**Comment by Nxtmind** [comment]
@sachiv-logiciel 
Thx bro for the tips, it worked great! Hoping for a fix on the main repo

**Comment by EddyVerbruggen** [comment]
With 5.1.2 you can use the `offline` flag (see the readme) which will not force the refresh (like that code snippet above does).
