### ISSUE TITLE
Error 10 in derived APK

### ISSUE THREAD

**Issue by ansien12** [EddyVerbruggen/cordova-plugin-googleplus#392]
Finished my app, tested it on multiple android devices and everything worked perfectly.

Just submitted my app to the playstore and tried logging in but it keeps giving me an: 'Error 10'.

I've tried re-signing, changing and making new client ID's, rebuilding, everything. It works perfectly in the original APK, but the derived one doesn't.

Using Phonegap with Phonegap build.

**Comment by ansien12** [comment]
So the problem seems to be with Phonegap Build, when i decompile the APK Phonegap build gives me the ./res/xml/config.xml contains:

```
Error decode xml
java.io.IOException: Decode error: Type: 0x104 not yet implemented, position: 0xa2e
	at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:96)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:128)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:88)
	at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:106)
	at jadx.api.ResourcesLoader.access$000(ResourcesLoader.java:25)
	at jadx.api.ResourcesLoader$1.decode(ResourcesLoader.java:89)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:63)
	at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:82)
	at jadx.api.ResourceFile.getContent(ResourceFile.java:52)
	at jadx.api.JadxDecompiler$2.run(JadxDecompiler.java:173)
```

Not sure how to fix this though.

**Comment by ansien12** [comment]
Made a completely new Phonegap project and started over again. Everything works perfectly fine till I try the final/derived build, then it gives: Error 10.

Is there any way i can debug / find out how to fix this?

**Comment by ansien12** [comment]
Did some more debugging (logging the fingerprint) and found out that that the SHA1-hash didn't match the fingerprint in the API console, for anyone that has this issue in the future, error 10 is most likely something hash/fingerprint releated.

![image](https://cloud.githubusercontent.com/assets/1700132/26749460/6b9da01a-480b-11e7-9f34-d8059a5ba266.png)

**Comment by harshrajk** [comment]
Hi @ansien12 , did you find the solution ? I am also having same issue !

**Comment by ansien12** [comment]
@harshrajk Yes, see my latest posts. The fingerprint in your derrived APK doesn't match the one in your Google API console.

**Comment by jeroen79** [comment]
it seems google now resigns the apk's , i fixed it by creating extra credentials with the SHA1 found under: App Signing in the play developer console.

**Comment by amit777** [comment]
@jeroen79 I've been struggling with similar issue. Would you mind clarifying your fix? Do you have two different credential? One for development and one for production?  And for production do you first need to submit the app to the play store before you can get the resigned SHA1?

**Comment by amit777** [comment]
Also is the credential type Android or Web Application? I'm seeing conflicting advise on that. It seems like the android credential type is the only one you can configure a sha1 hash for

**Comment by jeroen79** [comment]
Hi,

you have to use type android!, doesn't even seem to mater that u enter the
id in the app, there just has to be a credential with the new sha1 google
created.

**Comment by Dhfolger** [comment]
so is the current version the original, or derived?
