### ISSUE TITLE
Getting Error: Uncaught (in promise): 10

### ISSUE THREAD

**Issue by pantonis** [EddyVerbruggen/cordova-plugin-googleplus#393]
Hi,

I am using Google plus plugin in Ionic v.3.3.0.

When I run the app in android device and click login, select the gmail account I get the following error.

```Error: Uncaught (in promise): 10```

**Comment by pantonis** [comment]
Managed to resolve it by creating credentials [here](https://console.developers.google.com) of type Web application. This was used when debugging on a device

**Comment by theunreal** [comment]
@pantonis I have credentials there any I still have this error, how did u solve it exactly?

**Comment by pantonis** [comment]
@theunreal What type of credentials do you have. Check the Type column.
