### ISSUE TITLE
Android exception on calling login() and trySilentLogin()

### ISSUE THREAD

**Issue by icedt89** [EddyVerbruggen/cordova-plugin-googleplus#399]
Hi there,

i get the following error when i try to call the login() and trySilentLogin() methods of the GooglePlus object:

> Attempt to invoke virtual method 'android.content.Context com.google.android.gms.common.api.GoogleApiClient.getContext()' on a null object reference

I use Ionic 3.3.0
I build for Android
I have followed all the instructions necessary to setup the plugin

``
 private loginWithGoogle(): void {
        debugger;
        this.googlePlus.login()
            .then(() => {
                debugger;
            })
            .catch(e => {
                debugger;
            });
    }
``

**Comment by jh3141** [comment]
Also seeing this, using cordova directly, not Ionic.

Full dump of messages from logcat:
```
06-27 12:36:14.009 32365 32469 I GooglePlugin: Trying to Log in!
06-27 12:36:14.009 32365 32469 I GooglePlugin: In onActivityResult
06-27 12:36:14.009 32365 32469 I GooglePlugin: This wasn't one of our activities
06-27 12:36:14.105 32365 32469 E PluginManager: Uncaught exception from plugin
06-27 12:36:14.105 32365 32469 E PluginManager: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context com.google.android.gms.common.api.GoogleApiClient.getContext()' on a null object reference
06-27 12:36:14.105 32365 32469 E PluginManager:         at com.google.android.gms.auth.api.signin.internal.zzc.getSignInIntent(Unknown Source)
06-27 12:36:14.105 32365 32469 E PluginManager:         at nl.xservices.plugins.GooglePlus.signIn(GooglePlus.java:165)
06-27 12:36:14.105 32365 32469 E PluginManager:         at nl.xservices.plugins.GooglePlus.execute(GooglePlus.java:70)
06-27 12:36:14.105 32365 32469 E PluginManager:         at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:117)
06-27 12:36:14.105 32365 32469 E PluginManager:         at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
06-27 12:36:14.105 32365 32469 E PluginManager:         at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
06-27 12:36:14.105 32365 32469 E PluginManager:         at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
06-27 12:36:14.105 32365 32469 E PluginManager:         at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
06-27 12:36:14.105 32365 32469 E PluginManager:         at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
06-27 12:36:14.105 32365 32469 E PluginManager:         at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
06-27 12:36:14.105 32365 32469 E PluginManager:         at android.os.Handler.dispatchMessage(Handler.java:111)
06-27 12:36:14.105 32365 32469 E PluginManager:         at android.os.Looper.loop(Looper.java:207)
06-27 12:36:14.105 32365 32469 E PluginManager:         at android.os.HandlerThread.run(HandlerThread.java:61)
```

I previously had this working on another project, but copied the same code to a new project, set up new keys with Google's client key management system, and changed the reverse client ID to the new one provided when I gave google the new keys.

Code I'm using is this:
```
    beginLogin: function () {
        return new Promise ( (resolve, reject) =>
          window.plugins.googleplus.login (
            this.scopes,
            (details) => { this.loggedInDetails = details; resolve (this); },
            (err) => { reject (null);  /* or maybe we should reject (err) ... figure out when to do so. */ })
        );
    },
```

Because everything here *other than* the Android SDK is basically identical to a previously working project, But this app is being built on a system that has an older version of the Android Support Repository (42) than the system that was known to be working (46).  I wonder if this could be the cause...?

**Comment by jh3141** [comment]
Should possibly consider this as a request for better diagnostics ... the fact that an undefined reference causes such a failure is not at all clear from the documentation, as all the fields in that object are described as optional so leaving the entire object out *should* have no effect.  But not passing in an object at all prevents the `mGoogleApiClient` member of the plugin being initialised, which causes the exception quoted above.  Logging a warning and triggering the error handler in `signIn()` and `trySilentLogin()` when `mGoogleApiClient` is null would make it much easier to debug issues like this.
