### ISSUE TITLE
Does this plugin use a non-standard or old Android support jar file?

### ISSUE THREAD

**Issue by andrewb273** [EddyVerbruggen/cordova-plugin-googleplus#40]
I'm having a dependency issue in my Phonegap project, and it seems to be because of this plugin using an old version of the Android support jar. This issue is described in #20, but I can't use that fix as I don't have the luxury of modifying my builds - we're using [Phonegap Build](http://build.phonegap.com). As a summary, there's a dependency discrepancy with `com.phonegap.plugins.facebookconnect`. Project builds fine if I use `com.phonegap.plugins.facebookconnect` v0.4.0, but if I use the latest, I get the dependency issue.

Looking at the code cordova-plugin-googleplus, this line of code at [plugin.xml](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/plugin.xml) ln 32 seems suspect:

```
<dependency id="android.support.v4@21.0.1"
    url="https://github.com/MobileChromeApps/cordova-plugin-android-support-v4" />
```

In comparison, facebookconnect adds it as part of the gradle build in [platforms/android/FacebookLib/build.gradle](https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/android/FacebookLib/build.gradle):

```
dependencies {
    compile 'com.android.support:support-v4:[20,21)'
    compile 'com.parse.bolts:bolts-android:1.1.2'
}
```

I realise these are pretty different approaches. I'm not experienced with Android builds so can't comment knowledgeably - which repo is using the standard approach, and which repo needs to adjust its code to match?

**Comment by EddyVerbruggen** [comment]
v4 has been removed by a recent pull request, I hope this solves this problem as well.
