### ISSUE TITLE
Unable to Install the plugin on IOS - 'GoogleSignIn/GoogleSignIn.h' file not found

### ISSUE THREAD

**Issue by arnoldsi** [EddyVerbruggen/cordova-plugin-googleplus#402]
Hello,
The plugin works great on Android, Great work!

When I'm installing the plugin with this line

cordova plugin add cordova-plugin-googleplus --save --variable REVERSED_CLIENT_ID=HERE I HAVE MY REVERSED_CLIENT_ID

I'm getting next message:
`
cp: dest is not a directory (too many sources)
`

When I run "cordova build ios"  i get next error:

![image](https://user-images.githubusercontent.com/18511197/27517521-a5523fc8-59d6-11e7-9d87-c9c71647787d.png)

**Comment by arnoldsi** [comment]
This probably was permissions issue. It worked on other PC

**Comment by marimuthudm** [comment]
Hi,
I have faced the same issue while building for IOS and Ionic 1.

```
In file included from /ionic/platforms/ios/Kitescafe/Plugins/cordova-plugin-googleplus/GooglePlus.m:3:
/ionic/platforms/ios/Kitescafe/Plugins/cordova-plugin-googleplus/GooglePlus.h:2:9: fatal error: 'GoogleSignIn/GoogleSignIn.h' file not found
#import <GoogleSignIn/GoogleSignIn.h>
```
Any solutions ?

**Comment by josterfeld** [comment]
I'm unable to build my application for IOS and getting the same error.

**Comment by marimuthudm** [comment]
Latest version of cordova-plugin-googleplus facing this issue.

Try old version 4.0.5

`cordova plugin add cordova-plugin-googleplus@4.0.5 --save --variable REVERSED_CLIENT_ID=myreversedclientid`

Its not showing error for Ios. But same version showing error for android
