### ISSUE TITLE
How to install without using the cordova command line tool?

### ISSUE THREAD

**Issue by mzarella** [EddyVerbruggen/cordova-plugin-googleplus#41]
What are the steps to to install the plugin as suggested by the readme?

> "Installing this plugin directly from Cordova Registry results in Xcode using a broken GoogleOpenSource.framework and GooglePlus.framework, this is because the current publish procedure to NPM breaks symlinks CB-6092.Please install the plugin through a locally cloned copy or re-add the frameworks to Xcode after installation."

**Comment by hanamj** [comment]
I was stumped by the same thing last week :)

Do "cordova plugin add org.chromium.identity". When I did it about 10 days ago though, the code there was a bit behind here by a week or two, so to resolve an issue I had that was just fixed I had to copy the code from Github and update the functions in the files myself manually. The plugin registry may be updated now. After doing this and using the right scopes, the functions worked perfectly for me in my Cordova app.

Cheers!

**Comment by alxpereira** [comment]
You have to clone the repo of this plugin somewhere on your machine

```sh
$ git clone https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git
```

Then install it from the clone and not the remote : 
```sh
$ cordova -d plugin add /path/to/clonedrepo
```
