### ISSUE TITLE
[iOS] Error 400, Custom scheme URIs are not allowed for 'WEB' client type

### ISSUE THREAD

**Issue by MaxInMoon** [EddyVerbruggen/cordova-plugin-googleplus#410]
As mentionned [here](https://github.com/EddyVerbruggen/cordova-plugin-googleplus#4-installation-phonegap-cli--cordova-cli), the following paragraphe suggest to install the plugin with the `webClientId`:

> If you are building a hybrid application (iOS and Android), or an Android application, you have to replace myreversedclientid with the reverse value of Client ID in your Release credential generated on step 3, on Google Developer's Console, this will be: "com.googleusercontent.apps.uniqueId", without quotes.

It rises this error when trying to login:
> Custom scheme URIs are not allowed for 'WEB' client type

Do someone can tell if it's possible to share the same key between Android and iOS? Without editing some files manually?

Thanks!

**Comment by iconico** [comment]
I think you're getting confused about the value of `webClientId`. Your code should look like this, and yes this does work on both iOS and Android without changing the `webClientId`.

```
var SCOPES = 'profile email';  // https://developers.google.com/identity/protocols/googlescopes
var webClientId = '123456789012345-qwertyuiopasdfghjkl1234567890';
window.plugins.googleplus.login({
  'scopes': SCOPES,
  'webClientId': webClientId,
  'offline': true
}
```

**Comment by Be4t5** [comment]
Same problem, How did you solve this? I have exactly the code above, but it doesn't work...

**Comment by mrtnkl** [comment]
I had this working but all of a sudden it's throwing this error, without any code changes.

**Comment by jqzhao** [comment]
Same here. all of sudden it's throwing this error on ios without code changes. Looking forward to some insight!

**Comment by animaster** [comment]
I got it works by changing the webClientId and REVERSED_CLIENT_ID to use the one for iOS.

![api 2017-10-06 17-44-40](https://user-images.githubusercontent.com/2392133/31274760-90441f32-aabe-11e7-8554-7da9e7af6809.jpg)

You can obtain the key in [https://console.developers.google.com/apis/credentials](https://console.developers.google.com/apis/credentials) and select your project there.

In order to update / change the `REVERSED_CLIENT_ID` on the Ionic app, we need to remove the plugin first and then add it again with the new `REVERSED_CLIENT_ID`.

```
ionic cordova plugin rm cordova-plugin-googleplus
ionic cordova plugin add cordova-plugin-googleplus --save --variable REVERSED_CLIENT_ID=reversed_ios_client_id
```

When using the login function on the controller, don't forget to change the `webClientId` as well:

```
var iosClientId = '123456789012345-qwertyuiopasdfghjkl1234567890';
window.plugins.googleplus.login({
  'webClientId': iosClientId,
  'offline': true
}
```

I have not tested it on Android device / emulator though, but at least it works on the iOS simulator and my iPhone.

**Comment by jqzhao** [comment]
Changing to ios client ID doesn't work for me. It doesn't complain web client is not allowed but still complain about invalid request. Also we need to build for android but changing to ios client fails the login request on android devices.

**Comment by serdartaylan** [comment]
eklentiyi kurarken ios REVERSED_CLIENT_ID değerine göre kurup
js içinde ise web client değerini kullanınız.
bu durumda ios için sorun oluşmamaktadır.

**Comment by alphapilgrim** [comment]
having the same problem, I tried your @animaster solution. while it doesn't error, the user is not registered in my firebase app. I don't know if you were using firebase, but id appreciate any help.

**Comment by thomc2nf** [comment]
Same error!
Anybody help?

**Comment by thomc2nf** [comment]
I solved my problem:
+ REVERSED_CLIENT_ID is ID for iOS. We need this id to install plugin.
+ webClientId is ID for Web. We need this id to get token.
=> REVERSED_CLIENT_ID  != webClientId.

I don't know why we need 2 IDs?

**Comment by beyond-root-dev** [comment]
I solved this issue by replace the URL_Schemes into Xcode.

Copy the REVERSED_CLIENT_ID from googleserviceInfo.plist file and paste it into info.plist file.

**Comment by mesqueeb** [comment]
For future reference. If you had used the wrong `REVERSED_CLIENT_ID` in the past, you **CANNOT change it by just overwriting the package.json and config.xml**!!

You'll need to remove the plugin and re-add it again with the correct `REVERSED_CLIENT_ID` variable in the install command.
