### ISSUE TITLE
Using plugin with phonegap-plugin-push

### ISSUE THREAD

**Issue by zankevich** [EddyVerbruggen/cordova-plugin-googleplus#411]
I'm using [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) with [cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) and when I try to build IOS project there are errors. Maybe this happens because both plugins using libGTM? How can I resolve this?
![2017-07-14 5 47 22](https://user-images.githubusercontent.com/5199298/28217128-b220dbac-68bc-11e7-8b9e-e72340e1705b.png)
Also I have linker errors in xcode.
![2017-07-14 5 52 38](https://user-images.githubusercontent.com/5199298/28217292-503a859a-68bd-11e7-8981-c6f2af653867.png)
When I building with removing from frameworks all libraries with libGTM..., project builds without errors.
![2017-07-14 5 54 30](https://user-images.githubusercontent.com/5199298/28217353-86c7887e-68bd-11e7-89b4-bab59f8d0a97.png)

**Comment by GeorgeGuja** [comment]
Your problem is also described in this issue. 
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/247
Using this fork: https://github.com/yehiasalam/cordova-plugin-googleplus will solve the problem but unfortunately its not maintained.

**Comment by zankevich** [comment]
@GeorgeGuja Thanks!
