### ISSUE TITLE
Error 10, for some times

### ISSUE THREAD

**Issue by mene078** [EddyVerbruggen/cordova-plugin-googleplus#422]
I got some very weird issue about error 10 because this error appear for sometimes.
This was too strange and I can not found any reason that sometimes the error 10 not appear.

More weird thing is this error mostly happen on the apk from google play store.
Same release apk work fine... but this fine is for sometimes.

Do anybody had this situation? and please guide me some solution about this one.

**Comment by rooz121359** [comment]
I am having the same issue right now and I'm pulling my hair out. I tried everything on other open and closed issues regarding this error 10 and nothing seems to work!

The issue that i have is that the fingerprint in the app is different than the one I used and its in my keystore file!! it just doesn't make sense at all!

I run this CODE to check the fingerprint:

```
window.plugins.googleplus.getSigningCertificateFingerprint(
  function (fingerprint) {
    alert(fingerprint);
  }
);
```
and it gives me this in the alert():

`AC:D3:30:3A:91:BD:53:AA:C8:92:76:35:DD:57:B7:2F:8A:08:D3:07`

But my SHA-1 key that I used is this:

`C6:B9:C7:A7:CE:F3:83:53:BF:EF:C7:4D:54:EF:7C:6F:52:9E:B3:24`



This is getting very annoying now as I cannot find anything that solves this issue.
