### ISSUE TITLE
xap file Confusion problem

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-googleplus#43]
hi @EddyVerbruggen 
I am using PGB 3.7
I found if I install version 1.1.0 (only 1.1.0)
it will occur xap file "Confusion problem"
see my screenshot
http://www.littlebau.com/xap2.jpg

install from "plugins.cordova.io"

**Comment by EddyVerbruggen** [comment]
How is that possible.. The plugin doesn't support wp so this may be a phonegapbuild problem. Can you open an issue with them?

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
thanks for your reply
already post a issue at here
http://community.phonegap.com/nitobi/topics/3rd-plugin-nl-x-services-plugins-googleplus-build-problem-with-pgb-3-7

waiting for PGB's reply...

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I notice that several 3rd plugins (not only yours) also have the same situation (xap file Confusion problem)
so I will close this topic first and ask somebody's help
