### ISSUE TITLE
Is this an active plugin?

### ISSUE THREAD

**Issue by kinesii** [EddyVerbruggen/cordova-plugin-googleplus#434]
Is this an active plugin? There are 200+ issues with very little responses.

**Comment by EddyVerbruggen** [comment]
I see a lot of similar issues almost always turn out to be a usage issue. Not sure what you expect. I hope people will help each other once they figure out what the issue was.

**Comment by francoro** [comment]
@EddyVerbruggen did you know why passing scope:' ' or not passing it at all it doesnt return the imgUrl, i can find a way to return it, also i try passing the scope https://www.googleapis.com/auth/userinfo.profile but it returns the same and also passing others scopes it always return the same. i dont know what to do, Please help
