### ISSUE TITLE
Getting error code 4

### ISSUE THREAD

**Issue by palakt4f** [EddyVerbruggen/cordova-plugin-googleplus#455]
```
window.plugins.googleplus.login(
    {
      {},
      'webClientId': '****************'
      'offline': true,
    },
    function (obj) {
      alert(JSON.stringify(obj));
    },
    function (msg) {
      alert('error: ' + msg); //geeting 4 as msg
    }
);
```

**Comment by haximilian** [comment]
@palakt4f could you please share your solution to this issue? My app was working just fine, and now I'm suddenly getting this error.

**Comment by sung-work** [comment]
@palakt4f what was your solution? I am getting the error for `silentLogin` on Android using version `7.0.2` of this plugin.
