### ISSUE TITLE
ios build fails in 5.2.0 and Xcode 9.2

### ISSUE THREAD

**Issue by deliverymanager** [EddyVerbruggen/cordova-plugin-googleplus#458]
**fatal error: 'GoogleSignIn/GoogleSignIn.h' file not found**

    Node              : v6.11.4
    npm               : 3.10.10 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.2 Build version 9C40b 

It works in 5.1.1 version of the plugin.

**Comment by lrwhiddon** [comment]
I am getting the same.

**Comment by tech-eng** [comment]
having same error

**Comment by tech-eng** [comment]
Please help!!!

**Comment by itanhduy** [comment]
Having same issue. Anyone has fixed this issue?
Duplicate of #459

**Comment by EddyVerbruggen** [comment]
Introduced with #420, reverted in 5.2.1.

**Comment by rcnicke** [comment]
Thanks for the fix, I was ripping my hair out over this!

**Comment by EddyVerbruggen** [comment]
I hope you have some left 💇‍♂️!
