### ISSUE TITLE
'GoogleSignIn/GoogleSignIn.h' file not found

### ISSUE THREAD

**Issue by itanhduy** [EddyVerbruggen/cordova-plugin-googleplus#459]
Hi all,

I've spent almost 2 days for trying to fix this issue. But no luck. 
Finally I decided to post my issue here and I hope I can get help from everyone.

![image](https://user-images.githubusercontent.com/10527554/34703861-ec52dddc-f527-11e7-8915-ce7292457b46.png)
![image](https://user-images.githubusercontent.com/10527554/34703455-9bc5f522-f525-11e7-8806-b009d3cd9008.png)
![image](https://user-images.githubusercontent.com/10527554/34703464-a8b8c4f8-f525-11e7-85ec-1f7056738ae0.png)
![image](https://user-images.githubusercontent.com/10527554/34703471-afd330c0-f525-11e7-8b98-03f3c278fc42.png)
![image](https://user-images.githubusercontent.com/10527554/34703475-b643fa20-f525-11e7-8435-0f9ac956ec16.png)

Am I missing information? Tell me.
Thanks a lot

**Comment by EddyVerbruggen** [comment]
Introduced with #420, reverted in 5.2.1.

**Comment by parliament718** [comment]
This issue is back for me in version 8.2.0. Is there a solution

**Comment by vicatcu** [comment]
@parliament718 did you work around this somehow? @EddyVerbruggen  do you understand what the root cause of this is?
