### ISSUE TITLE
Signed Cert SHA Key for debug apk

### ISSUE THREAD

**Issue by zishor** [EddyVerbruggen/cordova-plugin-googleplus#46]
Probably a very basic question and I am missing something very trivial. 
When you use cordova build android or cordova run android it spits out a normal apk.
Of course I would like to avoid the manually signing of the debug packages. How did you guys get the sha keys for google api developers console for the debug apk's?
Thanks in advance, Frank

**Comment by romanostolosh-devpronet** [comment]
Hi,
here is where you can find the answer http://stackoverflow.com/questions/15727912/sha-1-fingerprint-of-keystore-certificate

it boils down to using command
```keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android```

**Comment by zishor** [comment]
Awesome! Thanks
