### ISSUE TITLE
the problem that apple deny the app.

### ISSUE THREAD

**Issue by roysG** [EddyVerbruggen/cordova-plugin-googleplus#47]
Do you fixed this problem  ?

**Comment by roysG** [comment]
some response ?

**Comment by noizu** [comment]
"the problem that apple deny the app. " on behave of the developers. What is the specific problem. Apply Denied what app.  What were you trying to do. what was the expected outcome. What was the actual outcome.

There is not enough information above for anyone to help you with this issue.

**Comment by EddyVerbruggen** [comment]
I think your question is answered in #37.
