### ISSUE TITLE
Ionic Error

### ISSUE THREAD

**Issue by terencenero** [EddyVerbruggen/cordova-plugin-googleplus#48]
I am using this plugin in Ionic using ng-Cordova 
But it gives me this error:
Unknown provider: $cordovaGooglePlusProvider <- $cordovaGooglePlus

I have included it like this in my controller:
app.controller('SignInCtrl', function($rootScope, $scope, $state, $filter, $ionicPopup, $localStorage, $cordovaOauth, $ionicSideMenuDelegate, $cordovaPush, $cordovaDialogs, $cordovaMedia, $cordovaToast, $cordovaFacebook, $cordovaGooglePlus , HawkUser,Consumer,Subscription,UserDevice,API,ENV)

**Comment by EddyVerbruggen** [comment]
Ehm, AFAIK this plugin is not supported in ngCordova. Do you have a doc/link that says otherwise?

Thx,
Eddy

**Comment by EddyVerbruggen** [comment]
Hi @terencenero it is available since a while now so please try again.

**Comment by terencenero** [comment]
Hi @EddyVerbruggen I have checked it and it is working now.
Thanks

**Comment by Vijay-Bhaskar** [comment]
Hi @terencenero , 

        Am trying to use the plugin and, am getting the same error. Please check the issue. 

Am pasting the error msg from browser(Am running it in device, using browser just for error log) :- 

Error: [$injector:unpr] Unknown provider: $cordovaGooglePlusProvider <- $cordovaGooglePlus <- loginController
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24cordovaGooglePlusProvider%20%3C-%20%24cordovaGooglePlus%20%3C-%20loginController
    at REGEX_STRING_REGEXP (ionic.bundle.js:8762)
    at ionic.bundle.js:12696
    at Object.getService [as get] (ionic.bundle.js:12843)
    at ionic.bundle.js:12701
    at getService (ionic.bundle.js:12843)
    at invoke (ionic.bundle.js:12875)
    at Object.instantiate (ionic.bundle.js:12892)
    at ionic.bundle.js:17161
    at IonicModule.controller.self.appendViewElement (ionic.bundle.js:48253)

**Comment by zigzag-way** [comment]
Can anyone give some kind of instruction on using this plugin with IONIC?
