### ISSUE TITLE
iOS SDK SignIn don't leave app [Apple appstore rejection]

### ISSUE THREAD

**Issue by Moussawi7** [EddyVerbruggen/cordova-plugin-googleplus#49]
Hi @EddyVerbruggen ,
First thanks for this plugin,
According to ***isAvailable*** function to check if googleplus is installed or not which cause Appstore rejection in case of not.
I am currently using [facebook plugin](https://github.com/Wizcorp/phonegap-facebook-plugin) which load facebook on ***inappbrowser*** (in case facebook application is not installed) where the application is never rejected by Apple.
Thank you

**Comment by EddyVerbruggen** [comment]
Correct, Facebook is allowed to do that by Apple. Google is not.
