### ISSUE TITLE
Getting the error 10 - what is it?

### ISSUE THREAD

**Issue by kartagis** [EddyVerbruggen/cordova-plugin-googleplus#495]
I'm trying to make a Cordova app for youtube.upload, getting the consent screen like
[https://www.dropbox.com/s/g1kqzuvyfe512i0/Screenshot_20180516-161939.png?dl=0](url)
and then getting the error 10 and the message "Could not log in". I have no clue what the error is. The code I'm using:
```
document.addEventListener("deviceready", function() {
  window.plugins.googleplus.login(
    {
      'scopes': 'https://www.googleapis.com/auth/youtube.upload',
      'webClientId': 'webclientid'
    },
    function(obj) {
      //onLoginCallback(obj);
      console.log(obj);
    },
    function (msg) {
      console.log(JSON.stringify(msg));
      alert("Could not log in");
    }
  )
});

```
I've installed the plugin with `cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git --variable REVERSED_CLIENT_ID=reversedclientid`

Am I doing something wrong?

**Comment by EddyVerbruggen** [comment]
IDK, but I'm sure you can find something by browing through [all the similar issues](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/search?q=error+10&type=Issues).

**Comment by kartagis** [comment]
I now started getting 7. Is there a concise list of what any of these codes mean?
