### ISSUE TITLE
Finally a more useful error message

### ISSUE THREAD

**Issue by kartagis** [EddyVerbruggen/cordova-plugin-googleplus#500]
Hello,
On Android I've been getting the error 10 and finally it dawned on my to try on iOS. Oddly enough, I got a useful message from iOS, which is `**Error: invalid_client** The OAuth client was not found.`. What is the issue here?

**Comment by Losnen** [comment]
Did u have this?

```    
<plugin name="cordova-plugin-googleplus" spec="^5.3.0">
        <variable name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.[web-application-client-id]" />
</plugin>```

**Comment by kartagis** [comment]
Yes I've got that. As a last resort, I cleared all my oauth2 keys and made a new one, and voila.
