### ISSUE TITLE
iOS Crash in combination with Custom-URL-scheme

### ISSUE THREAD

**Issue by wouterbin** [EddyVerbruggen/cordova-plugin-googleplus#506]
Hi,

I have a problem using the [cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) alongside [Custom-URL-scheme](https://github.com/EddyVerbruggen/Custom-URL-scheme). When the app is called through the scheme defined by Custom-URL-scheme the cordova-plugin-googleplus crashes on GooglePlus.m:66. When attached to Xcode you can see the app crashes on an infinite loop.

Returning false on that line solves the issue, but that is obviously not the right fix. My knowledge of native iOS has reached its limits here. 

To reproduce the issue i made a minimum [app](https://github.com/wouterbin/scheme-issue).

**Comment by wouterbin** [comment]
After some digging the question raised if it is the right choice to use swizzling for application:openURL:options: ?

Would it not be possible/better to listen to the notifications which Cordova sends? [see the code](https://github.com/apache/cordova-ios/blob/077b1dc3c1d72ade9552773ed5a3a4c817800d37/CordovaLib/Classes/Public/CDVAppDelegate.m#L95)

**Comment by gsfioravanti** [comment]
Was there a solution to this issue?

**Comment by wouterbin** [comment]
> Was there a solution to this issue?

Yes see: https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/507
