### ISSUE TITLE
problem with login

### ISSUE THREAD

**Issue by avishayhajbi** [EddyVerbruggen/cordova-plugin-googleplus#53]
hello
i am using phonegap 4.1.2 version
and cordova 4.3.0 version

i'm installed the plugin and create google plus key by following the tutorial.
i got available - true
BUT when i'm trying to login i got : 
 error: failed to retrieve 
 token: unknown

why it happen ? 
thanks a lof

**Comment by AbhilashThomas** [comment]
You have to complete the keytool process.

**Comment by avishayhajbi** [comment]
the problem was the package
