### ISSUE TITLE
Plugin Conflict with cordova-plugin-googlemaps and cordova-plugin-request-location-accuracy

### ISSUE THREAD

**Issue by JonathanKanContracting** [EddyVerbruggen/cordova-plugin-googleplus#540]
it seems that this plugin has a conflict with: 
cordova-plugin-request-location-accuracy
and
cordova-plugin-googlemaps

in Android

when include these two plus this plugin in my config.xml (using Phonegap Build), the app builds, however calling the google plus login call does not have any effect.
removing both 
cordova-plugin-request-location-accuracy
and 
cordova-plugin-googlemaps

plugin then rebuilding, the app builds and the same google plus login action works (opens dialog to choose account in android).

i need the above two plugins for my app so i cannot not use those plugins.

IOS is unaffected, so i'm guessing it's just the Java side for Android that is having issues.

let me know if there is a workaround i can place in my config.xml

thanks,

**Comment by enzonotario** [comment]
Hi! I'm also having problems, but just with `cordova-plugin-googlemaps` and `cordova-plugin-googleplus`

**Comment by JonathanKanContracting** [comment]
I have resolved the issue:
force the PLAY_SERVICES_VERSION for both plugins to 5.0.1, as follows (config.xml)
  <gap:plugin name="cordova-plugin-googlemaps" source="npm" spec="2.3.5">
    <variable name="API_KEY_FOR_ANDROID" value="XXXX" />
    <variable name="API_KEY_FOR_IOS" value="XXXX" />
    <variable name="PLAY_SERVICES_VERSION" value="15.0.1"/>
  </gap:plugin>
  <gap:plugin name="cordova-plugin-googleplus" source="npm">
    <variable name="REVERSED_CLIENT_ID" value="XXXX" />
    <variable name="WEB_APPLICATION_CLIENT_ID" value="XXXXXX" />   
    <variable name="PLAY_SERVICES_VERSION" value="15.0.1"/>
  </gap:plugin> 

make sure the variable name is PLAY_SERVICES_VERSION, not GOOGLE_PLAY_SERVICES_VERSION, as i saw some other forums had...

after this, the next error i ran into with Android, was that the google plus login would show up, i would select an account but would get the error (12500). As per the documentation for the googleplus plugin, it says in the doc: (https://github.com/EddyVerbruggen/cordova-plugin-googleplus#6-usage)

window.plugins.googleplus.login(
    {
      'scopes': '... ', // optional, space-separated list of scopes, If not included or empty, defaults to `profile` and `email`.
      'webClientId': 'client id of the web app/server side', // optional clientId of your Web application from Credentials settings of your project - On Android, this MUST be included to get an idToken. On iOS, it is not required.
      'offline': true // optional, but requires the webClientId - if set to true the plugin will also return a serverAuthCode, which can be used to grant offline access to a non-Google server
    },
    function (obj) {
      alert(JSON.stringify(obj)); // do something useful instead of alerting
    },
    function (msg) {
      alert('error: ' + msg);
    }
);

note the comment for the variable "webClientId", it says "...On Android, this MUST be included to get an idToken...", however whenever i called this, i would ALWAYS get a return code error of 12500. I eventually solved this by doing the **OPPOSITE**: ALWAYS leaving it blank, and it works.

my guess is that when you create your oClient auth key in cloud.google.com, you also specify:
- bundleid (package name of the app)
- SHA1 Fingerprint

so when you call the googleplus services on an android device, it just looks to see if there is a key created for an app that has the above two things, and therefore does not use the ClientID. iOS needs this key, in reverse but defined in the config.xml.

hope that helps
