### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by rubencougil** [EddyVerbruggen/cordova-plugin-googleplus#548]
Hi!

I am facing this issue when running in browser mode. How can I solve this? Would be possible to open this dialog in a new tab instead of an iFrame?

Many thanks for the help!

<img width="1215" alt="screen shot 2018-11-07 at 18 02 03" src="https://user-images.githubusercontent.com/1073799/48147580-f01b1780-e2b7-11e8-87b9-edb167d075b1.png">

Using Ionic with following settings:

```cordova-plugin-googleplus 5.3.2 "Google SignIn"```

```Ionic:

   ionic (Ionic CLI)  : 4.0.5 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.4, ios 4.5.5

System:

   NodeJS : v8.11.3 (/usr/local/bin/node)
   npm    : 5.6.0
   OS     : macOS High Sierra
   Xcode  : Xcode 10.0 Build version 10A255````

**Comment by vicatcu** [comment]
I think that's a problem on the server side, so this plugin _probably_ can't fix it.

**Comment by anthonnyc2** [comment]
Hi guys, I'm facing this problem too. It seems like your plugin is having some conflic with cordova-plugin-inappbrowser. Because after install that plugin I'm getting the error with X-Frame-Options. @EddyVerbruggen can you check what is the problem?

**Comment by rubencougil** [comment]
@vicatcu Thank you for replying. I've already tried that! but problem is the response header seems to come from accounts.google.com domain, not mine. If I open this link in a new tab, it just works. So I guess a _target="blank" or something similar should be enough. But I guess it should be implemented at plugin level.

**Comment by JustasKuizinas** [comment]
Have the same problem. Any updates on this?

**Comment by rubencougil** [comment]
Any update on this?¿

**Comment by rubencougil** [comment]
Ok, so i've been helped in https://stackoverflow.com/questions/53206693/ionic-googleplus-plugin-refused-to-display-in-a-frame-because-it-set-x-frame-o 
The culprit is cordova-plugin-inappbrowser. After uninstalling it, this one works ok in browser.

**Comment by rubencougil** [comment]
@JustasKuizinas no idea. I didn't get it working along with the browser plugin

**Comment by JustasKuizinas** [comment]
@ocsi94 you mean to remove  `<platform name="browser">.......`

**Comment by ocsi94** [comment]
@JustasKuizinas
Under platform browser remove the clobber where contains window.open. You dont have tó remove the platform, if You want to use the plugin

**Comment by JustasKuizinas** [comment]
@ocsi94 I am a bit confused, do you have a specific file in mind from which I have to remove  window.open?

**Comment by ocsi94** [comment]
@JustasKuizinas 
Here is my edited file:
https://pastebin.com/jDLfydmv

**Comment by JustasKuizinas** [comment]
@ocsi94 thanks

**Comment by rromanovsky** [comment]
@JustasKuizinas Did it help you?
I have the same issue and removing of `<clobbers target="window.open" />` from `<platform name="browser">` section didn't change anything

**Comment by ocsi94** [comment]
@rromanovsky
Run the application in browser, open de tool and console and check window.open if its write something like [nativ code] then idk, if its a function then try to rebuild remove add platform etc.
Hope its helps.

**Comment by rromanovsky** [comment]
@ocsi94 I've checked it and It equals to `ƒ open() { [native code] }`:
![screen shot 2019-02-13 at 00 39 23](https://user-images.githubusercontent.com/2143194/52669705-df69e580-2f27-11e9-8b30-52a6fe857fb8.png)

**Comment by ocsi94** [comment]
@rromanovsky
Which plugin you exactly use for instagram?

**Comment by rromanovsky** [comment]
@ocsi94 Looks like I have a weird Instagram login flow which uses the ionic InAppBrowser:
```javascript
login(options) {
      ...
      const browser = this.InAppBrowser.create(
        'https://api.instagram.com/oauth/authorize/?client_id=***&redirect_uri=http://localhost:8000/auth/instagram/callback&response_type=token',
        '_blank',
        browserOptions
      );

      browser.on('loadstart').subscribe(event => {
         if (event.url.indexOf('http://localhost:8000/auth/instagram/callback') === 0) {
           const access_token = event.url.split('access_token=')[1];

           browser.close()

           const spinner = this.loadingCtrl.create({
             content: "Please wait..."
           });

           spinner.present();

           this.http.get(`https://api.instagram.com/v1/users/self/?access_token=${access_token}`, {}, {})
             .then((data) => {
               userData = data;

               return !isLogged ? this.awsService.login('instagram', access_token) : null;
             })
             .then((aws) => {
               const parsedData = JSON.parse(userData.data);

               var payload:any = {
                instagram: Object.assign({}, {
                  access_token: access_token,
                  isInstagram: true,
                  url: parsedData.data.profile_picture
                }, parsedData.data)
              };

              if (aws) {
                payload.aws = aws;
              }

              this.logged = true;

               return this.ss.setUser(payload).then(() => {
                 spinner.dismiss();
                 resolve();
               })
             })
             .catch((error) => {
               spinner.dismiss();
               reject(error);
             });
         }
      });
    })
  }
```
I think I just need to rewrite it with some Instagram plugin...
Thanks for your help!

**Comment by JustasKuizinas** [comment]
@rromanovsky yes it helped me

**Comment by chilipote** [comment]
@rromanovsky, I am actually in the case where I would need some IG login flow also, did you find something for that ? 

I don't find any things on the internet, and for now, and my code is really similar to yours rn

Let me know :)
