### ISSUE TITLE
would this plugin work post google plus shutdown?

### ISSUE THREAD

**Issue by Devi-1989** [EddyVerbruggen/cordova-plugin-googleplus#549]
Hi, I just wanted to understand if I can utilize this plugin for my project. I heard google plus would be shutdown for consumers. Would just the google login make more sense then? Thanks

**Comment by EddyVerbruggen** [comment]
Short answer: it's not affected.

Long answer: when this plugin was created the underlying framework was called "Google Plus". This changed to "Google Sign In" along the way. The plugin was, however, not renamed.

**Comment by Devi-1989** [comment]
Thanks for the quick response !
