### ISSUE TITLE
On Android Error is thrown : FAILED TO RETRIEVE TOKEN

### ISSUE THREAD

**Issue by siddmegadeth** [EddyVerbruggen/cordova-plugin-googleplus#55]
Hi,

while performing google sign in i get an error 
"FAILED TO RETRIEVE TOKEN: UNKNOWN"

Generated SHA1 like below
keytool -genkey -v -keystore test.keystore -alias test -keyalg RSA -validity 10000

keytool -export  -alias test -keystore C:\keytools\test.keystore -list -v

Afterwards got and copied an SHA1 with deep linking enabled
pasted the package="com.test.app" from androidmanifest.xml into package name

I should be able to retrieve the token and an success object. buts its not happening.

my code below is

function googleAuth()
{

 window.plugins.googleplus.login(
    {
      /*'iOSApiKey': '1234567890-abcdefghijklm74bfw.apps.googleusercontent.com'*/
    },
    function (obj) {
      out("Google+ Login : ");
      out(JSON.stringify(obj)); // do something useful instead of alerting
    },
    function (msg) {
      out('Google+ Error : ' + msg);
      window.plugins.googleplus.logout(
    function (msg) 
    {
      out("Logging Off Google+");
      out(msg); // do something useful instead of alerting
    });

      //Dicconnect
      window.plugins.googleplus.disconnect(
    function (msg) {
      out("Disconnecting Google+");
      out(msg); // do something useful instead of alerting
    });

    }
);

where out can be replaced with console.log

Please help. Please suggest where i am getting it wrong

**Comment by siddmegadeth** [comment]
Hi,

I have resolved it. To make it work the apk has to be signed
Please follow ethe below steps to make it work. I have written this from my system .
may be you all can co-relate. Please let me know yr views.



 SHA Keytool :
 Add Reference to PATH for SHA keytool under JDK folder under bin 
 Eg : C:\Program Files\Java\jdk1.8.0_40\bin
 Then To create keystore
 keytool -genkey -v -keystore maptags.keystore -alias maptags -keyalg RSA -keysize 2048 -validity 10000
 After maptags.keystore has been created Run
 keytool -export  -alias maptag -keystore C:\keytools\maptag.keystore -list -v
 place the maptag.keystore under /platform/android/ant-build

The  build your application using cordova
cordova build android --release  switch


The to SIGN the App . Kindly do this if want to run goole/facebook oAuth on android
Add to PATH jarsigner PATH if not added
eg : C:\Program Files\Java\jdk1.8.0_40\bin then in CMD type
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore maptag.keystore MainActivity-release-unsigned.apk maptag
Remember alias has to be same as defined early
MainActivity-release-unsigned.apk is the apk which you have built using cordova  cordova build android --release


AFter jarsigner is complate and no error is thrown then run zipaligner. To use zipaligner add the folwing below path to PATH
remeber zipaligner com with android-sdk and it can be  found under .
C:\Program Files (x86)\Android\android-sdk\build-tools\22.0.1

then RUN or type in CMD
zipalign -v 4 MainActivity-release-unsigned.apk testAppRelease2.apk

where Apk is the recenly build using cordova --release and signed using jarsigner and the last apk is the name to
which u would like to output to

**Comment by SUDHAKHAR** [comment]
done the same but still got the same error failed to receive token

**Comment by getcarpool** [comment]
Hi, this worked for us. Thanks @siddmegadeth 
just to add, we are using the NPM version and not the Git repo
