### ISSUE TITLE
Blank screen after login on iOS

### ISSUE THREAD

**Issue by githubowl** [EddyVerbruggen/cordova-plugin-googleplus#550]
The plugin works for me on my iPhone 6 with ios12 but on my iPad with ios 12 it always returns a blank screen after presenting the google screens. I have run it through debugger on XCode and the presentviewcontroller and dismissviewcontroller functions don't appear to be called. Any tips would be greatly received. Thanks.

**Comment by githubowl** [comment]
I found the problem. I had an old version of the status bar plugin and when I updated it, the problem went away.

**Comment by scottcarter87** [comment]
I have the latest status bar plugin and have this issue.

**Comment by githubowl** [comment]
I had to create a copy of my project with just the login code and all the plugins attached. I then removed the plugins one by one to find the guilty party.
