### ISSUE TITLE
Firebase v1/v2 deprecation

### ISSUE THREAD

**Issue by rbrand21** [EddyVerbruggen/cordova-plugin-googleplus#552]
Does anyone happen to know if this project will be affected by the deprecation of Firebase Auth V1/V2 on December 18th 2018?
Here's a link: https://docs.google.com/document/d/1vpQV8DBQLkIZci7Vh8N4LUHyTkBOsuW5eXE1x8IAqvw/preview

**Comment by mesqueeb** [comment]
This plugin allows you to retrieve a google identity or access token, which you can pass on to firebase authentication if you please. So AFAIK any changes with firebase api's are unrelated to this repository.

**Comment by mesqueeb** [comment]
Closing for now, please feel free to follow up with any comments or suggestions!
