### ISSUE TITLE
Google depcreating google+ sign in.

### ISSUE THREAD

**Issue by asoap** [EddyVerbruggen/cordova-plugin-googleplus#555]
Hey everyone,
I just got this email from google.  IS this plugin going to be updated?  OR is there one that uses Google Sign In instead of Google+ Sign In?  

The email:
Hello Google+ Developer,

We’re writing to let you know that as part of the sunset of the consumer version of Google+, we will be shutting down our Google+ APIs on March 7, 2019. As part of these changes, Google+ Sign-in has been fully deprecated and will also be shut down on March 7, 2019.

What do I need to know?
On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

What do I need to do?
Please update your projects listed below by March 7, 2019 and ensure they are no longer using Google+ APIs. The data below shows which Google+ API methods your projects have recently called.

Note: If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature to the more comprehensive Google Sign-in authentication system.

This is the link they provided to the new API:
https://developers.google.com/identity/

**Comment by dland512** [comment]
Got this email too. How does this affect this project?

**Comment by EddyVerbruggen** [comment]
This project was migrated to the [non-deprecated Google Sign-In framework](https://developers.google.com/identity/) years ago.

**Comment by asoap** [comment]
I did a quick look.  The email specifically mentioned the method "plus.people.get"

I looked at the plugin code, and I see no mention of people.  I also looked at the imports and it looks like it's importing the new API classes, not the google plus stuff.

I then looked at my verification code on my server and found this:.

```
      plus = Google::Apis::PlusV1::PlusService.new
      plus.authorization = token
      this_is_me = plus.get_person('me')
```

So it looks like it's my validation code on my server which is causing the issue.  I'm using rails/google apis gem.  Looks like I have some work to do.

**Comment by EddyVerbruggen** [comment]
Thanks, @asoap, that's much appreciated. I did the same check as you and came to the conclusion I mentioned earlier.

Still, if someone else finds a problem with this plugin please let me know.

**Comment by EddyVerbruggen** [comment]
Reopening for better visibility, also: https://twitter.com/eddyverbruggen/status/1076156113366802433

**Comment by asoap** [comment]
Hmm..  I should add.  Does anyone know of a way to test the code?  Like how Google checked to see if we're using the google plus method?  I'd like to re-run that check to make sure my code is all good to go.

I'm guessing Google does that automatically when we update the app.  But it appears my issue is server side, and not the app.  Anyone have any ideas?

**Comment by danroot** [comment]
In some code where I use this, there is a call to https://www.googleapis.com/plus/v1/people/me that happens _server side_ to get email given a token.  This is NOT part of the cordova-plugin-googleplus code, but separate server API code. In my case, this is part of the AccountController on the ASP.NET app that runs an api for this app, and it looks like it's built into ASP.NET Core's Google auth bits we use as well: https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/Google/src/GoogleDefaults.cs
https://github.com/aspnet/AspNetCore/issues/6069 

If we're sure https://www.googleapis.com/plus/v1/people/me is not referenced in cordova-plugin-googleplus, it may be developers should look more at their APIs/Website code if applicable.

**Comment by smartin015** [comment]
If anyone's looking for a way to verify they're not calling the G+ APIs, you can check with:

`https://console.cloud.google.com/apis/api/plus.googleapis.com/metrics?project=mygoogleprojectname`

Of course, replacing `mygoogleprojectname` with whatever project Google claims to have detected the API usage from.

**Comment by mbellezi** [comment]
> Received an email half an hour ago about it :
> 
> ![capture d ecran de 2019-01-29 18-26-30 1](https://user-images.githubusercontent.com/4408419/51923646-10a8c880-23f4-11e9-8165-f66aa33acb65.jpg)

Receive the same here

**Comment by pascal-bourut** [comment]
Same here, I'm using plugin version 5.2.1.
It puzzles me.

**Comment by mesqueeb** [comment]
We should consider keeping this issue open until people stop asking the same questions.
