### ISSUE TITLE
Google plus api is deprecated 

### ISSUE THREAD

**Issue by regevbr** [EddyVerbruggen/cordova-plugin-googleplus#556]
Google just announced depreciation of all Google plus apis thus we need to change the api calls here...

http://www.google.com/appserve/mkt/p/AEM7UVSA38rSJXgt3wmMtkKUZajxbSkKwCbX7wvyVmKDhd1JBo6wdyVM54GT2kEgpP5SyIeTXBcLivTYCC-GWTWZ_b0V3Jky6AYdM-_eHJYsqA

**Comment by EddyVerbruggen** [comment]
#555
