### ISSUE TITLE
is it work on vue js Cordova?

### ISSUE THREAD

**Issue by izzul-sage** [EddyVerbruggen/cordova-plugin-googleplus#561]
Hello,

is this plugin work on Vue js?

I already tried one but always get error 
"window.plugins.googleplus.login is undefined"

**Comment by mesqueeb** [comment]
This post has way to little information for anyone to help you out.
Are you running in an emulator? Did you do all steps in the readme?

if `window.plugins.googleplus` is undefined it just means you did something wrong installing and setting this app up.

**Comment by izzul-sage** [comment]
yes, i followed all the step given
specifically created for android ver,

Anyway i will retrace back all the step and reported here later on

**Comment by mesqueeb** [comment]
I will close this issue until you are able to identify a clear problem. In that case please open a new issue.
