### ISSUE TITLE
 Google+ Integrations Shutdown

### ISSUE THREAD

**Issue by goverdhanpaliwal** [EddyVerbruggen/cordova-plugin-googleplus#572]
https://developers.google.com/+/integrations-shutdown
will it impact this plugin?
what's the solution for that.

**Comment by fabio998** [comment]
Here the email from Google

> **What do I need to know?**
> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown, with API calls starting to intermittently fail as early as January 28, 2019, and OAuth requests for Google+ scopes starting to intermittently fail as early as February 15, 2019.
> 
> **What do I need to do?**
> Please update your projects listed below by March 7, 2019 and ensure they are no longer using Google+ APIs, or requesting Google+ OAuth scopes. The data below shows which Google+ API methods your projects have recently called, as well as Google+ OAuth scopes it has requested.

How to update with your plugin? Thank you

**Comment by EddyVerbruggen** [comment]
There's a few duplicates in this repo.
