### ISSUE TITLE
Will GooglePlus Shutdown Affect This plugin?

### ISSUE THREAD

**Issue by mkimmet** [EddyVerbruggen/cordova-plugin-googleplus#574]
I got the following email today about the shutdown of google plus, which doesn't seem like a big deal, however, it mentions the discontinuation of OAuth and in particular the "plus.me" scope, so I wanted to check if you happen to know if this plugin will be affected by this shutdown.

===Start Email From Google===
Dear Developer,

Earlier this week we sent you an email related to your projects that will be impacted by the Google+ API shutdown, which **also affects requests for Google+ OAuth scopes.**

The email listed that one or more of your projects are requesting the “plus.me” scope, and would thus be affected. We would like to clarify that only projects directly requesting the “plus.me” scope are affected. This scope may have been listed in some emails, even if not directly requested by your project. We apologize for any confusion caused.

If you are directly requesting the “plus.me” scope, any other Google+ OAuth scopes, or making any Google+ API calls, please ensure that you remove these requests from your project before March 7, 2019.

To see if your project is directly requesting the “plus.me” or any other Google+ OAuth scopes:

If your project is written in Google Apps Script, you can view which scopes your project is requesting by reviewing your project properties in App Script Editor.
If your project is not written in Google Apps Script, please check your code for references to “plus.me” in OAuth scope requests. We recommend that you review projects using any 3rd-party libraries that support sign-in or social functionality, as these may also be affected by the shutdown.
Thanks for being a valued Google+ Developer.

Sincerely,
The Google+ API team

**Comment by EddyVerbruggen** [comment]
Plz search issues before opening a new one.
