### ISSUE TITLE
Plugin is causing Android build to fail on Adobe's web hosted PhoneGap Build

### ISSUE THREAD

**Issue by andrewb273** [EddyVerbruggen/cordova-plugin-googleplus#58]
Also reported here: http://community.phonegap.com/nitobi/topics/google-plugin-is-causing-android-build-to-fail?rfm=1

When I include nl.x-services.plugins.googleplus, Android build fails (iOS succeeds), and I get the following error message:

Error - Plugin error (you probably need to remove plugin files from your app):
Failed to install 'nl.x-services.plugins.googleplus’:
Error: Expected fetched plugin to have ID "com.google.playservices@21.0.0" but got "com.google.playservices@21.0.1”.
at checkID (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/fetch.js:150:15)
at /home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/fetch.js:91:17
at _fulfilled (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:798:54)
at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:827:30)
at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:760:13)
at /home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:574:44
at flush (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:419:13)
Expected fetched plugin to have ID "com.google.playservices@21.0.0" but got "com.google.playservices@21.0.1".

Looks to me like a weakness in the code that has caused an error due to a change on Google or npm's end.

I've tried different versions (1.0.7 seems to be the only supported one), and I've also tried removing the only other possible dependency clash (com.adobe.plugins.gaplugin). I don't have conflicting JS files. It's clearly an issue with nl.x-services.plugins.googleplus.

For now, we've removed Google+ from our app, but definitely hoping to run a successful build with it as soon as we can. Anybody able to assist with this?

Also a little concerned with the version lag between this repo and PhoneGap Build... entirely possible that this has been fixed in more recent repo versions.

**Comment by EddyVerbruggen** [comment]
Hi, see my suggestion in #56

**Comment by andrewb273** [comment]
Yep figured that out. Hoping PGB's plugin page can get updated, as before it was just say 1.0.7 with no source spec, hence my issue.

**Comment by EddyVerbruggen** [comment]
I can't update my plugins at phonegap build anymore because that requires a paid account these days.

**Comment by andrewb273** [comment]
That's odd. You're supporting the PhoneGap build process with free plugins, and they want you to pay. Interesting.

**Comment by EddyVerbruggen** [comment]
It used to be part of their free plan. But indeed it's silly.

Anyway, things have moved to plugins.cordova.io and real soon to npm.

I'm not sure how to let users know that those plugins on pgb are not the latest versions.

**Comment by andrewb273** [comment]
Could remove it from PGB, then they'll briefly freak out and find your instructions on the repo. Also I added a support issue to PHB community, which now has the solution listed.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
just hope one day have a plugins.cordova.io or npm version
thanks

**Comment by EddyVerbruggen** [comment]
It's on npm now.

**Comment by bau720123** [comment]
thanks @EddyVerbruggen 
got it
https://www.npmjs.com/package/cordova-plugin-googleplus

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I try your npm version in PGB 3.7
but build fail (but plugins.cordova.io version is work)

**Comment by sirwoetang** [comment]
I got the build error to stop showing up on PGB 3.7 by changing my XML to 

<gap:plugin name="nl.x-services.plugins.googleplus" source="plugins.cordova.io"/>

Next build will tell me if the Google Login is successful with my login details.
