### ISSUE TITLE
idToken missing on Android

### ISSUE THREAD

**Issue by stianborgesen** [EddyVerbruggen/cordova-plugin-googleplus#59]
I'm sending 'idToken' to my backend for user authentication. It works on iOS, but 'idToken' is not returned on Android device. Is it possible to get it on Android as well?

**Comment by rtomas** [comment]
Add the webApiKey

 window.plugins.googleplus.login(
                    {
                      'iOSApiKey': 'xxxx',
                      'webApiKey': 'xxxx'
                    },

**Comment by gauravgaikwad777** [comment]
Please use Client ID for Web Application
![image](https://cloud.githubusercontent.com/assets/8176450/8237853/eb26aff0-15a6-11e5-8f25-1c0d7743955e.png)

This works.
Thanks @rtomas

**Comment by AdamNowaczyk** [comment]
Hi, I've tried the above and still not getting idToken. What exactly should I use as REVERSED_CLIENT_ID and what as webApiKey?

**Comment by phw** [comment]
@AdamNowaczyk Maybe my answer on #100 helps you

Basically the REVERSED_CLIENT_ID is the one from the iOS oAuth 2.0 client ID (in reversed notation) and the webApiKey is the ID for the web project (which you should use on the server side). The logic is that your app makes an authentication request with it's own client ID, but also requests an access token on behalf of your server.

**Comment by phw** [comment]
@AdamNowaczyk Just read on your other question that you are using Android, so have a look at my answer to #80 for this. Don't use `webApiKey` but the somewhat misnamed `androidApiKey` in that case.

For supporting both platforms I have code that looks something like this:

```JavaScript
if (platform === 'android') {
	params = {
		androidApiKey: GOOGLE_PLUS.CLIENT_ID
	};
}
else {
	params = {
		webApiKey: GOOGLE_PLUS.CLIENT_ID
	};
}

$window.plugins.googleplus.login(params, function(result) {
   //...
});
```

**Comment by AdamNowaczyk** [comment]
@phw I've tried that as well. Used oAuth 2.0 client ID (Android) for REVERSED_CLIENT_ID and web browser client id as webApiKey and I'm getting the error. If I'm not providing the webApiKey, I'm getting oauthToken without problems, but I need idToken as I understand it is Open ID token, right?

**Comment by AdamNowaczyk** [comment]
@phw oh, ok. I didn't know there's androidApiKey option even available :D. I'll try that.

**Comment by phw** [comment]
@AdamNowaczyk Ah, sorry, not sure about the `idToken`. Yes, if you only want to authenticate the user the idToken would be sufficient. And in this case `webApiKey` would be the correct field, but not sure how to set it.

I have only used the `oauthToken`, which is a one time token used by your server to get proper access tokens for offline access. The downside if the user gets asked for the offline access permission, which might be strange if you don't need it :)

**Comment by AdamNowaczyk** [comment]
@phw I need to authenticate in the Cognito with the token I get. However I cannot do that with oauthToken as I'm using multiple clients (native iOS) and in such case Cognito suggest using Open ID token. Just trying different options. I just need native authentication, so I can authenticate in Cognito.
