### ISSUE TITLE
Cordova v9

### ISSUE THREAD

**Issue by mesqueeb** [EddyVerbruggen/cordova-plugin-googleplus#590]
So on 18 March [Cordova v9](https://cordova.apache.org/announcements/2019/03/18/cordova-lib-release-9.0.0.html) was released.

I am afraid to upgrade to Cordova v9, to make sure this plugin does not break. Can anyone confirm if this library is compatible with Cordova v9 and if there's any advice how to upgrade to Cordova v9, let me know! 
Much appreciated 😉

**Comment by SteveKennedy** [comment]
This is true. The plugin will fail installing with Cordova v9.  A bunch of other cordova plugins are experienceing this this issue. It fails with error: 

`Failed to install 'cordova-plugin-googleplus': CordovaError: Using "requireCordovaModule" to load non-cordova module "child_process" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

Most of the time, the issue stems from scripts uing this *sort* of code to import dependencies:

`var childProcess = ctx.requireCordovaModule('child_process');`

And now, need to be changed to something like:

`var childProcess = require('child_process');`

I'm NOT sure this is the right kind of solution, but I suspect it's in-or-around there.

**Comment by meirg** [comment]
I tested SteveKennedy's solution and it worked. Just search and replace "context.requireCordovaModule" with "require", there were only 2 or 3 of them

**Comment by gvhuyssteen** [comment]
Thanks @meirg   I added a PR here.
https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/591

**Comment by EddyVerbruggen** [comment]
Thx - 7.0.1 released to npm.

**Comment by hiepxanh** [comment]
[https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/565](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/565) I think this version not working correctly
