### ISSUE TITLE
Error 10 on release with correct Google App signing SHA1

### ISSUE THREAD

**Issue by KMenant** [EddyVerbruggen/cordova-plugin-googleplus#597]
Hi everyone, sorry for another error 10 issue.. 

I think I followed all the step, I read every post/issues, but it doesn't work ...
The plugin work in debug mode, but when I download the APK from the store, the connection return the error 10.

I don't understand why, because I added the **Debug SHA1**, the **Release/Upload SHA1** and the **Google App Signing SHA1** in the API Console of Google.

Play Console -> Key Management :
![image](https://user-images.githubusercontent.com/12236384/56445938-08c83880-6300-11e9-9c84-2ecb83229e5a.png)

API Console -> ID clients OAuth 2.0 :
![image](https://user-images.githubusercontent.com/12236384/56445699-dec24680-62fe-11e9-8b51-e56a930c3c86.png)

API Console -> ID clients OAuth 2.0 -> Store Client :
![image](https://user-images.githubusercontent.com/12236384/56445864-b4bd5400-62ff-11e9-89e0-2dde30dfae71.png)

**Someone can help me ?
What am I missing ?**

(I put the correct Web Client Id in config.xml, not the Android Client Id)
![image](https://user-images.githubusercontent.com/12236384/56446142-3b266580-6301-11e9-8252-71286e782a21.png)

**Comment by ciroanni** [comment]
hi *,
I have the same issue, in debug mode too...I am sure that I added the sha1 correctly.
could it be a recent issue?
thanks

**Comment by KMenant** [comment]
I solve my problem by **removing the debug ID Client 2.0 and adding it again** on the 
Console Developers ....
