### ISSUE TITLE
In IOS, after login redirection to app not happening

### ISSUE THREAD

**Issue by ksabariraj** [EddyVerbruggen/cordova-plugin-googleplus#600]
Hi,

I can able to login in google. But after login, redirection to app back is not happening. google search page is opening in in safari. I'm getting the below log in xcode.

> FB handle url: com.googleusercontent.apps.998500651283-5gasnyajqCGAtgo3Sq2pnPP4pkcj:/oauth2callback?code=4/PwHDP6nAlyajqC985006512PPWSJw5iuw-TeRFu6CNo475aWWp71985006512cHW1JHiCQrHwSEaFhKGQ0&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile

Could you please help me on this?

Thanks,
Sabari.

**Comment by pietro-stdout** [comment]
me too, why?

**Comment by ksabariraj** [comment]
I don't know :( Need some support on this.

**Comment by sjregan** [comment]
The suggested plugin 'cordova-plugin-facebook4' breaks other plugins that use deep links such as this one.

Use this plugin for Facebook instead: https://github.com/guylando/cordova-plugin-facebook4

**Comment by ksabariraj** [comment]
@sjregan: Thanks. It's working now.

**Comment by vencis** [comment]
This fork works for me
