### ISSUE TITLE
login not redirect to app

### ISSUE THREAD

**Issue by mrpower55** [EddyVerbruggen/cordova-plugin-googleplus#601]
hello there,

i login successfully using google account but it is redirect to google.com not going back to app itself

so please, any one can help on that?

thanks

**Comment by meyerjohan** [comment]
I have the same issue, using it with the facebook plugin seems like there is a conflict. This makes the plugin useless. Any ideas how we can get around that for now @EddyVerbruggen ?

**Comment by phattranky** [comment]
Hi @meyerjohan,

I'm also using facebook plugin, and got same this issue

**Comment by phattranky** [comment]
@mrpower55  @meyerjohan 

I think you guys can downgrade the version to 5.3.2 may fix the problem. Let's check this same issue
```
using 5.3.2 with cordova-plugin-facebook4 (v4.2.1) fixed the problem for me aswell
```

https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/565

**Comment by mrpower55** [comment]
@phattranky thank man you saved my life, it is working now

**Comment by meyerjohan** [comment]
@phattranky Thanks!!
