### ISSUE TITLE
Plugin not working when I inject $cordovaGooglePlus into my controller.

### ISSUE THREAD

**Issue by OSSDeveloper** [EddyVerbruggen/cordova-plugin-googleplus#61]
Hi @EddyVerbruggen ,

    Am trying to use the plugin and, am getting the same error. Please check the issue. 
Am pasting the error msg from browser(Am running it in device, using browser just for error log) :-

Error: [$injector:unpr] Unknown provider: $cordovaGooglePlusProvider <- $cordovaGooglePlus <- loginController
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24cordovaGooglePlusProvider%20%3C-%20%24cordovaGooglePlus%20%3C-%20loginController
at REGEX_STRING_REGEXP (ionic.bundle.js:8762)
at ionic.bundle.js:12696
at Object.getService as get
at ionic.bundle.js:12701
at getService (ionic.bundle.js:12843)
at invoke (ionic.bundle.js:12875)
at Object.instantiate (ionic.bundle.js:12892)
at ionic.bundle.js:17161
at IonicModule.controller.self.appendViewElement (ionic.bundle.js:48253)

And, here is my controller :- 
var loginController = starterApp.controller('loginController', function($scope, $cordovaGooglePlus){
	$cordovaGooglePlus.login().then(function(data){
		alert(data);
	}, function(err){
		alert(err)
	});
});

**Comment by KillerCodeMonkey** [comment]
i think that this has nothing to do with the original plugin.

the issue you created on ngCordova should be enough.
https://github.com/driftyco/ng-cordova/issues/796

**Comment by OSSDeveloper** [comment]
Hi Eddy,

     Greetings. Actually, in ng-cordova
library, ngCordova.plugins.googleplus factory was not injected into
ngCordova.plugins module. I raised a pull request and its merged yesterday.
https://github.com/driftyco/ng-cordova/pull/805

But, even after injecting it, the plugin is not working. Its a bit
embarrassing for me not to be able to do simple google+ authentication(Not
api access but just getting name and email) with ionic. So, was trying
hard.

Shall let you know in case I am able to do it. If you are able to do it in
mobile app, with Ionic, pls let me know.



Thanks and Regards,
Vijaya Bhaskar Puranam.
(91 - 7569625888)

*** Obstacle is an opportunity in disguise ***
