### ISSUE TITLE
Browser after_prepare hook doesn't update CLIENT_ID

### ISSUE THREAD

**Issue by frankie567** [EddyVerbruggen/cordova-plugin-googleplus#617]
The browser `after_prepare` hook is here to insert the `WEB_APPLICATION_CLIENT_ID` value from `config.xml` or CLI arguments into `GooglePlusProxy.js` file.

This works well on the first install but, if you change the value afterwards, the script is not able to replace it again because it always looks for the `WEB_APPLICATION_CLIENT_ID` placeholder.

It is a problem when you have several environments for your app with different client ids.

I'll send a PR in a few minutes to fix this.

**Comment by ryaa** [comment]
There is still a problem with updating CLIENT_ID - see https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/667
