### ISSUE TITLE
PLUGIN IS DEPRECATED: com.google.playservices

### ISSUE THREAD

**Issue by awebdeveloper** [EddyVerbruggen/cordova-plugin-googleplus#62]
What do i do. I get this error

Fetching plugin "https://github.com/MobileChromeApps/google-play-services" via git clone
Installing "com.google.playservices" for android
PLUGIN IS DEPRECATED: com.google.playservices

Plugins should use framework tags instead.

E.g.:
    < framework src="com.google.android.gms:play-services-plus:+" />
    < framework src="com.google.android.gms:play-services-identity:+" />>

Full list available: http://developer.android.com/google/play-services/setup.html

**Comment by EddyVerbruggen** [comment]
Yeah no worries, they deprecated a plugin this one relies on, I will change it eventually.

Thanks for letting me know!

**Comment by KillerCodeMonkey** [comment]
EEEhhhmmmm, but some of us have a little bit "worries" :), because they are using this plugin in production, but can not build their apps in case of that.

Is their any workaround for that issue?
I am using phonegap build and get the following error:

```Error - Plugin error (you probably need to remove plugin files from your app): Failed to install 'nl.x-services.plugins.googleplus':Error: Expected fetched plugin to have ID "com.google.playservices@21.0.0" but got "com.google.playservices@21.0.1". at checkID (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/fetch.js:150:15) at /home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/cordova-lib/src/plugman/fetch.js:91:17 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:798:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:827:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:760:13) at /home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:574:44 at flush (/home/ec2-user/.npm/lib/node_modules/plugman-repo/node_modules/q/q.js:108:17) at process._tickCallback (node.js:442:13) Expected fetched plugin to have ID "com.google.playservices@21.0.0" but got "com.google.playservices@21.0.1".```

**Comment by EddyVerbruggen** [comment]
@KillerCodeMonkey That's a very different problem (an error instead of a deprecation warning). How are you adding the plugin to your project? From this repo directly, plugins.cordova.io, ..?

**Comment by KillerCodeMonkey** [comment]
I am using phonegap build and i added this line to my config.xml
```<gap:plugin name="nl.x-services.plugins.googleplus" />```

And this worked well until last week Oo... I do not know what has changed

I tried to set an explicit versionnumber like 1.0.7 or 1.0.8 with no success... the build failed anyway

**Comment by EddyVerbruggen** [comment]
@KillerCodeMonkey see #56

**Comment by KillerCodeMonkey** [comment]
Thank you very much... adding cordova.io as source helped.

i tried to search your plugin on cordova.io but with no success..
I tried searching for google or nlx and after i searched for google+ -> the "+" causes an endless-loop on the page ... redirecting between http://plugins.cordova.io/#/search?search=google+ and http://plugins.cordova.io/#/search?search=google%2B ^^

**Comment by bau720123** [comment]
hi all
just a +1 vote
I have the same problem with @awebdeveloper when I use cordova 5.0

**Comment by EddyVerbruggen** [comment]
@KillerCodeMonkey yeah that's a nice bug of their website :)

@bau720123 please confirm the plugin still works, it's only a deprecation warning which of course I will look at in the near future.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I will check for once twice
if anything feedback that I will show you，thanks~

**Comment by EddyVerbruggen** [comment]
:+1:

**Comment by EddyVerbruggen** [comment]
Hi guys, can you confirm your Android projects still compile after the change in #63 was merged? It should get rid of this deprecation warning.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
but now it encounter a new problem

all detail at here
http://www.littlebau.com/cli/googleplus_cli4.gif

**Comment by EddyVerbruggen** [comment]
I was afraid of that. Please use a release tag for now.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
well...
cauld you tell me how to use your "release tag"

**Comment by EddyVerbruggen** [comment]
Depends, when using config.xml add a version param. When using the CLI use @<version>. See https://cordova.apache.org/docs/en/4.0.0/guide_cli_index.md.html

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
but now I am already use
```
cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git
```

just like my screenshot said
http://www.littlebau.com/cli/googleplus_cli4.gif

**Comment by EddyVerbruggen** [comment]
You need to add `@<version>` as the doc says

**Comment by raphaelduartepinheiro** [comment]
I'm my case the plugin `nl.x-services.plugins.googleplus` changed the name to `cordova-plugin-googleplus`, that's why the duplications of packages.

I ran the command: `cordova plugin rm nl.x-services.plugins.googleplus`
