### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by Jasonseah** [EddyVerbruggen/cordova-plugin-googleplus#621]
This happens in android, we update the app from debug to release after that the google login is not working and I didn't get and error return from the app, what we get are loading and keep loading non-stop and no error message from the error log either.

We already upload the key to google play console, also update the SHA key to our credential and also double-checked the reverse key, web API client key all are the latest one and it just not working ...

Please help we been looking at the google search and nothing helped us. If anyone got the same issue please point us to the direction that we might miss out.

Thanks.

![Screenshot_20190729_154428_com google android gms](https://user-images.githubusercontent.com/7570733/62031304-9a0d4c00-b219-11e9-8761-0d6d59ab4b62.jpg)

**Comment by Yuripetusko** [comment]
Does your account ends with googlemail.com instead of gmail.com ? if yes then it might be related to this

https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/624

**Comment by Yuripetusko** [comment]
And this

https://stackoverflow.com/questions/57410877/stuck-on-white-screen-when-using-email-ending-on-googlemail-com-instead-of-gmail/57411021#57411021

**Comment by Jasonseah** [comment]
Hi, @Yuripetusko thanks for helping! I actually manage to fix it by change a new OAuth Key. So I think this can be closed.

Btw, we are using @gmail.com.
