### ISSUE TITLE
how to keep session alive till user manually logout

### ISSUE THREAD

**Issue by bhavin9695** [EddyVerbruggen/cordova-plugin-googleplus#623]
I created ionic4 application in which i am trying to backup user data in user's google drive.
for that i implemented google login with google drive scope. but accessToken gets expired after some time.
Application don't have any backend services. so i want to schedule drive backup in my app for that i need to keep google login token alive.
Can we do that using cordova google plus plugin ?
Can someone please add example of how to keep google session alive ?

**Comment by bhavin9695** [comment]
Solved : One can use firebase with google login to keep access_token alive

**Comment by TkStas** [comment]
Faced the same problem. Could you please describe in more detail how you implemented this opportunity to update access_token using firebase? Thanks.

**Comment by bhavin9695** [comment]
First, check how to enable google auth in firebase.

Then, you can use following code to keep token alive and remove when user log out.

`import {Injectable} from '@angular/core';
import {CommonService} from './common.service';
import {StorageService} from './storage.service';
import {GooglePlus} from '@ionic-native/google-plus/ngx';
import {GoogleLogin} from '../model/data.model';
import {File} from '@ionic-native/file/ngx';
import {Constatns} from '../constants/constants';
import {HttpClient, HttpHeaders} from '@angular/common/http';

import * as firebase from 'firebase/app';
import {AngularFireAuth} from '@angular/fire/auth';
import {AdMobService} from './ad-mob.service';

export interface ERROR {
    code: number;
    message: string;
    description?: string;
}

export class ErrorResponse extends Error {

    constructor(public internalApiError?: ERROR, public externalApiError?: any) {
        super();
    }
}

@Injectable({
    providedIn: 'root'
})
export class GoogleAuthService extends CommonService {

    constructor(storageService: StorageService,
                adMobService: AdMobService,
                private googlePlus: GooglePlus,
                private file: File,
                private afAuth: AngularFireAuth,
                private http: HttpClient) {
        super(storageService, adMobService);
    }

    public static ERROR_CODES: { [key: number]: ERROR } = {
        1000: {code: 1000, message: 'Something went wrong.'},
        1001: {code: 1001, message: 'Login error.'},
        1002: {code: 1002, message: 'Firebase login error.'},
        1003: {code: 1003, message: 'Login response update error.'},
        2001: {code: 2001, message: 'Logout error.'},
        2002: {code: 2002, message: 'Firebase logout error.'},
        2003: {code: 2003, message: 'Logout response update error.'},
        3001: {code: 3001, message: 'Backup on device error'},
        3002: {code: 3002, message: 'Backup on google drive error'},
        3003: {code: 3003, message: 'Backup on google drive response update error'},
        4001: {code: 4001, message: 'File search error'},
        4002: {code: 4002, message: 'File not found error'},
        4003: {code: 4003, message: 'File read error'}
    };
    private readonly WEB_CLIENT_ID = '833017-fsa1XXXXXXXXXXXXXXXXXXj8.apps.gooXXXXXXXntent.com';
    private readonly SCOPE = 'profile email https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.file';

    private constants = Constatns;
    private dataDirectory = this.file.externalDataDirectory;


    async tryGoogleSilentLogin(): Promise<any> {
        return await this.googlePlus.trySilentLogin({
            scopes: this.SCOPE,
            webClientId: this.WEB_CLIENT_ID,
            offline: false
        }).then(
            value => {
                return value;
            }, reason => {
                throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
            }
        ).catch(
            reason => {
                throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
            }
        );
    }

    async tryGoogleSilentLoginAndUpdateResponse(): Promise<any> {
        return await this.tryGoogleSilentLogin().then(
            user => {
                return this.updateGoogleLoginToken({
                    name: user.displayName,
                    email: user.email,
                    picture: user.imageUrl,
                    idToken: user.idToken,
                    accessToken: user.accessToken
                }).then(response => {
                    return response;
                }, error => {
                    throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1003], error);
                });
            }
        ).catch(
            reason => {
                throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
            }
        );
    }

    async doGoogleLogout(): Promise<any> {
        return await this.tryGoogleSilentLogin().then(
            value => {
                return this.googlePlus.logout().then(
                    value1 => {
                        return this.afAuth.auth.signOut().then(
                            value2 => {
                                return this.logOut().then(
                                    value3 => {
                                        return value3;
                                    }
                                ).catch(reason => {
                                    throw new ErrorResponse(GoogleAuthService.ERROR_CODES[2003], reason);
                                });
                            }
                        ).catch(
                            reason => {
                                throw new ErrorResponse(GoogleAuthService.ERROR_CODES[2002], reason);
                            }
                        );

                    }
                ).catch(
                    reason => {
                        throw new ErrorResponse(GoogleAuthService.ERROR_CODES[2001], reason);
                    }
                );
            }
        ).catch(
            reason => {
                throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
            }
        );
    }

    async doGoogleLogin(): Promise<any> {
        return await this.googlePlus.login({
            scopes: this.SCOPE,
            webClientId: this.WEB_CLIENT_ID,
            offline: true
        }).then(user => {
            return this.afAuth.auth.signInWithCredential(firebase.auth.GoogleAuthProvider.credential(user.idToken)).then(
                value => {
                    if (value) {
                        user.refreshToken = value.user.refreshToken;
                    }
                    return user;
                }
            ).catch(
                reason => {
                    throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1002], reason);
                }
            );

        }, reason => {
            throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
        });
    }

    async updateGoogleLoginToken(token: GoogleLogin): Promise<GoogleLogin> {
        return await this.updateLoginToken(token);
    }

    getGoogleLoginToken() {
        return this.getLoginToken();
    }
}
`

**Comment by TkStas** [comment]
Thanks. I will study.

  
>Вторник, 3 марта 2020, 11:02 +03:00 от bhavin9695 <notifications@github.com>:
> 
>First, check how to enable google auth in firebase.
>Then, you can use following code to keep token alive and remove when user log out.
>`import {Injectable} from '@angular/core';
>import {CommonService} from './common.service';
>import {StorageService} from './storage.service';
>import {GooglePlus} from '@ionic-native/google-plus/ngx';
>import {GoogleLogin} from '../model/data.model';
>import {File} from '@ionic-native/file/ngx';
>import {Constatns} from '../constants/constants';
>import {HttpClient, HttpHeaders} from '@angular/common/http';
>import * as firebase from 'firebase/app';
>import {AngularFireAuth} from '@angular/fire/auth';
>import {AdMobService} from './ad-mob.service';
>export interface ERROR {
>code: number;
>message: string;
>description?: string;
>}
>export class ErrorResponse extends Error {
>constructor(public internalApiError?: ERROR, public externalApiError?: any) {
>    super();
>}
>
>}
>@Injectable ({
>providedIn: 'root'
>})
>export class GoogleAuthService extends CommonService {
>constructor(storageService: StorageService,
>            adMobService: AdMobService,
>            private googlePlus: GooglePlus,
>            private file: File,
>            private afAuth: AngularFireAuth,
>            private http: HttpClient) {
>    super(storageService, adMobService);
>}
>
>public static ERROR_CODES: { [key: number]: ERROR } = {
>    1000: {code: 1000, message: 'Something went wrong.'},
>    1001: {code: 1001, message: 'Login error.'},
>    1002: {code: 1002, message: 'Firebase login error.'},
>    1003: {code: 1003, message: 'Login response update error.'},
>    2001: {code: 2001, message: 'Logout error.'},
>    2002: {code: 2002, message: 'Firebase logout error.'},
>    2003: {code: 2003, message: 'Logout response update error.'},
>    3001: {code: 3001, message: 'Backup on device error'},
>    3002: {code: 3002, message: 'Backup on google drive error'},
>    3003: {code: 3003, message: 'Backup on google drive response update error'},
>    4001: {code: 4001, message: 'File search error'},
>    4002: {code: 4002, message: 'File not found error'},
>    4003: {code: 4003, message: 'File read error'}
>};
>private readonly WEB_CLIENT_ID = '833017-fsa1XXXXXXXXXXXXXXXXXXj8.apps.gooXXXXXXXntent.com';
>private readonly SCOPE = 'profile email https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.file';
>
>private constants = Constatns;
>private dataDirectory = this.file.externalDataDirectory;
>
>
>async tryGoogleSilentLogin(): Promise<any> {
>    return await this.googlePlus.trySilentLogin({
>        scopes: this.SCOPE,
>        webClientId: this.WEB_CLIENT_ID,
>        offline: false
>    }).then(
>        value => {
>            return value;
>        }, reason => {
>            throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
>        }
>    ).catch(
>        reason => {
>            throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
>        }
>    );
>}
>
>async tryGoogleSilentLoginAndUpdateResponse(): Promise<any> {
>    return await this.tryGoogleSilentLogin().then(
>        user => {
>            return this.updateGoogleLoginToken({
>                name: user.displayName,
>                email: user.email,
>                picture: user.imageUrl,
>                idToken: user.idToken,
>                accessToken: user.accessToken
>            }).then(response => {
>                return response;
>            }, error => {
>                throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1003], error);
>            });
>        }
>    ).catch(
>        reason => {
>            throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
>        }
>    );
>}
>
>async doGoogleLogout(): Promise<any> {
>    return await this.tryGoogleSilentLogin().then(
>        value => {
>            return this.googlePlus.logout().then(
>                value1 => {
>                    return this.afAuth.auth.signOut().then(
>                        value2 => {
>                            return this.logOut().then(
>                                value3 => {
>                                    return value3;
>                                }
>                            ).catch(reason => {
>                                throw new ErrorResponse(GoogleAuthService.ERROR_CODES[2003], reason);
>                            });
>                        }
>                    ).catch(
>                        reason => {
>                            throw new ErrorResponse(GoogleAuthService.ERROR_CODES[2002], reason);
>                        }
>                    );
>
>                }
>            ).catch(
>                reason => {
>                    throw new ErrorResponse(GoogleAuthService.ERROR_CODES[2001], reason);
>                }
>            );
>        }
>    ).catch(
>        reason => {
>            throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
>        }
>    );
>}
>
>async doGoogleLogin(): Promise<any> {
>    return await this.googlePlus.login({
>        scopes: this.SCOPE,
>        webClientId: this.WEB_CLIENT_ID,
>        offline: true
>    }).then(user => {
>        return this.afAuth.auth.signInWithCredential(firebase.auth.GoogleAuthProvider.credential(user.idToken)).then(
>            value => {
>                if (value) {
>                    user.refreshToken = value.user.refreshToken;
>                }
>                return user;
>            }
>        ).catch(
>            reason => {
>                throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1002], reason);
>            }
>        );
>
>    }, reason => {
>        throw new ErrorResponse(GoogleAuthService.ERROR_CODES[1001], reason);
>    });
>}
>
>async updateGoogleLoginToken(token: GoogleLogin): Promise<GoogleLogin> {
>    return await this.updateLoginToken(token);
>}
>
>getGoogleLoginToken() {
>    return this.getLoginToken();
>}
>
>}
>`
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением, 
Станислав Ткачук
