### ISSUE TITLE
Login not working on Android with library v8.0.0

### ISSUE THREAD

**Issue by ghidoz** [EddyVerbruggen/cordova-plugin-googleplus#625]
I was using this fork https://github.com/peterpeterparker/cordova-plugin-googleplus#cocoapods and everything was working fine.

Then suddenly I noticed login stopped working. I updated to use the new v8 version (which integrates the above fork), but still no luck.

I get no error while compiling and no error when calling the login. It just doesn't do anything.

I'm also using those plugins:
- cordova-plugin-firebasex
- cordova-plugin-googlemaps

but everything compiles fine, with no compatibility errors.

This is my config in package.json:
```
"cordova-plugin-googleplus": {
    "REVERSED_CLIENT_ID": "com.googleusercontent.apps.MYID",
    "WEB_APPLICATION_CLIENT_ID": "MYID.apps.googleusercontent.com",
    "PLAY_SERVICES_VERSION": "11.8.0"
}
```

and I also added it to the config.xml:
```
<plugin name="cordova-plugin-googleplus" source="npm">
    <variable name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.MYID" />
    <variable name="WEB_APPLICATION_CLIENT_ID" value="MYID.apps.googleusercontent.com" />
</plugin>
```

I tried either with the Angular wrapper:
```
this.google.login({}).then((response: any) => {
   console.log(response);
}, (err: any) => {
   console.log(err);
});
```

and without:
```
window['plugins'].googleplus.login({
    'webClientId': 'MYID.apps.googleusercontent.com',
}, function (response) {
    console.log(response);
}, function (err) {
    console.log(err);
});
```
but again no luck.

Any ideas? I'm testing it on Android emulator with:
`ionic cordova run android`

I also upgraded to Angular 8 and Ionic 4.7.1, but nothing changed.

Here's my ionic info:
```
Ionic:

   Ionic CLI                     : 5.2.2 (/Users/danieleghidoli/.nvm/versions/node/v8.9.4/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 18 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   Android SDK Tools : 26.1.1 (/Users/danieleghidoli/Library/Android/sdk)
   ios-sim           : 8.0.1
   NodeJS            : v8.9.4 (/Users/danieleghidoli/.nvm/versions/node/v8.9.4/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Comment by ramonvermeulen** [comment]
Having the same issue, either the `then(res => { ... })` nor the `catch(err => { ... })` return anything, it just freezes instead.

**Comment by ghidoz** [comment]
Awesome, it worked Thank you very much!

**Comment by guigons** [comment]
> Having the same issue, neither the `then(res => { ... })` nor the `catch(err => { ... })` return anything, it just freezes instead.
> 
> EDIT:
> 
> **fixed** this by upgrading the play services to version `15.0.1`.
> 
> So edit your config:
> 
> ```
> "cordova-plugin-googleplus": {
>     "REVERSED_CLIENT_ID": "your key here",
>     "WEB_APPLICATION_CLIENT_ID": "your key here",
>     "PLAY_SERVICES_VERSION": "15.0.1"
> }
> ```
> 
> or
> 
> `ionic cordova plugin remove cordova-plugin-googleplus`
> 
> then
> 
> `ionic cordova plugin add cordova-plugin-googleplus --save --variable REVERSED_CLIENT_ID=yourkey --variable WEB_APPLICATION_CLIENT_ID=yourkey --variable PLAY_SERVICES_VERSION=15.0.1`

It is working!! THanks!!!

**Comment by shreejibawa** [comment]
I have following recent versions and doesn't work for me.

### Versions

````
Ionic:

   Ionic CLI                     : 6.2.0 (C:\Users\lenovo\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 6 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : 0.3.0

System:

   NodeJS : v12.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10

Project Properties

target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.google.android.gms:play-services-auth:15.0.1
cordova.system.library.2=com.google.android.gms:play-services-identity:15.0.1
cordova.system.library.3=com.android.support:support-annotations:27.+

PackageJSON

"@ionic-native/google-plus": "^5.23.0",
"cordova-plugin-googleplus": "^8.4.0",

````

### Login code
````
    this.googlePlus.login({}).then(res => {
      console.log(" >>>> ", res);
    }).then(err => {
      console.log(err);
    });
````

No firebase of no angular fire libs are used. This still doesn't work for me. any idea what I might be doin wrong?

**Comment by corncobb** [comment]
@aCodeAlchemist Same here. Works in debug but not in release version. No error code or anything. The popup closes after signing in but doesn't authorize the user in the app
