### ISSUE TITLE
Ionic Native GooglePlus login fails without any error

### ISSUE THREAD

**Issue by jafsab** [EddyVerbruggen/cordova-plugin-googleplus#627]
Hi,

I have ionic 3 project using google plus login, the problem is when I call the this.googlePlus.login({}) method it is not responding, also without any error,

I have set everything in your  documentation, and search allot of issues.

Im using google plus 8.0.0 (tried 7.0.2 also), firebase 2.0.5 plugins
I have set the SHA1 for debug, release and appstore signing in firebase console.
Im using com.google.android.gms:play-services-auth:11.8.0
tried cordova android 7.1.4, and 8.0.0

after all of these it still not responding without error, can you help me please!

**Comment by serdartaylan** [comment]
I'm having the same problem.
couldn't find solution

**Comment by serdartaylan** [comment]
Sample installation:
ionic cordova plugin add cordova-plugin-googleplus --save --variable REVERSED_CLIENT_ID=com.googleusercontent.apps.************* --variable WEB_APPLICATION_CLIENT_ID=*************.apps.googleusercontent.com --variable PLAY_SERVICES_VERSION=15.0.1



sample code : 

var webClientId = '********.apps.googleusercontent.com';
            this.googlePlus.login({
                'webClientId': webClientId,
                'offline': false
            }).then.........

**Comment by jafsab** [comment]
thanks serdartaylan, it works for me also.

**Comment by mike-nelson** [comment]
What was the solution?
