### ISSUE TITLE
How to disable consent screen

### ISSUE THREAD

**Issue by Yuripetusko** [EddyVerbruggen/cordova-plugin-googleplus#629]
Even though this plugin only asks for profile and email scopes i still see consent screen every time, when I check any other android app that uses Google sign in (CityMapper, Booking.com, Pokemon Go) They never show consent screen.

```
By design, the consent screen is not shown in the scenario described (account selection with profile/email scopes).

I'm on the product team at Google and we removed the consent screen (the "Allow/Deny" screen showing the data being shared) in cases where only email and/or profile scopes are requested and the user explicitly selects their Google Account, since the account selection UI already shows the email and profile (name/picture) information that will be shared with the app.
```

https://stackoverflow.com/questions/46328962/oauth-consent-screen-not-showing/46396959#46396959

**Comment by mirko77** [comment]
I have the same issue, did you manage to solve it?

**Comment by Yuripetusko** [comment]
@mirko77 yes, make sure you don't pass offline:true to this plugin

**Comment by mirko77** [comment]
@Yuripetusko but doing that will not give me the `serverAuthCode`

**Comment by Yuripetusko** [comment]
I guess there's no other way @mirko77

**Comment by mirko77** [comment]
Using a previous version we never had this issue. We updated the plugin and now there is the consent screen each time we login...
