### ISSUE TITLE
Failed to install 'cordova-plugin-googleplus': Error: pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by rzy77** [EddyVerbruggen/cordova-plugin-googleplus#632]
### Trying to add cordova platform IOS in ionic fails because of this plugin
```
MacBook-Pro$ ionic cordova platform add ios
> cordova platform add ios
...
Installing "cordova-plugin-googleplus" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-googleplus': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/.../node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
Failed to restore plugin "cordova-plugin-googleplus" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 1
...
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
  In snapshot (Podfile.lock):
    GoogleUtilities/UserDefaults (= 6.2.5, ~> 6.0, ~> 6.2)

  In Podfile:
    GoogleUtilities (= 6.2.3) was resolved to 6.2.3, which depends on
      GoogleUtilities/UserDefaults (= 6.2.3)

Specs satisfying the `GoogleUtilities/UserDefaults (= 6.2.5, ~> 6.0, ~> 6.2), GoogleUtilities/UserDefaults (= 6.2.3)` dependency were found, but they required a higher minimum deployment target.
```

### Environment details:
```
MacBook-Pro$ node -v
v10.12.0
MacBook-Pro$ ionic -v
5.2.3
MacBook-Pro$ cordova -v
9.0.0 (cordova-lib@9.0.1)
```

Please ask me if you need any more details.
Thanks in advance

**Comment by peterpeterparker** [comment]
I just provided a PR to solve this https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/635

Till its merged you could install the plugin from my PR's branch:

```
ionic cordova plugin add https://github.com/peterpeterparker/cordova-plugin-googleplus#optimistic-cocoapods
```

**Comment by rzy77** [comment]
Thanks for the reply.
I could add the platform. I will get back here and tell you if everything else (regarding this matter) worked after I can do proper testing.

**Comment by jasvindersingh-evon** [comment]
> I just provided a PR to solve this #635
> 
> Till its merged you could install the plugin from my PR's branch:
> 
> ```
> ionic cordova plugin add https://github.com/peterpeterparker/cordova-plugin-googleplus#optimistic-cocoapods
> ```

Have you removed the plugin from the repo. I am getting error while adding it 

Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/peterpeterparker/cordova-plugin-googleplus.git
npm ERR! 
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/peterpeterparker/cordova-plugin-googleplus.git/' not found
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jassi/.npm/_logs/2019-09-18T11_40_31_159Z-debug.log
[ERROR] An error occurred while running subprocess cordova.
        
        cordova plugin add https://github.com/peterpeterparker/cordova-plugin-googleplus... exited with exit code 1.

**Comment by peterpeterparker** [comment]
Yes @jasvindersingh-evon as the related PR (https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/635) as been merged and released by @EddyVerbruggen 

You could use the last version of the plugin instead and I think this issue could be closed.

**Comment by jasvindersingh-evon** [comment]
Thanks for reverting back. But I am still getting the same issue with release version 8.1.1.

Command finished with error code 31: pod install,--verbose
Failed to install 'cordova-plugin-googleplus': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Volumes/JS/Office Projects/Ionic/ThirstyBikerFrontEnd/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
pod: Command failed with exit code 31
Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Volumes/JS/Office Projects/Ionic/ThirstyBikerFrontEnd/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)

**Comment by jasvindersingh-evon** [comment]
If I remove the podfile.lock file after adding the plugin and then running the command pod install then it installs the dependencies as below

Installing GoogleSignIn (4.4.0)
Installing GoogleToolboxForMac 2.2.1
Installing GoogleUtilities 6.2.5 (was 6.3.0)

After this I opened the project in Xcode, clean the build. Run the build command again. Now it worked.

**Comment by SlavaEgorov** [comment]
I am still getting the same issue.

**Comment by jmprado** [comment]
Same error here. When this will be fixed please?

**Comment by rzy77** [comment]
> Yes @jasvindersingh-evon as the related PR (#635) as been merged and released by @EddyVerbruggen
> 
> You could use the last version of the plugin instead and I think this issue could be closed.

I'm still getting the same error with this plugin (updated version of course to 8.1.1).

@peterpeterparker I used your plugin and it worked fine. But now I cannot find it anymore.
Did you take it down ?

**Comment by peterpeterparker** [comment]
again, the PR I provided has been merged and released therefore my branch isn't needed anymore and has been deleted

install the last version of the plugin instead

**Comment by rzy77** [comment]
As I said I’ve updated the package and I get the same error. With your branch I did not encounter it. 
I’m using Ionic Appflow so I don’t have any local settings. Everything is cloned and built up on a new VM. 
Any thoughts ? 

Thanks.

**Comment by peterpeterparker** [comment]
maybe trying to install the plugin from GitHub then? or you already tried?

```
ionic cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus
```

I didn't had no other changes in the branch, sorry no other idea

**Comment by jmprado** [comment]
> maybe trying to install the plugin from GitHub then? or you already tried?
> 
> ```
> ionic cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus
> ```
> 
> I didn't had no other changes in the branch, sorry no other idea

I tried that with no success but @jasvindersingh-evon solution works.

Install the plugin for iOS, if it fail go to /platforms/ios and run 

`pod install`

Open xCode and compile/archive your app. Everything will work as expected.

**Comment by rzy77** [comment]
I've made my own fork (changed only plugin.xml):
`<pod name="GoogleUtilities" spec="~> 6.2.3"/>`
to
`<pod name="GoogleUtilities" spec="~> 6.3.0"/>`

It works well now, no more issues.

**Comment by peterpeterparker** [comment]
@rzy77 when I provided the PR my first idea was to use a variable for the POD references, so everybody would be able to specify another version without having to hack around or fork the plugin, but unfortunately that isn't yet possible (see https://github.com/apache/cordova-lib/issues/789)

**Comment by rzy77** [comment]
@peterpeterparker  - that is a very good idea but I had to do this change in order for me to be able to build successfully.

**Comment by SteveKennedy** [comment]
Even with the absolute latest version of this plugin (8.1.1 as of 9/29/2019), and this precise error still occurs.

**Comment by Sevensnake** [comment]
@peterpeterparker  tryied that but still got the error failed to install cordova-plugin-googleplus: undefined.  when ionic cordova platform add ios.

**Comment by Armanio** [comment]
Same problem.
Thx to @rzy77

**Comment by menusha95** [comment]
after working around, I've got a working solution.
All you have to define a google version for this.
`ionic cordova plugin add cordova-plugin-googleplus@5.2.1 --save --variable REVERSED_CLIENT_ID=com.xxxxxx.mobile --variable WEB_APPLICATION_CLIENT_ID=3650100XXXXX-qtr14nvvtbek1bddr152XXXXXXX.apps.googleusercontent.com`

**Comment by hesamr76** [comment]
cordova-plugin-googleplus@8.2.1
Cordova-ios@6.2.1
worked for me

ionic cordova plugin add cordova-plugin-googleplus@8.2.1 --save --variable REVERSED_CLIENT_ID=com.xxxxxx.mobile --variable WEB_APPLICATION_CLIENT_ID=3650100XXXXX-qtr14nvvtbek1bddr152XXXXXXX.apps.googleusercontent.com
