### ISSUE TITLE
'GoogleSignIn/GoogleSignIn.h' file not found - Ionic Hub build

### ISSUE THREAD

**Issue by jkrysakowski** [EddyVerbruggen/cordova-plugin-googleplus#636]
When building my app on Ionic Hub I'm getting an error:

`❌  /Users/ionic/builds/project-0/platforms/ios/Bonzo/Plugins/cordova-plugin-googleplus/GooglePlus.h:2:9: 'GoogleSignIn/GoogleSignIn.h' file not found`

Have anyone a solution for it?

**Comment by jkrysakowski** [comment]
Solution: downgrade cordova-plugin-googleplus to version 7.0.2

**Comment by mmubasher** [comment]
@jkrysakowski  What can be the reason for it to work with 7.0.2 but not 8.x.x ? thanks
