### ISSUE TITLE
Error: Unsupported system library (does not work with gradle)

### ISSUE THREAD

**Issue by danicastanos** [EddyVerbruggen/cordova-plugin-googleplus#64]
Since today, I'm getting this error when building my application:
[exec] Fetching plugin "https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git" via git clone
     [exec] Installing "nl.x-services.plugins.googleplus" for android
     [exec] Failed to install 'nl.x-services.plugins.googleplus':Error: Unsupported system library (does not work with gradle): com.google.android.gms:play-services-plus
     [exec]     at /Users/danicastanos/Documents/koala/app/platforms/android/cordova/lib/build.js:280:31
     [exec]     at Array.forEach (native)
     [exec]     at Object.builders.gradle.prepBuildFiles (/Users/danicastanos/Documents/koala/app/platforms/android/cordova/lib/build.js:266:38)
     [exec]     at Object.module.exports.prepBuildFiles (/Users/danicastanos/Documents/koala/app/platforms/android/cordova/lib/build.js:554:20)
     [exec]     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:567:29
     [exec]     at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
     [exec]     at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
     [exec]     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
     [exec]     at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
     [exec]     at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
     [exec] Error: Unsupported system library (does not work with gradle): com.google.android.gms:play-services-plus
     [exec]     at /Users/danicastanos/Documents/koala/app/platforms/android/cordova/lib/build.js:280:31
     [exec]     at Array.forEach (native)
     [exec]     at Object.builders.gradle.prepBuildFiles (/Users/danicastanos/Documents/koala/app/platforms/android/cordova/lib/build.js:266:38)
     [exec]     at Object.module.exports.prepBuildFiles (/Users/danicastanos/Documents/koala/app/platforms/android/cordova/lib/build.js:554:20)
     [exec]     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:567:29
     [exec]     at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
     [exec]     at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
     [exec]     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
     [exec]     at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
     [exec]     at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)

I am using Cordova 5.0.0 and javac 1.8.0_25

Any clues?

**Comment by EddyVerbruggen** [comment]
Since today this PR #63 has been integrated. I was afraid it would break stuff for some people so I haven't built a release yet. Please use a release instead of the masted (=development) branch to avoid this problem.

**Comment by danicastanos** [comment]
Sorry for this silly question but, how can I set the 1.1.1 release URL in my plugin addition?
I'm currently using: cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git

**Comment by danicastanos** [comment]
Got it!
cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git#1.1.1

But It's still not working:
[exec] Failed to install 'nl.x-services.plugins.googleplus':Error: Expected plugin com.google.playservices to satisfy version "21.0.0" but got "21.0.1".
     [exec]     at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:167:15)
     [exec]     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:148:9
     [exec]     at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
     [exec]     at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
     [exec]     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
     [exec]     at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
     [exec]     at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
     [exec]     at process._tickCallback (node.js:442:13)
     [exec] Error: Expected plugin com.google.playservices to satisfy version "21.0.0" but got "21.0.1".
     [exec]     at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:167:15)
     [exec]     at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:148:9
     [exec]     at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
     [exec]     at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
     [exec]     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
     [exec]     at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
     [exec]     at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
     [exec]     at process._tickCallback (node.js:442:13)

**Comment by pupupu93** [comment]
Okay, here we go. I tried to remove the plugin from my cordova plugin with "cordova plugin rm nl.x-services.plugins.googleplus".

And it gives me a gradle Error:


C:\myMobileApp>cordova plugin rm nl.x-services.plugins.googleplus
Uninstalling nl.x-services.plugins.googleplus from android
Error: Unsupported system library (does not work with gradle): com.google.android.gms:play-services-plus
    at C:\myMobileApp\platforms\android\cordova\lib\build.js:280:31
    at Array.forEach (native)
    at Object.builders.gradle.prepBuildFiles (C:\myMobileApp\platforms\android\cordova\lib\build.js:266:38)
    at Object.module.exports.prepBuildFiles (C:\myMobileApp\platforms\android\cordova\lib\build.js:554:20)
    at C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\uninstall.js:345:29
    at _fulfilled (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Puya\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)

C:\myMobileApp>cordova run android
Running command: C:\myMobileApp\platforms\android\cordova\run.bat
ANDROID_HOME=C:\Users\Puya\AppData\Local\Android\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_40
WARNING : No target specified, deploying to device '4df1fa485359af91'.
C:\myMobileApp\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error: Unsupported system library (does not work with gradle): com.google.android.gms:play-services-plus
    at C:\myMobileApp\platforms\android\cordova\lib\build.js:280:31
    at Array.forEach (native)
    at Object.builders.gradle.prepBuildFiles (C:\myMobileApp\platforms\android\cordova\lib\build.js:266:38)
    at C:\myMobileApp\platforms\android\cordova\lib\build.js:298:29
    at _fulfilled (C:\myMobileApp\platforms\android\cordova\node_modules\q\q.js:798:54)
    at self.promiseDispatch.done (C:\myMobileApp\platforms\android\cordova\node_modules\q\q.js:827:30)
    at Promise.promise.promiseDispatch (C:\myMobileApp\platforms\android\cordova\node_modules\q\q.js:760:13)
    at C:\myMobileApp\platforms\android\cordova\node_modules\q\q.js:526:49
    at flush (C:\myMobileApp\platforms\android\cordova\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:355:11)
ERROR running one or more of the platforms: Error: C:\myMobileApp\platforms\android\cordova\run.bat: Command failed with exit code 1
You may not have the required environment or OS to run this project



How can I uninstall the plugin properly? I am using cordova 5.0.0 CLI without IDE.

**Comment by pupupu93** [comment]
@danicastanos  can you try this? It worked for me (not sure how and why but it worked and now builds successfully):

1) Remove Android Platform from Cordova Project "cordova platform rm android"

2) Remove the Google+ Plugin and google play plugin:
"cordova plugin rm com.google.playservices" and "cordova plugin rm nl.x-services.plugins.googleplus"

3) Install the plugin again with: "cordova plugin add nl.x-services.plugins.googleplus#1.1.1"   (#1.1.1 seems not really matter here because it loads 1.1.2 but still worked for me ")

4) Add android platform again with "cordova platform add android" --> It should work without error but a depreciated warning

5) Try to build. I tried "cordova run android" and it build successfully and opened app on my device.

**Comment by danicastanos** [comment]
HI @pupupu93,

I finally resolved the issue using the plugin repository and not the GitHub URL:
cordova plugin add nl.x-services.plugins.googleplus

Thank you anyway.

**Comment by brutaldev** [comment]
@pupupu93 Thanks for the info but those steps did not work for me. I still get the error when adding the Android platform even when getting the proper release version using `cordova plugin add nl.x-services.plugins.googleplus@1.1.1`

**Comment by macdonst** [comment]
@EddyVerbruggen I've pulled and tested @josschne's PR and it fixes the build issue.

**Comment by josschne** [comment]
Thanks @macdonst

**Comment by EddyVerbruggen** [comment]
Thanks @josschne, @macdonst. Available in 2.0.2.

**Comment by brutaldev** [comment]
Still doesn't work after upgrading to 2.0.2 (after removing old plugin name and old Play service AND Android platform).

`cordova platform rm android`
`cordova plugin rm com.google.playservices`
`cordova plugin rm nl.x-services.plugins.googleplus`
`cordova plugin add cordova-plugin-googleplus `
`cordova platform add android`

After adding the Android platform back I still get the same error (Cordova version 5.1.1):
```
...
Installing "cordova-plugin-googleplus" for android
Failed to install 'cordova-plugin-googleplus':Error: Unsupported system library (does not work with gradle): com.google.
android.gms:play-services-plus
    at S:\Dev\ThumbReview\platforms\android\cordova\lib\build.js:280:31
    at Array.forEach (native)
    at Object.builders.gradle.prepBuildFiles (S:\Dev\ThumbReview\platforms\android\cordova\lib\build.js:266:38)
    at Object.module.exports.prepBuildFiles (S:\Dev\ThumbReview\platforms\android\cordova\lib\build.js:554:20)
    at C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:574:29
    at _fulfilled (C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
Error: Unsupported system library (does not work with gradle): com.google.android.gms:play-services-plus
    at S:\Dev\ThumbReview\platforms\android\cordova\lib\build.js:280:31
    at Array.forEach (native)
    at Object.builders.gradle.prepBuildFiles (S:\Dev\ThumbReview\platforms\android\cordova\lib\build.js:266:38)
    at Object.module.exports.prepBuildFiles (S:\Dev\ThumbReview\platforms\android\cordova\lib\build.js:554:20)
    at C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:574:29
    at _fulfilled (C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
    at C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:509:49
    at flush (C:\Users\Werner\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:108:17)
```

Any advice in overcoming this issue would be greatly appreciated. Looks like I'm going back to 1.1.1...

**Comment by balthier82** [comment]
It gives to me the same error when I install the plugin

**Comment by josschne** [comment]
@brutaldev @balthier82 What version of "Extras/Android Support Repository" and "Extras/Google Repository" do you have installed under the Android SDK Manager?

**Comment by balthier82** [comment]
@balthier82 @brutaldev Android Support Repository is Rev 16 and Google Repository is Rev 19

**Comment by brutaldev** [comment]
@josschne Android Support Repository = 16, Google Repository = 19.
Still using 1.1.1 successfully.

**Comment by madshall** [comment]
Same for me. Android Support Repository = 16, Google Repository = 19, Google Play Services = 25. I'm using `$ cordova plugin add cordova-plugin-googleplus` to install.

**Comment by josschne** [comment]
Ok. I think something went wrong in the release process.  @EddyVerbruggen - Is it possible that the 2.0.2 upload did not include my changes in PR #64?  

When I download the 2.0.2 tgz manually from https://registry.npmjs.org/cordova-plugin-googleplus/-/cordova-plugin-googleplus-2.0.2.tgz, I do not see my changes reflected in plugin.xml.

For the folks who are having difficulties, you can emergency patch this by installing the plugin directly from @EddyVerbruggen 's master branch:

    cordova platform rm android
    cordova plugin rm cordova-plugin-googleplus
    cordova plugin --save add https://github.com/EddyVerbruggen/cordova-plugin-googleplus.git
    cordova platform add android

**Comment by brutaldev** [comment]
@josschne Followed the steps you mentioned including the following commands:
`cordova plugin rm nl.x-services.plugins.googleplus`
`cordova plugin rm com.google.playservices`

Project breaks with a completely different build error now.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:22.0.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/22.0.0/support-v4-22.0.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/22.0.0/support-v4-22.0.0.aar
         file:/C:/Users/Werner/AppData/Local/Android/android-sdk/extras/google/m2repository/com/android/support/support-v4/22.0.0/support-v4-22.0.0.pom
         file:/C:/Users/Werner/AppData/Local/Android/android-sdk/extras/google/m2repository/com/android/support/support-v4/22.0.0/support-v4-22.0.0.aar
     Required by:
         :android:unspecified > com.google.android.gms:play-services-plus:7.5.0 > com.google.android.gms:play-services-b
ase:7.5.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
I have Android Support Library 22.2.1,  Google Play Services 25 and Google Repository 19 installed.

**Comment by brutaldev** [comment]
Needed to install Android Support Repository (v16) for it to build. Again, no luck with new errors this time relating to conflicts with multiple versions of android-support-v4 being included by other plugins:
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  at com.android.dx.command.dexer.Main.run(Main.java:246)
  at com.android.dx.command.dexer.Main.main(Main.java:215)
  at com.android.dx.command.Main.main(Main.java:106)
```

Tried the solutions in this SO answer but they either don't work or makes things worse: http://stackoverflow.com/questions/26342444/multiple-dex-files-define-landroid-support-annotation-animres

Going back to nl.x-services.plugins.googleplus 1.1.1 (which works) until further notice.

**Comment by SandroGrzicic** [comment]
Hi, just stumbled upon this issue when I tried "cordova plugin add cordova-plugin-googleplus", however then I just did "ordova plugin rm cordova-plugin-googleplus" and then "cordova plugin add nl.x-services.plugins.googleplus" and it worked. Thanks for the heads up.

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I have the same problem just like @brutaldev said
2.0.2 still not solve the problem
![gradle](https://cloud.githubusercontent.com/assets/5110085/8762625/003ef268-2db1-11e5-8531-36c4453d83bb.jpg)

**Comment by EddyVerbruggen** [comment]
@bau720123 Can you please try again with the 4.0.0 version I just released to npm?

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
problem solved
thanks

and the "REVERSED_CLIENT_ID" also create successfully by iOS
