### ISSUE TITLE
How to remove this plugin?

### ISSUE THREAD

**Issue by akadebnath** [EddyVerbruggen/cordova-plugin-googleplus#647]
I want to install different version, but can't remove this plugin. I tried:

> cordova plugin remove cordova-plugin-googleplus
> Variable(s) missing: WEB_APPLICATION_CLIENT_ID

Also

> cordova plugin remove cordova-plugin-googleplus --variable WEB_APPLICATION_CLIENT_ID=myapplicationid.apps.googleusercontent.com
> Uninstalling cordova-plugin-googleplus from browser
> js-module uninstall called : plugins/cordova-plugin-googleplus/www/GooglePlus.js
> js-module uninstall called : plugins/cordova-plugin-googleplus/src/browser/GooglePlusProxy.js
> Variable(s) missing: REVERSED_CLIENT_ID

Also

> cordova plugin remove cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=com.googleusercontent.apps.myapplicationid
> Variable(s) missing: WEB_APPLICATION_CLIENT_ID

Also

> cordova plugin remove cordova-plugin-googleplus --variable WEB_APPLICATION_CLIENT_ID=myapplicationid.apps.googleusercontent.com --variable REVERSED_CLIENT_ID=com.googleusercontent.apps.myapplicationid
> Uninstalling cordova-plugin-googleplus from browser
> js-module uninstall called : plugins/cordova-plugin-googleplus/www/GooglePlus.js
> js-module uninstall called : plugins/cordova-plugin-googleplus/src/browser/GooglePlusProxy.js
> Variable(s) missing: REVERSED_CLIENT_ID

Also

> cordova plugin remove cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=com.googleusercontent.apps.myapplicationid --variable WEB_APPLICATION_CLIENT_ID=myapplicationid.apps.googleusercontent.com
> Uninstalling cordova-plugin-googleplus from browser
> js-module uninstall called : plugins/cordova-plugin-googleplus/www/GooglePlus.js
> js-module uninstall called : plugins/cordova-plugin-googleplus/src/browser/GooglePlusProxy.js
> Variable(s) missing: REVERSED_CLIENT_ID

**Comment by Zvika88** [comment]
copy the exact same string you used to install the plugin, just replacing "add" with "rm" . Make sure that all other parameters are in place. Note that any variable used in the "add" operation needs to be used, with the same settings, also by the "rm" operation or else parsing fails. Works for me.

**Comment by akadebnath** [comment]
Ahh.. okay. All the time I was trying with "remove" and not "rm". Thank you.

**Comment by revathikrishnan** [comment]
im also facing same issue i have tried both "remove" and "rm" comment but all the time its showing Variable(s) missing: REVERSED_CLIENT_ID

**Comment by epetre** [comment]
Same issue for me.

**Comment by sjregan** [comment]
I have the same issue, I have been able to uninstall the plugin by:

1. Edited `plugins/cordova-plugin-googlepls/plugin.xml`
2. Deleted line containing the `REVERSED_CLIENT_ID` preference in the `ios` section
3. Save file
4. Ran `cordova plugin rm cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myreversedclientid --variable WEB_APPLICATION_CLIENT_ID=mywebapplicationclientid`

**Comment by revathikrishnan** [comment]
Hi,
 Thanks for your reply. But one more issue is raising which  is unavailable
mac analyst while build the application in ios platform. How to sort out
this issue and made successfull login in device.
