### ISSUE TITLE
Plugin invalidates other plugins' entitlements (iOS)

### ISSUE THREAD

**Issue by hoi4** [EddyVerbruggen/cordova-plugin-googleplus#650]
After upgrading from 7.0.2 to the latest version 8.1.1, this plugin invalidates entitlements of other plugins.
All plugins correctly write their entitlements into `platforms/ios/ProjectName/Entitlements-Debug.plist` and `platforms/ios/ProjectName/Entitlements-Release.plist` respectively.

But Xcode (using latest version 11.1) does not show all entitlements from `Entitlements-Debug.plist`. Instead Xcode uses the `ProjectName.entitlements`-file that is created in the `install_entitlements.js`-hook.

**Comment by pghoratiu** [comment]
Created PR#652 to resolve this issue, not sure if it breaks other functionality (older XCode version, ...).

**Comment by smalluban** [comment]
PR is merged, so this issue might be closed.
