### ISSUE TITLE
Google auth stuck on loading spinner after account select on Ionic 4

### ISSUE THREAD

**Issue by harry-gordon** [EddyVerbruggen/cordova-plugin-googleplus#655]
I'm trying to work through this tutorial for setting up Google sign-in with Ionic 4 (https://medium.com/enappd/implement-google-login-in-ionic-4-apps-using-firebase-57334bad0910) and it seems to mostly work but gets stuck on the loading spinner after I choose my Google account (see images below).

I've been around the houses and I'm happy that everything is configured correctly. I checked logcat and haven't seen anything too unusual, apart from this memory error from Chromium:
```
chromium: [ERROR:tile_manager.cc(779)] WARNING: tile memory limits exceeded, some content may not draw
```
Here is a [full log](https://gist.github.com/harry-gordon/979bcaa64e133a0fe77e1e4391b91c18).

Any ideas?

![select](https://user-images.githubusercontent.com/28703576/67090257-8d0d5280-f1a1-11e9-83fc-6573e390e4dc.png)
![spinner](https://user-images.githubusercontent.com/28703576/67090261-8e3e7f80-f1a1-11e9-8bd9-4f322b174405.png)

**Comment by salcott** [comment]
Same issue here, Ionic 3. I received a 1-star Google Play Store app review for this.  I can't seem to find a fix after a day of debugging so I'm removing the feature for my android users!

**Comment by mirko77** [comment]
Maybe related to #659

**Comment by harry-gordon** [comment]
@mirko77 sounds like the same issue I'm experiencing, glad it's not just me!

**Comment by ofermisk** [comment]
I am facing the same issue.
Checked my web client id, it is the right one.
Ionic:

   ionic (Ionic CLI)             : 4.9.0 (C:\Users\Asus\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.4
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Capacitor:

   capacitor (Capacitor CLI) : 1.3.0
   @capacitor/core           : 1.3.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

System:

   Android SDK Tools : 26.1.1 (E:\AndroidSDK)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10

**Comment by grumpygary** [comment]
I believe that many of the issues listed, such as this one, are the result of "progress".  By that I mean that the plugin worked fine when originally built, but over time various library version references have made it incompatible (it won't build on iOS, throws an error on android).  The author will need to upgrade to more recent references (cdv-CLI 9, cdv-iOS 5.1.0, android 8.1.0), as well as making sure it plays well with other google plugins.  Since he is doing this on his own, we can only wait... (I'm not qualified to make the changes or I would).

**Comment by marcoacevey** [comment]
mee to stuck on that, only on ios.

**Comment by vivek365** [comment]
Hey Guys, anyone found the solution for this? I am facing the same issue.

**Comment by harry-gordon** [comment]
Posted this many moons ago and I'm actually no longer working with the Cordova plugin. I ran into the same issue on the Flutter Google Sign In plugin last week and the issue was the consent configuration - after I added myself as a test user it worked fine.

@vivek365 if you can try that we can probably close the issue?

**Comment by vivek365** [comment]
@harry-gordon thanks man. It works.

**Comment by ArnaudFelixParis** [comment]
> Posted this many moons ago and I'm actually no longer working with the Cordova plugin. I ran into the same issue on the Flutter Google Sign In plugin last week and the issue was the consent configuration - after I added myself as a test user it worked fine.
> 
> @vivek365 if you can try that we can probably close the issue?
> 
> P.S: this only applies if your app is in "Testing" mode.

Une save me dude ! Thank's a lot

**Comment by ArnaudFelixParis** [comment]
> Posted this many moons ago and I'm actually no longer working with the Cordova plugin. I ran into the same issue on the Flutter Google Sign In plugin last week and the issue was the consent configuration - after I added myself as a test user it worked fine.
> 
> @vivek365 if you can try that we can probably close the issue?
> 
> P.S: this only applies if your app is in "Testing" mode.

You saved me dude ! Thank's a lot

**Comment by daveyleo** [comment]
@harry-gordon I am having the same issue, but I don't understand what you mean by "consent configuration"  where is this consent configuration?  In Firebase?  Where?  I am unable to find it. Please help point me in the right direction, I would greatly appreciate it.

**Comment by harry-gordon** [comment]
> @harry-gordon I am having the same issue, but I don't understand what you mean by "consent configuration" where is this consent configuration? In Firebase? Where? I am unable to find it. Please help point me in the right direction, I would greatly appreciate it.

@daveyleo I believe it was the "OAuth consent screen" config in the [Google Cloud Platform console](https://console.cloud.google.com/apis/dashboard)?

**Comment by ssrazeen** [comment]
> Posted this many moons ago and I'm actually no longer working with the Cordova plugin. I ran into the same issue on the Flutter Google Sign In plugin last week and the issue was the consent configuration - after I added myself as a test user it worked fine.
> 
> @vivek365 if you can try that we can probably close the issue?
> 
> P.S: this only applies if your app is in "Testing" mode.

I changed my app status from testing to publish in OAuth consent screen of google console. Now its  Working fine..
