### ISSUE TITLE
PLUGIN IS DEPRECATED: com.google.playservices 

### ISSUE THREAD

**Issue by cordova-android** [EddyVerbruggen/cordova-plugin-googleplus#66]
ihave issue in install this plugin in cordova
to install plugin "https://github.com/MobileChromeApps/google-play-services" via git clone
Installing "com.google.playservices" for android
PLUGIN IS DEPRECATED: com.google.playservices

Plugins should use framework tags instead.

E.g.:
< framework src="com.google.android.gms:play-services-plus:+" />
< framework src="com.google.android.gms:play-services-identity:+" />>

Full list available: http://developer.android.com/google/play-services/setup.html

how i can solve this problem??

**Comment by EddyVerbruggen** [comment]
Please see #65

**Comment by cordova-android** [comment]
Now this issue solved but when i run it and click login
i have alert('error:service not available');

**Comment by EddyVerbruggen** [comment]
Please update to the latest (just released) 4.0.0 version.
