### ISSUE TITLE
401 Error: invalid_client 

### ISSUE THREAD

**Issue by nitish75** [EddyVerbruggen/cordova-plugin-googleplus#665]
hi @EddyVerbruggen @habibillah 
i am developing a hybrid app for android and ios. able to generate all the keys like REVERSED_CLIENT_ID and WEB_APPLICATION_CLIENT_ID.

i am using 
```
"cordova-plugin-googleplus": "8.1.2"
"@ionic-native/google-plus": "^4.20.0",
"cordova-plugin-googleplus": {
  "REVERSED_CLIENT_ID": "apps.googleusercontent.com.464576266155-o2cmpejeu0bnqmtkjifm2l*******adra",
  "WEB_APPLICATION_CLIENT_ID": "464576266155-9cl4nip5hc49l9*******7kl79r1hg77.apps.googleusercontent.com",
  "PLAY_SERVICES_VERSION": "15.0.1"
}

doGooglelogin() {
    console.log('function called');
    this.googlePlus.login({
      'webClientId': '464576266155-9cl4nip5hc********g77.apps.googleusercontent.com', 
      'offline': true
    })
      .then(user => {
        console.log('user', user);
      }, err => {
        console.log('error', err)
      });
  }
```

In android it is working fine but in ios it is giving me below error(pic 1) in app and in safari console i am getting error pic 2.
![Screenshot 2019-12-26 at 1 21 06 PM](https://user-images.githubusercontent.com/43879303/71465449-ab677e00-27e2-11ea-9445-62ecb6e5ef17.png)

![IMG_0106](https://user-images.githubusercontent.com/43879303/71465349-62afc500-27e2-11ea-8f55-3e1a9b1de926.PNG)
error

Please have a look into it, i am stucked from 2-3 days i tried many things like changed REVERSED_CLIENT_ID  with many keys but all goes in vain.
Thanks in advance.

**Comment by salcedobrain** [comment]
Hello @nitish75, I had the same issue. I did the following steps:

1.- Remove cordova-plugin-googleplus
2.- Remove platforms (Android and iOS)
3.- Reinstall both.

Maybe the first attempt to install cordova-plugin-googleplus you put wrong values and these values are saved and I tried to change the values only into package.json (it was what I did).

You have to install the plugin with the correct values.

I hope to help you.

Best regards.

**Comment by nitish75** [comment]
Hi @salcedobrain, 
thanks for the response.
I tried the things with your steps but got same issue.

**Comment by salcedobrain** [comment]
@nitish75 are you getting the values correctly? You can get your REVERSED_CLIENT_ID from plist file and WEB_APPLICATION_CLIENT_ID from google-services.json, additionally, you have to use the values according to debug or release environment.

**Comment by nitish75** [comment]
@bjdose i think i followed the wrong steps to generate REVERSED_CLIENT_ID can you please send me the steps you followed to generate your REVERSED_CLIENT_ID. It will be helpful for me.

**Comment by russcarver** [comment]
For me, I didn't have to reinstall the plugin, just change the `REVERSED_CLIENT_ID` values for the plugin in both `package.json` and `config.xml`.
