### ISSUE TITLE
Android Build Failing

### ISSUE THREAD

**Issue by RustyGumbo** [EddyVerbruggen/cordova-plugin-googleplus#67]
I get the following error since today:

<code>
Error - Plugin error (you probably need to remove plugin files from your app): Failed to install 'nl.x-services.plugins.googleplus':Error: Expected plugin com.google.playservices to satisfy version "21.0.0" but got "21.0.1". at checkID (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/fetch.js:167:15) at /home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/fetch.js:148:9 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:749:13) at /home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:557:44 at flush (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:108:17) at process._tickCallback (node.js:442:13) Expected plugin com.google.playservices to satisfy version "21.0.0" but got "21.0.1"
</code>

How can I fix this?

**Comment by EddyVerbruggen** [comment]
Please see #58

**Comment by RustyGumbo** [comment]
It didn't work, possibly an error on PGB's side and I didn't want to use cordova.io since it will be deprecated :(

**Comment by EddyVerbruggen** [comment]
Please use cordova.io, it will be available for a few months to come. In the meanwhile I will move this plugin to NPM shortly.

**Comment by EddyVerbruggen** [comment]
It's on npm now.
