### ISSUE TITLE
Googleplus 8.4.0 build error for iOS, and 7.0.2 build issue in uiwebview

### ISSUE THREAD

**Issue by iamtarun1993** [EddyVerbruggen/cordova-plugin-googleplus#688]
Is there any way to fix UIWEBVIEW issue in 7.0.2 ???

**Comment by iamtarun1993** [comment]
@leogoesger I saw you fixed UIWEBVIEW issue in 8.4.0. 
Can you tell me what I need to update to make the same fix in 7.0.2 ?
I tried with your fix in this [PR](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/671/commits/7ec9f893d581002609136348f620b03a62c87502) but this is not helping.

**Comment by pjain168** [comment]
@iamtarun1993 I am facing similar issue, have you got any solution for this.

**Comment by iamtarun1993** [comment]
yes, you need to use Cordova 9.0.0 and Cordova-iOS 5.1.1.
Maybe you will get some issue when building for iOS first time for Cocoapods pods creation. To solve this.
1. Remove google-plus plugin via terminal.
2. Add the same plugin via terminal.

this will resolve cocoapods issue.
