### ISSUE TITLE
Consent screen presents every time with login (Ionic)

### ISSUE THREAD

**Issue by samit-s3752136** [EddyVerbruggen/cordova-plugin-googleplus#689]
Hi, I've been working with this plugin for the past 2 years. Recently I noticed that the consent screen is presented everytime, even if the permissions have been given. In the first attempt it will ask to allow. However in the second attempt to login, it displays that the account has already given permissions but is still asking to give
![Screen Shot 2020-04-10 at 2 02 31 pm](https://user-images.githubusercontent.com/62533583/78961307-5acb2500-7b34-11ea-8354-8a458e10690f.png)

**Comment by AleCat83** [comment]
I have the same issue. Using "trySilentLogin()" instead "login()" seems to work for me. I don't understand what has changed to cause the issue since I am using this plugin from more than 1 year and I've never experienced the problem.

**Comment by samit-s3752136** [comment]
@AleCat83 sorry I never got back to this but I figured it out. There isn't an issue with the plugin. It's rather the Params. Make sure `'offline': false`. It shouldn't pop up after the first time you give permission
