### ISSUE TITLE
First time: No callback when trying to get oauthToken

### ISSUE THREAD

**Issue by Moussawi7** [EddyVerbruggen/cordova-plugin-googleplus#69]
Dear,
The plugin work excellent with me except one thing.
First time I try to authenticate the app. no callback fired(success/error). so i have to call the login function again to get the response.
```javascript
 window.plugins.googleplus.login({"iOSApiKey": "XXX",
            "androidApiKey": "XXX"},
        function (response) {
            callback.call(context, response);
        }, function () {
            callback.call(context, false);
        });
```

**Comment by EddyVerbruggen** [comment]
iOS or Android?
Btw, please retry this with 4.0.1 since it has significantly changed since your bugreport.

**Comment by Moussawi7** [comment]
Hi @EddyVerbruggen ,
The issue was on Android devices.
Thanks.
