### ISSUE TITLE
Failed to retrieve token: unknown 

### ISSUE THREAD

**Issue by SudarshN** [EddyVerbruggen/cordova-plugin-googleplus#73]
I have followed all the steps mentioned in the documentation, But i am not able to login it says, Failed to retrieve token. Please help me on this.

**Comment by trinhvanhuy** [comment]
Any help ? i have same issue here :'( :'(

**Comment by Xeaphii** [comment]
I got same issue as well

**Comment by ang1217** [comment]
TIVE o mesmo problema meu erro foi:
assinei o .apk e coloquei a chave sh1 do apk assinado como cliente da api do google.
Na hr de testar executei cordova run android pelo prompt mas esse comando não instala o .apk assinado  e sim o que usa a ch de debug(por padrão android-debug.apk). Então instalei o .apk que assinei e funcionou. 
ou seja pra testar pelo prompt gere a chave sh1 de debug na api do google.

espero que ajude.

**Comment by ang1217** [comment]
TIVE o mesmo problema meu erro foi:
assinei o .apk e coloquei a chave sh1 do apk assinado como cliente da api do google.
Na hr de testar executei cordova run android pelo prompt mas esse comando não instala o .apk assinado  e sim o que usa a ch de debug(por padrão android-debug.apk). Então instalei o .apk que assinei e funcionou. 
ou seja pra testar pelo prompt gere a chave sh1 de debug na api do google.

espero que ajude.

**Comment by Xeaphii** [comment]
I have resolved this issue by debugging that library. I will push to that if admin of that library allows me.

**Comment by hgoebl** [comment]
@Xeaphii the normal way is to fork the repo, push to your fork and create a pull request.

**Comment by phw** [comment]
Duplicate of #28

**Comment by jorgejeferson** [comment]
Pessoal, tive esse problema mesmo problema, porém no meu caso foi:
Como eu tinha gerado a SH1 na chamada da função deve-se remover o parametro `webApiKey`
Pronto tudo lindo...

**Comment by emanuelvictor** [comment]
Quer dizer então que devo colocar algo como 'webApiKey' : ''DE:D8:46:1A:1D:F9:F4:6C:68:7E:A8:45:12:E6:E4:F8:E3:8B:37:D3' como parâmetros?
