### ISSUE TITLE
error 10 on oauth

### ISSUE THREAD

**Issue by alfacool** [EddyVerbruggen/cordova-plugin-googleplus#745]
just checking is this plugin still usable? because when creating the credentials theres no option for google plus api even after i enable the api,, tried to use oauth but keep geting error 10

**Comment by alfacool** [comment]
nevermind its on my --buildConfig,, the plugin still works

**Comment by purelydeft** [comment]
Hello @alfacool ,
How did you fix these issues?

**Comment by alfacool** [comment]
@purelydeft honestly i kinda forgot,,, i think i did 2 solutions

1. was to create a build.cordova.json and include it on build cli by using command -- --buildConfig="../build.cordova.json"
2. was to register debug key from keystore to google devs
