### ISSUE TITLE
Google plus token information not clear with use of logout and disconnect function in given plugin.

### ISSUE THREAD

**Issue by TestingFlair** [EddyVerbruggen/cordova-plugin-googleplus#75]
Hello,

I have used this plugin in my app for google plus login that is done.

But while i am using logout and disconnect function it gives correct response but logout is not done.

It is not clearing user token information.

Thanks in advance.

**Comment by EddyVerbruggen** [comment]
Can you please try again with the 4.0.1 version and reopen this issue (and a bit of code) if it's still a problem?
