### ISSUE TITLE
Could not find any version that matches com.google.android.gms:play-services-plus:+.

### ISSUE THREAD

**Issue by mitchmyburgh** [EddyVerbruggen/cordova-plugin-googleplus#77]
When building a cordova project to which i have added the plugin via:

```
$ cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus
$ cordova prepare
```

I get the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-plus:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-plus/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-plus/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.google.android.gms:play-services-identity:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-identity/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-identity/
     Required by:
         :android:unspecified
```

**Comment by josschne** [comment]
@mitchmyburgh What version of "Extras/Android Support Repository" and "Extras/Google Repository" do you have installed under the Android SDK Manager?

**Comment by Dineshrajaa** [comment]
I am facing the same issue now here are the details
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-plus:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-plus/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-plus/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.google.android.gms:play-services-identity:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-identity/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-identity/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.528 secs

**Comment by shfaizanali** [comment]
I am also facing this issue

**Comment by axelingadi** [comment]
Yeah me too. Same thing.

```
 FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-plus:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-plus/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-plus/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.google.android.gms:play-services-identity:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-identity/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-identity/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by axelingadi** [comment]
Finally figure out how to fix this. You need to have Android Support Repository and Android Support Library installed in the Android SDK manager. This worked for me.

**Comment by EddyVerbruggen** [comment]
@axelingadi indeed, I've now added that to the [README Q&A](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/README.md#7-troubleshooting) to avoid some of the trouble folks may have with it.

**Comment by Maurozac** [comment]
These are the Extras you must add to your SDK packages:

Google Repository
Google Play services

https://developer.android.com/sdk/installing/adding-packages.html

**Comment by kythanh** [comment]
Hi @EddyVerbruggen, below is my Extras SDK status, the issue is still same here. Do you have any advices?
<img width="685" alt="screen shot 2016-04-20 at 11 04 44 pm" src="https://cloud.githubusercontent.com/assets/869405/14681700/72f67770-074c-11e6-9eec-351c0567c1da.png">

**Comment by sammuggPS** [comment]
@kythanh, Hey there! Do you have the Google APIs installed for your target platform? Not sure if it will make a difference, but I have it installed for each of the platforms that includes it.

**Comment by kythanh** [comment]
Hi @sammuggPS, I've fixed my issue now by pointing to correct Android SDK on my mac. 

This one also helped a lot http://stackoverflow.com/a/32559386/3654502.
