### ISSUE TITLE
error: no valid token, how to fix?

### ISSUE THREAD

**Issue by buidinhtuyen** [EddyVerbruggen/cordova-plugin-googleplus#78]

**Comment by charlesmudy** [comment]
Same error here, any solution on this @EddyVerbruggen ?

**Comment by EddyVerbruggen** [comment]
Sounds a bit like #5, perhaps take a look over there? If you still can't find the cause feel free to reopen this issue.

**Comment by buidinhtuyen** [comment]
This problem, I already knew the reason, because i didn't sign for my app,therefore SHA1 doesn't match
