### ISSUE TITLE
what about refresh_token / offline access ?

### ISSUE THREAD

**Issue by zofe** [EddyVerbruggen/cordova-plugin-googleplus#80]
Hi all, I plan to use this plugin to sync users with an already existent web application.
On server, I already have the oauth  logic,  so the cordova app should sync  "new mobile users"  with serverside DB  passing via api any "new" mobile user including the refresh_token for offline access (it's needed by server to do  offline stuff  without user interaction)

I'ts possible with this plugin  ?
how to do that?

thanks

**Comment by phw** [comment]
You can do this using the workflow described in https://developers.google.com/identity/protocols/CrossClientAuth

Basically you need the following:

* In the Google API console define both the Android client and the Web client credentials inside the same project.
* When invoking the googleplus plugin you have to pass the web client id with the (somewhat misleading named) parameter `androidApiKey`

    ```
    window.plugins.googleplus.login({
        androidApiKey: GOOGLE_PLUS.CLIENT_ID
    }, function(result) {
        console.log('One time code: ', result.oauthToken);
        // Pass result.oauthToken to your server
    });
    ```
* You will now get a one time code in `result.oauthToken` which you should pass to your server. The server can then exchange this token for a proper access_token and refresh_token. You are probably already doing this for you web app. The process is explained in https://developers.google.com/+/web/signin/server-side-flow .

One important thing is, that the server should not pass any `redirect_uri` parameter when exchanging the one-time-code into an access token. That's different from the web initiated flow where the server must set `redirect_uri` to `postmessage` as this is what the web client also does. So you need a way to distinguish between the source of the token.

**Comment by phw** [comment]
Also you might want to use the latest git version of this plugin due to PR #119

**Comment by zofe** [comment]
Thanks a lot for the explanation,  really appreciated!
let me close this.
