### ISSUE TITLE
PGB 5.1.1 will build fail that only in android when install from npm

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-googleplus#81]
PGB 5.1.1 will build fail that only in android when install from npm
https://www.npmjs.com/package/cordova-plugin-googleplus
![gradle](https://cloud.githubusercontent.com/assets/5110085/8762625/003ef268-2db1-11e5-8531-36c4453d83bb.jpg)

but if install from "plugins.cordova.io"
http://plugins.cordova.io/#/package/nl.x-services.plugins.googleplus
build all success

**Comment by josschne** [comment]
Duplicate of #64.

**Comment by bau720123** [comment]
thanks @josschne 
I will follow https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/64
