### ISSUE TITLE
Failed to install (REVERSED_CLIENT_ID)

### ISSUE THREAD

**Issue by apalette** [EddyVerbruggen/cordova-plugin-googleplus#89]
Hello,

I've got this error when I try to add the plugin : 

> Failed to install 'cordova.plugin.googleplus':Error: Variable(s) missing: REVERSED_CLIENT_ID

**Comment by balicekt** [comment]
I have the same problem. Did you find solutin?

**Comment by apalette** [comment]
I can install the plugin like this
> cordova plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID
="My bundle identifier (not sure)"

But now, I've got an error when compiling

**Comment by balicekt** [comment]
Yes, I already found solution. And it's working properly:) Which error did you get? 

Did you install playservices? 

cordova plugin add com.google.playservices

Becuase w/o this plugin it doesn't work.

**Comment by apalette** [comment]
No I didn't install playservices. Thanks ;)

**Comment by orrybaram** [comment]
I get this problem also after installing playservices 

```
Failed to install 'cordova.plugin.googleplus':Error: Variable(s) missing: REVERSED_CLIENT_ID
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:306:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
Error: Variable(s) missing: REVERSED_CLIENT_ID
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:306:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
```
Here's my plugin list:

```
$ cordova plugins
com.google.playservices 21.0.0 "Google Play Services for Android"
com.ionic.keyboard 1.0.4 "Keyboard"
com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-file 2.1.0 "File"
cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
cordova-plugin-media-capture 1.0.1 "Capture"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-statusbar 1.0.2-dev "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova.plugin.googleplus 3.0.1 "Google+"
nl.x-services.plugins.socialsharing 4.3.19 "SocialSharing"
org.apache.cordova.network-information 0.2.15 "Network Information"
```

**Comment by balicekt** [comment]
This error is because you didn't put variable. You have to use this: 
cordova plugin add name.of.plugin --variable CLIENT_ID="123456789abcdefghcijklmn"

check this tutorial: http://phonegap-plugins.com/plugins/cabotdeveloper/cordovaplugin-googlepluswithdemoapp

**Comment by orrybaram** [comment]
Thanks that helped!

**Comment by EddyVerbruggen** [comment]
@orrybaram @balicekt Thanks guys, that's missing in the README since recent changes I integrated from a pull request. I will add the correct instructions today.

**Comment by nitin-krisil** [comment]
what is REVERSED_CLIENT_ID. how can i find it ??

**Comment by sammuggPS** [comment]
@nitin-krisil, REVERSED_CLIENT_ID is a property of your iOS configuration file.
Follow the instructions [here](https://developers.google.com/mobile/add?platform=ios&cntapi=signin) to set up your iOS configuration. Your Reversed ClientId will be in the file you can download at the end.

If you already have your iOS client id set up, you can go to your [Developer's Console](https://console.developers.google.com) and get it. It's also called the "iOS URL Scheme."

Please read the README documentation for more information!

**Comment by fducom** [comment]
This page make ID download and move file to root your project.
https://developers.google.com/mobile/add?platform=ios&cntapi=signin
