### ISSUE TITLE
No Cancel Button

### ISSUE THREAD

**Issue by yotamlaufer** [EddyVerbruggen/cordova-plugin-googleplus#90]
When using ionic I don't see an option for the user to cancel login after the google+ window has opened. There is no way to abort the flow once the plugin has been triggered.

**Comment by yotamlaufer** [comment]
<img width="487" alt="screen shot 2015-08-10 at 12 16 34" src="https://cloud.githubusercontent.com/assets/4353345/9166020/0f244ab6-3f5a-11e5-8016-fca27aa00b72.png">

**Comment by EddyVerbruggen** [comment]
That's the consent screen which is not part of the app nor this plugin, so can't help there. Just need to switch back to the app like you'd normally switch between apps.

**Comment by Freundschaft** [comment]
sorry to comment on this issue, but on ios switching back to the app doesnt work because the login window is opened in the application itself, not an external browser, what's the right workaround for this?

**Comment by EddyVerbruggen** [comment]
Thanks to #153 v4.0.6 now has an option to cancel the OAuth flow.
