### ISSUE TITLE
Plugin incompatibility when using Adobe PhoneGap Build

### ISSUE THREAD

**Issue by realtime-framework** [EddyVerbruggen/cordova-plugin-googleplus#98]
One developer called our attention to a conflict between your plugin and our CordovaPush plugin (https://github.com/realtime-framework/CordovaPush) when building for Android using Adobe Build. 

The error is:
"Error - Two of the plugins in your app are incompatible as they both add a file with the same name. View logs to find which plugins are causing this issue."

If we use only one of the plugins the build completes successfully (as expected).

Do you have any clue about what is causing this conflict?  (... it's probably our bad but your help would be appreciated)

Thanks.

**Comment by realtime-framework** [comment]
Building the project using Cordova CLI revealed the error:

> Failed to install 'cordova-plugin-googleplus':Error: Uh oh!
> ".../platforms/android/libs/google-play-services.jar" already exists!

I guess we need to add the Google Play Services dependency as:
```<dependency id="cordova-plugin-googleplayservices" /> ```

**Comment by Freundschaft** [comment]
I think its related to this one: https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/96
